reactor/reactor-netty

src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java
src/main/java/reactor/ipc/netty/options/ClientOptions.java

NoopAddressResolverGroup causes UnknownHostException in some scenarios where the client is configured to use http proxy
The fix is needed for CloudFoundry Java Client library to function behind proxies:
https://github.com/cloudfoundry/cf-java-client/issues/479
Signed-off-by: Tareq Sharafy <tareq.sha@gmail.com>

Allow configuring a custom resolver for proxies in ClientOptions

---

src/main/java/reactor/ipc/netty/http/server/HttpPredicate.java
src/test/java/reactor/ipc/netty/http/server/UriPathTemplateTest.java

Fixes part of https://github.com/reactor/reactor-netty/issues/30

Allow dots in parametrized path segments

---

src/main/java/reactor/ipc/netty/ByteBufFlux.java
src/test/java/reactor/ipc/netty/ByteBufFluxTest.java

Fix issue #34 where the ByteBufFlux was skipping bytes when reading the file.

fix #34 where the ByteBufFlux was skipping bytes when reading the file

---

src/main/java/reactor/ipc/netty/http/client/HttpClient.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
src/main/java/reactor/ipc/netty/http/client/HttpClientRequest.java
src/main/java/reactor/ipc/netty/http/client/HttpClientWSOperations.java
src/main/java/reactor/ipc/netty/http/server/HttpServerWSOperations.java
src/main/java/reactor/ipc/netty/http/websocket/WebsocketInbound.java
src/main/java/reactor/ipc/netty/http/websocket/WebsocketOutbound.java
src/test/java/reactor/ipc/netty/http/WebsocketTests.java

@smaldini can you double-check how I handled the `WebSocketHandshakeException`?
I'm also wondering how we could expose the selected subprotocol to clients, which could come in handy in case they accept several protocols (comma-separated), since the server has to chose one compatible protocol...

fix #20 Support websocket subprotocols in HttpClientRequest

---

src/main/java/reactor/ipc/netty/NettyContext.java
src/main/java/reactor/ipc/netty/channel/ChannelOperations.java
src/main/java/reactor/ipc/netty/channel/ServerContextHandler.java
src/test/java/reactor/ipc/netty/channel/ChannelOperationsTests.java

The default method was just recursively calling itself.
Added an template implementation that can be used by most implementors
in `ChannelOperations`.

fix #23 Make NettyContext.addDecoder non-default

---

src/main/java/reactor/ipc/netty/NettyInbound.java
src/main/java/reactor/ipc/netty/NettyOutbound.java
src/test/java/reactor/ipc/netty/NettyInboundTest.java
src/test/java/reactor/ipc/netty/NettyOutboundTest.java

This commit allows subsequent calls to `onReadIdle` and `onWriteIdle`
APIs with different idle callbacks. Each call will replace the previous
callback by removing any existing idle handler first.
cc @rstoyanchev

fix #22 Let NettyInbound/NettyOutbound idle handlers replace old ones

---

src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
src/main/java/reactor/ipc/netty/http/server/HttpServerOperations.java
src/test/groovy/reactor/ipc/netty/http/HttpSpec.groovy

Fix remaining cases of using reactor-core methods deprecated in 3.0.7 but removed in 3.1.0 that make reactor-netty not usable with reactor-core 3.1.0. 
The two have been out of sync for about a week, since Apr 19 with https://github.com/reactor/reactor-core/commit/df2c6cc64b6d867b7ff662e83e7fd02ecfd10238, but for some reason the Spring Framework build only [started failing](https://build.spring.io/browse/SPR-PUB-4770) today. Perhaps the 3.1.0 snapshots were stale?
Note I did not change all tests to be 3.1.0 compatible since flatMap is deprecated in 3.0.7 but actually needs to be used with 3.1.0 as a replacement for `then`.

Compatibility with current 3.1.0 snapshots

---

src/main/java/reactor/ipc/netty/http/client/MonoHttpClientResponse.java

When making http request to server on non standard port, host header should contain port number.

Add port to HttpClient host header

---

src/main/java/reactor/ipc/netty/NettyPipeline.java
src/main/java/reactor/ipc/netty/ReactorNetty.java
src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java
src/main/java/reactor/ipc/netty/http/client/HttpClient.java
src/main/java/reactor/ipc/netty/http/server/CompressionHandler.java
src/main/java/reactor/ipc/netty/http/server/FilteringHttpContentCompressor.java
src/main/java/reactor/ipc/netty/http/server/HttpServer.java
src/main/java/reactor/ipc/netty/http/server/HttpServerOptions.java
src/test/java/reactor/ipc/netty/http/HttpCompressionClientServerTests.java

This PR adds support for HTTP compression, configured with `HttpServerOptions.Compression` `enabled` and `minResponseSize` parameters. Latter controls compression based on response body size, 0 value means all responses with non-empty body are compressed. Partially addresses #77

conditional HTTP compression

---

build.gradle
src/main/java/reactor/ipc/netty/http/multipart/MultipartParser.java
src/test/groovy/reactor/ipc/netty/http/HttpCookieHandlingSpec.groovy
src/test/groovy/reactor/ipc/netty/http/HttpResponseStatusCodesHandlingSpec.groovy
src/test/groovy/reactor/ipc/netty/http/HttpSpec.groovy
src/test/java/reactor/ipc/netty/http/ClientServerHttpTests.java
src/test/java/reactor/ipc/netty/http/HttpServerTests.java
src/test/java/reactor/ipc/netty/http/SmokeTests.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java
src/test/java/reactor/ipc/netty/http/client/WebsocketTest.java
src/test/java/reactor/ipc/netty/tcp/TcpClientTests.java
src/test/java/reactor/ipc/netty/tcp/TcpServerTests.java

This commit bumps the 0.7 dependency to core 3.1.0.M2 and fixes usages
of the following Mono APIs:
- otherwise has become onErrorResume
- flatMap has become flatMapMany
- then has become flatMap
- subscribe() returns a Disposable, use toProcessor() for old behavior
It also fixes a usage of `Flux.then(Supplier)` to use `Flux.then()` and
a defer instead.

fix #71 bump to core 3.1.0.M2, migrate then/flatMap/toProcessor

---

src/main/java/reactor/ipc/netty/http/server/HttpServerOptions.java
src/test/java/reactor/ipc/netty/http/HttpCompressionClientServerTests.java
src/test/java/reactor/ipc/netty/http/server/HttpServerOptionsTest.java

Rework the tests so that they correctly surface the issue, fix the
option ignoring the threshold and always activating compression.

fix #106 Take HttpServerOptions.compression(int) threshold into account

---

src/main/java/reactor/ipc/netty/http/client/HttpClient.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java
src/main/java/reactor/ipc/netty/http/server/HttpServer.java
src/main/java/reactor/ipc/netty/http/server/HttpServerOptions.java
src/main/java/reactor/ipc/netty/options/ClientOptions.java
src/main/java/reactor/ipc/netty/options/NettyOptions.java
src/main/java/reactor/ipc/netty/options/ServerOptions.java
src/main/java/reactor/ipc/netty/tcp/TcpClient.java
src/main/java/reactor/ipc/netty/tcp/TcpServer.java
src/main/java/reactor/ipc/netty/udp/UdpClientOptions.java
src/test/java/reactor/ipc/netty/http/client/HttpClientOptionsTest.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java
src/test/java/reactor/ipc/netty/http/server/HttpServerOptionsTest.java
src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java
src/test/java/reactor/ipc/netty/options/ClientOptionsTest.java
src/test/java/reactor/ipc/netty/tcp/TcpClientTests.java
src/test/java/reactor/ipc/netty/tcp/TcpServerTests.java

This is useful when the handler cannot be created, to get the original
configuration of the Client/Server object.
The toString() methods for Client/Servers and Options have been aligned,
and each option type has 2 additional String representations (one
detailed as used in toString, the other simplified, as used by the
client/server's toString).

fix #66 Expose duplicate of options for TCP/HTTP Client and Server

---

src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java
src/main/java/reactor/ipc/netty/options/NettyOptions.java
src/test/java/reactor/ipc/netty/http/client/HttpClientOptionsTest.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java

This commit fixes HttpClient not correctly working with SSL activated
when performing a request (eg. get) on a relative url/path.
This was due to HttpClientOptions.formatSchemeAndHostRelative not taking
the SslContext configuration into account when creating a full URL for
such a request, resulting in HTTP requests being performed on a HTTPS
connection.

fix #109 Make HttpClient SSL work on relative GET

---

src/main/java/reactor/ipc/netty/http/server/HttpServerHandler.java

Problem: pendingResponses variable is decreased when
`r.i.n.h.server.HttpServerHandler#write` is invoked with `LastHttpContent`,
but the channel attributes are cleared in the event for termination
`r.i.n.channel.ChannelOperations#onHandlerTerminate`.
New request can be received after invocation of the write operation and
before event for termination.
`r.i.n.h.server.HttpServerHandler#channelRead`
In this situation instead of pipelining the new request the implementation
will check the channel attributes and as they are still not cleared the
request will not be processed.

issue #89: Update pendingResponses in the event for termination

---

src/main/java/reactor/ipc/netty/http/HttpResources.java
src/main/java/reactor/ipc/netty/tcp/TcpResources.java

This commit allows to just shut down the currently set global
TcpResource without replacing it with a new one. It disposes underlying
resources, which helps in server shutdown scenarios.

fix #24 Allow shutdown of global TcpResources

---

src/main/java/reactor/ipc/netty/ByteBufFlux.java
src/main/java/reactor/ipc/netty/ByteBufMono.java
src/main/java/reactor/ipc/netty/FutureMono.java
src/main/java/reactor/ipc/netty/channel/ChannelOperations.java
src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java
src/main/java/reactor/ipc/netty/channel/FluxReceive.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
src/main/java/reactor/ipc/netty/http/client/MonoHttpClientResponse.java
src/main/java/reactor/ipc/netty/http/multipart/MultipartDecoder.java

This commit adapts to the CoreSubscriber change in core by replacing
`subscribe(Subscriber, Context)` methods by `subscribe(CoreSubscriber)`.

Adapt to CoreSubscriber & Context change in reactor-core

---

src/main/java/reactor/ipc/netty/channel/ClientContextHandler.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java
src/main/java/reactor/ipc/netty/options/ClientOptions.java
src/main/java/reactor/ipc/netty/options/ClientProxyOptions.java
src/test/java/reactor/ipc/netty/channel/ClientContextHandlerTest.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java
src/test/java/reactor/ipc/netty/options/ClientOptionsTest.java
src/test/java/reactor/ipc/netty/options/ClientProxyOptionsTests.java

New configuration is added ClientProxyOptions.Builder.nonProxyHosts
that can be used to specify via regular expression
(using java.util.regex) the hosts that should bypass the proxy.

fix #125 Allow configuration of hosts that bypass the proxy

---

src/main/java/reactor/ipc/netty/channel/ClientContextHandler.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java
src/main/java/reactor/ipc/netty/options/ClientOptions.java
src/main/java/reactor/ipc/netty/options/ClientProxyOptions.java
src/test/java/reactor/ipc/netty/channel/ClientContextHandlerTest.java
src/test/java/reactor/ipc/netty/http/client/HttpClientOptionsTest.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java
src/test/java/reactor/ipc/netty/options/ClientOptionsTest.java
src/test/java/reactor/ipc/netty/options/ClientProxyOptionsTests.java

Replace `proxyOptions(ClientProxyOptions)` with `proxy(Consumer<? super ClientProxyOptions.Builder>)` 
Thus instead of this:
```
...proxyOptions(ClientProxyOptions.builder()
.host()
...
.build())
```
one can configure the proxy with:
```
...proxy(ops -> ops.host(...).port(...))
```

Simplify the creation of a proxy configuration

---

src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java
src/test/java/reactor/ipc/netty/http/client/HttpClientOptionsTest.java

This commit fixes the HttpClientOptions to correctly derive relative
urls from the base url, even when a proxy is configured. It would
previously wrongly replace the hostname with `localhost`.

fix #126 Correctly use base hostname in HttpClientOptions even if proxy

---

src/main/java/reactor/ipc/netty/http/HttpResources.java
src/main/java/reactor/ipc/netty/resources/DefaultLoopResources.java
src/main/java/reactor/ipc/netty/resources/DefaultPoolResources.java
src/main/java/reactor/ipc/netty/resources/LoopResources.java
src/main/java/reactor/ipc/netty/resources/PoolResources.java
src/main/java/reactor/ipc/netty/tcp/TcpResources.java
src/test/java/reactor/ipc/netty/http/HttpResourcesTest.java
src/test/java/reactor/ipc/netty/resources/DefaultLoopResourcesTest.java
src/test/java/reactor/ipc/netty/resources/DefaultPoolResourcesTest.java
src/test/java/reactor/ipc/netty/tcp/TcpResourcesTest.java

This commit adds a disposeAndListen method to both LoopResources and
PoolResources that allow to dispose these but also get a notification of
when the disposal is done, in a best effort fashion.
Subsequent calls however are not guaranteed to return a relevant Mono,
which could complete sooner than the actual disposal as triggered by the
first invocation.

fix #25 Allow listen until LoopResource/PoolResources disposal

---

src/main/java/reactor/ipc/netty/http/server/HttpServer.java
src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java

This commit makes port 8080 the default port for HttpServer created
without a specific port. This is a better default for these simple cases
that usually come up during development or testing, as port 80 binding
might be restricted (eg. to root under Linux).

fix #145 The HttpServer now listens on port 8080 by default

---

src/main/java/reactor/ipc/netty/NettyConnector.java
src/main/java/reactor/ipc/netty/http/server/HttpServer.java
src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java

The onStarted is useful to get a reference to the facade, in order to
programmatically shut it down later (eg. when running the startAndAwait
from inside a Thread), but is optional. This adds an override without
the callback.
Additionally, do the same for HttpServer.startRouterAndAwait plus add
tests for both startRouter and startRouterAndAwait.

fix #144 StartAndAwait alias without the onStarted callback

---

src/main/java/reactor/ipc/netty/http/client/MonoHttpClientResponse.java

This commit adds `DELETE` requests to the list of HTTP methods which
shouldn't send `Transfer-Encoding: chunked` request headers by default.
The HTTP specification states that for `GET`, `HEAD` and `DELETE`
requests, a payload has "no defined semantics" and "might cause existing
implementations to reject the request".
See https://tools.ietf.org/html/rfc7231#section-4.3.5
This commit aligns the `DELETE` behavior on other, similar HTTP methods.
See https://jira.spring.io/browse/SPR-15947 for background information.

Don't send chunked transfer for DELETE requests

---

src/main/java/reactor/ipc/netty/options/ServerOptions.java

When `SO_LINGER >= 0` this will specify a timeout value, in seconds (linger interval).
The linger interval is the timeout for the close method to **block**
while the OS attempts to transmit the unsent data. When **0** the OS will not attempt
to transmit the unsend data.
When `SO_LINGER < 0`, then the close method does not wait until unsent data is
transmitted, but if possible the OS will transmit any unsent data before
the connection is closed.
More information `StandardSocketOptions#SO_LINGER`

Do not specify SO_LINGER timeout, JVM default will be used

---

src/main/java/reactor/ipc/netty/http/client/HttpClient.java
src/main/java/reactor/ipc/netty/http/server/HttpServer.java
src/main/java/reactor/ipc/netty/options/ClientOptions.java
src/main/java/reactor/ipc/netty/tcp/TcpClient.java
src/main/java/reactor/ipc/netty/tcp/TcpServer.java
src/main/java/reactor/ipc/netty/udp/UdpClient.java

Create LoopResources/PoolResources only in case the user does not specify their own.

---

src/main/java/reactor/ipc/netty/NettyConnector.java
src/main/java/reactor/ipc/netty/tcp/BlockingNettyContext.java

Increase the default timeout for NettyConnector.start(T) from 3s to 45s.
Introduce a new method NettyConnector.start(T, Duration) so that the
timeout can be explicitly specified.

fix #179: Increase the default timeout, introduce a new method with timeout

---

src/main/java/reactor/ipc/netty/http/client/RedirectClientException.java

- there is no use for the stack trace of `reactor.ipc.netty.http.client.RedirectClientException`

Omit filling stack trace for RedirectClientException

---

src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java

DO NOT COMMIT: this change depends on the change in Netty: SslHandler and update of the pending data. Once 4.1.17.Final is out we can remove the `@Ignore` marker added to the tests and then commit the change.

inner.justFlushed is not needed, hasPendingWriteBytes used instead.

---

src/main/java/reactor/ipc/netty/http/client/UriEndpointFactory.java
src/test/java/reactor/ipc/netty/http/client/UriEndpointFactoryTest.java

- handle parsing URI with query and no path
- [fixes issue reported by @quanticc in the comments of the original PR](https://github.com/reactor/reactor-netty/pull/195#issuecomment-346952336) that introduced `UriEndpointFactory`.

Fix bug in UriEndpointFactory (0.8.x only): handle parsing URI with query and no path

---

src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java
src/test/java/reactor/ipc/netty/http/HttpTests.java

When the writing Publisher completes with an error,
the error signal must be propagated to the subscriber.

fix #231: Ensure error signal is propagated

---

src/main/java/reactor/ipc/netty/http/client/HttpClient.java
src/main/java/reactor/ipc/netty/http/client/HttpClientConnect.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
src/main/java/reactor/ipc/netty/http/client/HttpClientRequest.java
src/test/java/reactor/ipc/netty/http/client/HttpClientOperationsTest.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java
src/test/java/reactor/ipc/netty/http/client/HttpRedirectTest.java
src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java

The support for `followRedirect` per `HttpClientRequest` is removed.

fix #235: Allow setting followRedirect per HttpClient

---

src/main/java/reactor/ipc/netty/http/client/HttpClient.java
src/main/java/reactor/ipc/netty/http/client/HttpClientConnect.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
src/main/java/reactor/ipc/netty/http/client/HttpClientRequest.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java

The support for chunkedTransfer per HttpClientRequest is removed.

fix #94 : Allow setting chunkedTransfer per HttpClient

---

src/main/java/reactor/ipc/netty/http/server/HttpServer.java
src/main/java/reactor/ipc/netty/http/server/HttpServerOptions.java
src/test/java/reactor/ipc/netty/http/server/HttpServerOptionsTest.java

This is a redo of #252 that fixes #150 in a way closer to the 0.8 version (#256), at least in the way all 5 parameters are exposed in the builder API independently.

Redo #150 http codec config on 0.7

---

src/main/java/reactor/ipc/netty/channel/BootstrapHandlers.java

`(Tcp|Udp|Http)Client/Server#wiretap` will add to the pipeline
`SslLoggingHandler` when `reactor.netty.tcp.ssl.client.debug`/
`reactor.netty.tcp.ssl.server.debug` system properties are enabled.
It will be placed before `SslHandler`.

fix #227: Introduce properties for enabling ssl debugging

---

src/main/java/reactor/ipc/netty/http/server/HttpServerOperations.java
src/test/java/reactor/ipc/netty/http/client/WebsocketTest.java

Ensure server will send a response in case websocket upgrade failure

---

src/main/java/reactor/ipc/netty/http/client/MonoHttpClientResponse.java

When HttpClient receives AbortedException/IOException, it will retry once
and then will return the exception so that the user can decide how many
retries to do and with what delay.

fix #257: Retry once in case of AbortedException/IOException

---

src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java
src/main/java/reactor/ipc/netty/options/NettyOptions.java

This is a draft PR for gh-222.
Netty client doesn't enable hostname verification in its client SSL Context by default (see [this warning](https://netty.io/4.1/api/io/netty/handler/ssl/SslContext.html#newHandler-io.netty.buffer.ByteBufAllocator-)).
I've just tested that change against badssl.com - but I'm willing to improve that PR in any way you'd like.

Enable hostname verification in client SSL config

---

src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java
src/main/java/reactor/ipc/netty/options/NettyOptions.java

Reverts reactor/reactor-netty#273

Revert "Enable hostname verification in client SSL config"

---

src/main/java/reactor/ipc/netty/channel/PooledClientContextHandler.java
src/main/java/reactor/ipc/netty/resources/DefaultPoolResources.java
src/test/java/reactor/ipc/netty/resources/DefaultPoolResourcesTest.java
src/test/java/reactor/ipc/netty/tcp/TcpClientTests.java

Instead of setting up the close listener in the ChannelPoolHandler
channelCreated method, set it up in the PooledClientContextHandler.
This should prevent the listener to be invoked after a FixedChannelPool
has determined the channel was not healthy and has already decremented
its internal acquire counter (which would lead to a second decrement of
said counter and an assertion error).

fix #289 Register pool-releasing close listener only if acquired

---

src/main/java/reactor/ipc/netty/http/HttpOperations.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
src/main/java/reactor/ipc/netty/http/server/HttpServerHandler.java
src/main/java/reactor/ipc/netty/http/server/HttpServerOperations.java
src/test/java/reactor/ipc/netty/http/HttpTests.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java
src/test/java/reactor/ipc/netty/resources/DefaultPoolResourcesTest.java

HttpServerHandler now write informational response separately.
In order to fully work the fix correctly defers header sending on subscribe.
This can give precedence to the expect100Continue logic in receiveObject()

fix #293 support expect 100-continue

---

src/main/java/reactor/ipc/netty/http/HttpOperations.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
src/main/java/reactor/ipc/netty/http/server/HttpServer.java
src/main/java/reactor/ipc/netty/http/server/HttpServerOperations.java
src/main/java/reactor/ipc/netty/http/server/HttpServerOptions.java
src/test/java/reactor/ipc/netty/http/HttpCompressionClientServerTests.java

HttpServerBuilder now exposes a compression(BiPredicate<Req,Res>).
The predicate is evaluated before committing response header/status.
If the predicate is true, compression is enabled for the given response.
The minimum compression threshold now uses content-length predicate.

fix #218 add predicate based http server compression

---

src/main/java/reactor/ipc/netty/http/server/HttpServerHandler.java
src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java

When the decoding failed with `TooLongFrameException`, `413 Request
Entity Too Large` will be returned otherwise `400 Bad Request`

fix #309 In case there is a failure while decoding the request, return 4xx response

---

src/main/java/reactor/ipc/netty/channel/ChannelOperations.java
src/main/java/reactor/ipc/netty/resources/DefaultLoopResources.java
src/test/java/reactor/ipc/netty/tcp/TcpResourcesTest.java

Prevent bifunction handler propagation and close the connection.

fix #312 - Add reactor core 3.1.6 non blocking thread marker support

---

src/main/java/reactor/ipc/netty/NettyOutbound.java
src/main/java/reactor/ipc/netty/channel/data/AbstractFileChunkedStrategy.java

- replace shared state with check each time
- remove redundant check in NettyOutbound.sendFileChunked

Don't share pipeline state in fields of the FileChunkedStrategy instance

---

src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java
src/test/java/reactor/ipc/netty/http/server/HttpsSendFileTests.java

When onNext event is sent and the previous thread was not in an event loop then
the write will be delayed. Then when onComplete/onError event is sent, the
implementation need to check the pending writes and also the delayed.

fix #321: Handle the delayed writes when onComplete/onError event is sent

---

src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java

Take in account the delayed writes when calculating the requested
and produced items when onComplete/onError event is sent.

fix #316 Correctly calculate the requested and produced items

---

build.gradle
src/main/java/reactor/ipc/netty/NettyOutbound.java

Change the dependency to netty-transport-native-epoll to the one with linux-x86_64 classifier

fix #329 Change the dependency to netty-transport-native-epoll

---

build.gradle
src/docs/asciidoc/index.asciidoc
src/main/java/reactor/ipc/netty/NettyOutbound.java
src/main/java/reactor/ipc/netty/channel/ChannelOperations.java
src/main/java/reactor/ipc/netty/channel/ContextHandler.java
src/main/java/reactor/ipc/netty/channel/PooledClientContextHandler.java
src/main/java/reactor/ipc/netty/http/HttpOperations.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
src/main/java/reactor/ipc/netty/resources/DefaultLoopResources.java
src/main/java/reactor/ipc/netty/tcp/TcpClient.java
src/test/java/reactor/ipc/netty/NettyOutboundTest.java
src/test/java/reactor/ipc/netty/http/server/UriPathTemplateTest.java
src/test/java/reactor/ipc/netty/tcp/TcpClientTests.java

- suppress unchecked warnings in disposeLater method
- fix warning in asciidoc rendering about missing file
- fix unchecked warnings in tests
- enable rawtypes linting
- resolve or suppress warnings related to rawtypes

Fix and suppress compilation and build warnings

---

build.gradle
gradle/doc.gradle

- use recent versions that work
- move asciidoctor related config to separate file from build.gradle

Improve asciidoctor configuration in build

---

build.gradle
gradle/errorprone.gradle

- enable [errorprone](http://errorprone.info/) compiler plugin in build
- for now, errorprone errors are converted to warnings with the [`-XepAllErrorsAsWarnings` flag](http://errorprone.info/docs/flags)

Enable errorprone compiler plugin in build

---

src/main/java/reactor/ipc/netty/http/server/HttpServerRoutes.java

It would be great to have a more general predicate.

Improved ws condition support

---

build.gradle
src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java

- Contains a change to a test since it broke after upgrading
- Netty 4.1.25 contains https://github.com/netty/netty/pull/7891 , which changed the behaviour
of HTTP status code 205 / Reset Content
- the behaviour now conforms to [RFC 7231, section 6.3.6](https://tools.ietf.org/html/rfc7231#section-6.3.6)

 Update Netty version to 4.1.25.Final

---

src/main/java/reactor/netty/channel/BootstrapHandlers.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/tcp/SslProvider.java
src/main/java/reactor/netty/tcp/TcpClient.java
src/main/java/reactor/netty/tcp/TcpClientConnect.java
src/main/java/reactor/netty/tcp/TcpClientOperator.java
src/main/java/reactor/netty/tcp/TcpClientRunOn.java
src/main/java/reactor/netty/tcp/TcpClientSecure.java
src/main/java/reactor/netty/tcp/TcpClientUnsecure.java
src/main/java/reactor/netty/tcp/TcpServer.java
src/main/java/reactor/netty/tcp/TcpServerBind.java
src/main/java/reactor/netty/tcp/TcpServerOperator.java
src/main/java/reactor/netty/tcp/TcpServerRunOn.java
src/main/java/reactor/netty/tcp/TcpServerSecure.java
src/main/java/reactor/netty/tcp/TcpServerUnsecure.java

* make sure https is used in the uri factory if default secure
* remove ssl if absolute http is used in a redirect
* align server/client ssl conf accessor to expose SslProvider
* expose removeSslSupport in SslProvider
* fix BootstrapHandlers.findConfiguration for deferred confs

fix ssl configuration issue for tcp and http clients

---

src/main/java/reactor/netty/http/server/ConnectionInfo.java
src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

The "X-Forwarded-For" request header is about the remote host
information, not the server host information.

Fix X-Forwarded-For support

---

src/main/java/reactor/netty/http/server/HttpServer.java
src/main/java/reactor/netty/http/server/HttpServerSecure.java
src/main/java/reactor/netty/tcp/SslProvider.java
src/main/java/reactor/netty/tcp/TcpServer.java
src/test/java/reactor/netty/http/HttpTests.java
src/test/java/reactor/netty/tcp/TcpServerTests.java

Document in javadoc how ssl with self singed certificate can be used.
Expose API for choosing the default SslContext configuration
Related to issue #382

fix #370 Remove TcpServer/HttpServer API for using ssl with self singed certificate

---

src/main/java/reactor/netty/ChannelBindException.java
src/main/java/reactor/netty/http/server/HttpServerConfiguration.java
src/main/java/reactor/netty/resources/NewConnectionProvider.java
src/main/java/reactor/netty/tcp/TcpServerBind.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

Remove unused code
Fix for #368

Add explicit bind exception

---

src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/WebsocketFinalizer.java

Having access to the underlying Connection for websocket/http2 as in TCP makes it more natural to implement DuplexConnection in RSocket. So instead of having to use the 'handle' method and cast:
`.<DuplexConnection>handle((in, out) -> Mono.just(new WebsocketDuplexConnection((Connection) in)))`
We can instead do:
`.connect().map(WebsocketDuplexConnection::new);`

Expose connect() method for websocket connections

---

src/main/java/reactor/netty/resources/PooledConnectionProvider.java
src/test/java/reactor/netty/http/client/HttpClientTest.java

after channel released *operationComplete* will clean OWNER in channel
but the same channel will be reused once it released, it's not atomic
there will be chance the new subscriber set the OWNER then the old *operationComplete* clean the OWNER in different thread so the new subscriber will never complete.
so I move the clean procedure before release.

fix #405 channel reused before old OWNER is cleaned

---

src/main/java/reactor/ipc/netty/http/server/HttpServerHandler.java

Release the incoming message when the decoding failed

---

src/main/java/reactor/ipc/netty/NettyPipeline.java
src/main/java/reactor/ipc/netty/http/server/AccessLogHandler.java
src/main/java/reactor/ipc/netty/http/server/HttpServer.java
src/test/resources/logback.xml

Only `CLF` is supported
`-Dreactor.netty.http.server.accessLogEnabled=true` can be used to enable access log (by default it is disabled)
The configuration below (logback) or similar (other logging frameworks) can be used to have a separate access log file
```
<appender name="accessLog" class="ch.qos.logback.core.FileAppender">
<file>access_log.log</file>
<encoder>
<pattern>%msg%n</pattern>
</encoder>
</appender>
<appender name="async" class="ch.qos.logback.classic.AsyncAppender">
<appender-ref ref="accessLog" />
</appender>
<logger name="reactor.netty.http.server.AccessLog" level="INFO" additivity="false">
<appender-ref ref="async"/>
</logger>
```

fix #301 Add Http Server Access Log

---

src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConfiguration.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientOperations.java
src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
src/test/java/reactor/netty/http/client/WebsocketTest.java

Our current use case requires overriding the default value and as #223 shows there is no way to do this from HttpClient API.

Fix #223 Allow custom websocket maxFramePayloadLength

---

src/main/java/reactor/netty/http/client/HttpClientConnect.java

If a baseUrl ends with a slash, one extra character removed from the end of it.

Fix extra character trimming if baseUrl ends with a slash

---

src/main/java/reactor/netty/http/client/HttpClientConnect.java

Generate correct HOST header when IPv6 with scope_id

---

src/main/java/reactor/ipc/netty/ByteBufFlux.java
src/main/java/reactor/ipc/netty/ByteBufMono.java

This change handles the use case below:
When there is the sequence
```
.aggregate()
.asString()
```
If a timeout happens while in `aggregate()` the composite byte buffer
will be released. Later when `asString()` is invoked
`IllegalReferenceCountException` will be throws:
```
io.netty.util.IllegalReferenceCountException: refCnt: 0
at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1417)
at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1356)
at io.netty.buffer.AbstractByteBuf.checkDstIndex(AbstractByteBuf.java:1376)
at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:854)
at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:44)
at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:230)
at …
```

Handle IllegalReferenceCountException in ByteBuf(Flux|Mono)#as... methods

---

src/main/java/reactor/ipc/netty/NettyOutbound.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
src/main/java/reactor/ipc/netty/http/client/HttpClientWSOperations.java
src/main/java/reactor/ipc/netty/http/server/HttpServerWSOperations.java
src/main/java/reactor/ipc/netty/http/websocket/WebsocketOutbound.java
src/test/java/reactor/ipc/netty/http/client/WebsocketTest.java

Prepare to send a close frame on subscribe then close the
underlying channel. Any previous publisher will be canceled.
Clarify that nesting NettyOutbound#send* methods is not supported.
Related to #444

Add WebsocketOutbound#sendClose() API

---

src/main/java/reactor/ipc/netty/http/client/HttpClient.java
src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java
src/main/java/reactor/ipc/netty/tcp/TcpClient.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java

In case of `HttpClient` used with a specified request type and no connect address,
it will be calculated based on the `url` (`HttpClientOptions#formatSchemeAndHost`).
In case no request type is specified, but `newHandler` is used, the `HttpClient` will try
to connect to `https://localhost`.
```
java.lang.NullPointerException
at reactor.ipc.netty.resources.DefaultPoolResources$SocketAddressHolder.hashCode(DefaultPoolResources.java:294)
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at reactor.ipc.netty.resources.DefaultPoolResources.selectOrCreate(DefaultPoolResources.java:73)
at reactor.ipc.netty.tcp.TcpResources.selectOrCreate(TcpResources.java:157)
at reactor.ipc.netty.tcp.TcpClient.lambda$newHandler$1(TcpClient.java:181)
at …
```

Avoid NPE when a connect address isn't specified and newHandler is in use

---

src/main/java/reactor/netty/tcp/SslProvider.java
src/test/java/reactor/netty/tcp/SslProviderTests.java

Default HTTP2 configuration will use SslProvider.OPENSSL when OpenSSL#isAlpnSupported

fix #491 Default TCP configuration will use SslProvider.OPENSSL when OpenSSL#isAvailable

---

src/main/java/reactor/ipc/netty/http/client/HttpClientException.java
src/main/java/reactor/ipc/netty/http/client/MonoHttpClientResponse.java
src/test/java/reactor/ipc/netty/http/HttpTests.java
src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java

HttpClientException holds HttpResponse, when it is FullHttpResponse
it should be released. RedirectClientException extends HttpClientException,
so when do a redirection ensure the response is released.

When redirecting ensure the HttpResponse is released

---

src/main/java/reactor/ipc/netty/FutureMono.java
src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java

When there is `Connection: close` and `Content-Length: 0`
`Reactor Netty` prepares for as outgoing message
`DefaultFullHttpRequest`/`DefaultFullHttpResponse` and closes the connection.
`FutureMono` should not continue with writing the data.

fix #508 If the channel is not active do not continue with writing

---

src/main/java/reactor/netty/http/server/Http2StreamBridgeHandler.java
src/main/java/reactor/netty/http/server/HttpServerOperations.java
src/main/java/reactor/netty/http/server/HttpToH2Operations.java
src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

`doOnConnection` is invoked when `HttpServer` reaches state `CONFIGURED`.
On that state the user can add new handlers to the channel pipeline, because
of that the state's change must happen before `ChannelOperationsHandler`,
otherwise the new handlers will miss the first `channelRead` event.

fix #525 HttpServer CONFIGURED moved to HttpTrafficHandler/Http2StreamBridgeHandler

---

src/main/java/reactor/netty/channel/ChannelOperations.java
src/main/java/reactor/netty/channel/FluxReceive.java
src/main/java/reactor/netty/http/client/HttpClientFinalizer.java
src/main/java/reactor/netty/http/client/WebsocketFinalizer.java

- HttpClientFinalizer and WebclientFinalizer now trigger discard()
- Do not check for isDisposed but rather inbound only
- Merge FluxReceive#discard into cancel()

fix #529 Fix HttpClientFinalizer cleanup for interrupted responses

---

src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConfiguration.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientOperations.java
src/test/java/reactor/netty/http/client/HttpClientOperationsTest.java
src/test/java/reactor/netty/http/client/HttpRedirectTest.java

`reactor.netty.http.client.HttpClient#followRedirect(boolean)` will redirect when
`301`|`302`|`307`|`308`
`reactor.netty.http.client.HttpClient#followRedirect(
BiPredicate<HttpClientRequest,HttpClientResponse>)` will redirect based on
the predicate

fix #522 New HttpClient API to allow configuring redirects via a predicate

---

src/main/java/reactor/ipc/netty/FutureMono.java
src/main/java/reactor/ipc/netty/NettyOutbound.java
src/main/java/reactor/ipc/netty/ReactorNetty.java
src/main/java/reactor/ipc/netty/http/client/HttpClientWSOperations.java
src/main/java/reactor/ipc/netty/http/server/HttpServerHandler.java
src/main/java/reactor/ipc/netty/http/server/HttpServerWSOperations.java
src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java

When Connection:close invoke first cleanup so that the cancelation
is propagated to the publishers and then close the connection

When Content-Length:0 release the Object scheduled for writing

---

src/main/java/reactor/netty/ByteBufFlux.java
src/main/java/reactor/netty/ByteBufMono.java
src/main/java/reactor/netty/NettyOutbound.java
src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
src/test/java/reactor/netty/NettyOutboundTest.java
src/test/java/reactor/netty/http/ClientServerHttpTests.java
src/test/java/reactor/netty/http/HttpOperationsTest.java
src/test/java/reactor/netty/http/client/PostAndGetTests.java
src/test/java/reactor/netty/http/client/WebsocketTest.java
src/test/java/reactor/netty/http/server/HttpServerTests.java
src/test/java/reactor/netty/tcp/TcpServerTests.java
src/test/java/reactor/netty/udp/UdpClientTest.java

ByteBuf#(write|read)CharSequence methods have optimisations for
CharsetUtil.US_ASCII
CharsetUtil.ISO_8859_1
CharsetUtil.UTF_8

Use ByteBuf#(write|read)CharSequence when transforming from/to String

---

src/main/java/reactor/netty/ChannelBindException.java
src/main/java/reactor/netty/resources/NewConnectionProvider.java
src/test/java/reactor/netty/udp/UdpServerTests.java

When native transport (`epoll` | `kqueue`) is used the exception that is
thrown is
`io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use`

Correctly wrap BindException when native transport

---

src/main/java/reactor/netty/http/client/HttpClientOperations.java
src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
src/main/java/reactor/netty/http/server/HttpServerOperations.java
src/main/java/reactor/netty/http/server/HttpToH2Operations.java

Message may have content only when it is FullHttpResponse/FullHttpRequest

fix #595 Ensure message is released when I/O handler throws RuntimeException

---

src/main/java/reactor/netty/tcp/TcpServerBind.java

treat it as client side error
Log level will be DEBUG instead of ERROR
```
java.io.IOException: An existing connection was forcibly closed by the remote host
at sun.nio.ch.SocketDispatcher.read0(Native Method)
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:192)
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
at …
```

fix #555 When IOException happens on the server while reading/writing

---

src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConfiguration.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java

By default `Transfer-Encoding: chunked` will be applied for those HTTP methods
for which a request body is expected. If the user wants to disable that setting
then the user can provide `Content-Length` via request headers and
thus `Transfer-Encoding` will be removed.

fix #553 Remove the deprecated HttpClient#chunkedTransfer

---

src/main/java/reactor/netty/http/server/ConnectionInfo.java
src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

parseAddress changed to check number of ':' separators to infer ipv4 vs. ipv6. For ipv6 addresses, only parse last segment if following correct bracket notation required for ipv6 with ports.
This allows for valid, no-port ipv6 addresses that do not use bracket notation to be provided in forward headers without throwing NumberFormatException.
Added specific tests for these cases and updated tearDown to account for added tests not creating connection object.

fix #625 Update ConnectionInfo#parseAddress behavior to handle ipv6 addresses without bracket

---

build.gradle
gradle/doc.gradle
gradle/setup.gradle
gradle/wrapper/gradle-wrapper.properties
settings.gradle

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://github.com/reactor migrated to:  
https://github.com/reactor ([https](https://github.com/reactor) result 200).
* http://www.apache.org/licenses/LICENSE-2.0 migrated to:  
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).
* http://www.apache.org/licenses/LICENSE-2.0.txt migrated to:  
https://www.apache.org/licenses/LICENSE-2.0.txt ([https](https://www.apache.org/licenses/LICENSE-2.0.txt) result 200).

URL Cleanup

---

src/main/java/reactor/netty/resources/PooledConnectionProvider.java

When a channel is first released to the pool and then closed the
exception below will be created, that's because `release` will be
called twice. In order to prevent the exception creation
check for channel attribute `channelPool` when `closed channel` event
is received and only if it is present then release the channel.
```
java.lang.IllegalArgumentException.<init>(String) IllegalArgumentException.java:52
io.netty.channel.pool.SimpleChannelPool.doReleaseChannel(Channel, Promise) SimpleChannelPool.java:300
io.netty.channel.pool.SimpleChannelPool.release(Channel, Promise) SimpleChannelPool.java:281
io.netty.channel.pool.SimpleChannelPool.release(Channel) SimpleChannelPool.java:271
reactor.netty.resources.PooledConnectionProvider$Pool.release(Channel) PooledConnectionProvider.java:254 …
```

Do not release the channel twice

---

src/main/java/reactor/netty/channel/ChannelOperations.java
src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
src/main/java/reactor/netty/http/client/HttpClientDoOn.java
src/test/java/reactor/netty/http/client/HttpClientTest.java

Send `Disconnecting` when ChannelOperations#setSuccess/tryFailure/setFailure

fix #651 Ensure context is available when HttpClient#doAfterResponse

---

src/main/java/reactor/netty/resources/PooledConnectionProvider.java

When a channel is acquired and closed immediately, re-acquire only once.
If the second attempt also fails return an error and let the user decide to retry
or not.
Ensure the channel is released to the pool so that the pool updates the counters,
this is in case of FixedChannelPool.

fix #653 When a channel is acquired and closed immediately re-acquire only once

---

src/main/java/reactor/netty/http/client/HttpClientOperations.java
src/test/java/reactor/netty/http/client/HttpClientTest.java

Use composite buffer - it is responsible to release the original buffer when it is copied.

fix #694 Ensure HttpClientOperations#send(Publisher) does not leak when GET request

---

src/main/java/reactor/netty/channel/BootstrapHandlers.java

When run the following code:
```
DisposableServer disposableServer = HttpServer.create()
.port(8080)
.wiretap(false)
.bindNow();
disposableServer.onDispose().block();
```
NullPointerException appears:
```
java.lang.NullPointerException: childHandler
at io.netty.bootstrap.ServerBootstrap.childHandler(ServerBootstrap.java:134)
at reactor.netty.channel.BootstrapHandlers.removeConfiguration(BootstrapHandlers.java:169)
at reactor.netty.http.server.HttpServer.lambda$wiretap$17(HttpServer.java:416)
at reactor.netty.tcp.TcpServerBootstrap.configure(TcpServerBootstrap.java:39)
at reactor.netty.tcp.TcpServerBootstrap.configure(TcpServerBootstrap.java:39)
at reactor.netty.tcp.TcpServer.bind(TcpServer.java:143)
at reactor.netty.http.server.HttpServerBind.bind(HttpServerBind.java:96)
at …
```

Fix NullPointerException.

---

src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/test/java/reactor/netty/http/client/HttpClientTest.java
src/test/java/reactor/netty/http/client/WebsocketTest.java

Adapt `reactor.netty.http.client.WebsocketTest` to the change:
as the I/O handler is applied as the last observer, the availability of
`NettyPipeline.WsCompressionHandler` cannot be checked using
`doOnConnected`, because the compression handler is applied
as part of the I/O handler, however the test checks whether the
corresponding compression handler is available so it can be
checked in the `handle` method.

fix #558 Ensure doOnRequest is invoked before the actual request

---

src/main/java/reactor/netty/http/server/HttpServerOperations.java
src/main/java/reactor/netty/http/server/HttpTrafficHandler.java

Instead of checking whether the headers are sent (which does the invocation of
`HttpServerOperations#chunkedTransfer(true)`).
In `HttpServerOperations#preSendHeadersAndStatus()` there is no need to check
`Transfer-Encoding` and `Content-Length`, this is done in `HttpTrafficHandler#write`.

When creating HttpServerOperations directly set a header "Transfer-Encoding: chunked"

---

src/main/java/reactor/netty/http/server/HttpRequestDecoderSpec.java

This change is only for 0.8.x it will not be ported to 0.9.x

Override reactor.netty.http.HttpDecoderSpec methods to keep compatibility in 0.8.x

---

src/main/java/reactor/netty/ReactorNetty.java

When the message is sent successfully the buffer will
be released by Netty.
In addition to #699

Invoke cleanup only when cancel/error event

---

build.gradle
src/jarFileTest/java/reactor/netty/AbstractJarFileTest.java
src/jarFileTest/java/reactor/netty/JarFileShadingTest.java

- for now, we strip the native image metadata
- OSGI excludes could be generated automatically, but it requires an additional effort and can be done separately

Shade Netty's HAProxy, Proxy and HTTP/2

---

src/test/java/reactor/netty/channel/FluxReceiveTest.java
src/test/java/reactor/netty/http/HttpResponseStatusCodesHandlingTests.java
src/test/java/reactor/netty/http/client/HttpClientTest.java
src/test/java/reactor/netty/http/client/UriEndpointFactoryTest.java
src/test/java/reactor/netty/http/server/HttpServerTests.java
src/test/java/reactor/netty/tcp/InetSocketAddressUtilTest.java
src/test/java/reactor/netty/tcp/TcpClientTests.java
src/test/java/reactor/netty/tcp/TcpServerTests.java

This is motivated by the fact that example.com is a reserved domain
for such tests, which should be enough for GET 200 and 404 tests.
The only exception is postUpload, which uses POST and form encoding.
It has been changed to use http://httpbin.org, which is also a
domain set up for testing (although privately owned).

Use example.com urls instead of foo/google

---

src/main/java/reactor/netty/resources/DefaultLoopResources.java

As was suggested by @normanmaurer, we should extend from `FastThreadLocalThread`.
`FastThreadLocal` is a special optimization in Netty that is faster than JVM's ThreadLocals in Netty's use cases

Extend `EventLoop` from Netty's `FastThreadLocalThread`

---

src/main/java/reactor/netty/http/server/ConnectionInfo.java
src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

Related to #625#issuecomment-498604554

Use the default port when cannot extract the port from forwarded headers.

---

src/main/java/reactor/netty/http/server/ConnectionInfo.java
src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

Related to #625#issuecomment-506403990

Use the correct address when cannot extract the port from forwarded headers

---

src/main/java/reactor/netty/NettyOutbound.java
src/main/java/reactor/netty/ReactorNetty.java
src/main/java/reactor/netty/channel/ChannelOperations.java
src/main/java/reactor/netty/channel/MonoSend.java
src/main/java/reactor/netty/channel/MonoSendMany.java
src/main/java/reactor/netty/http/HttpOperations.java
src/test/java/reactor/netty/NettyOutboundTest.java
src/test/java/reactor/netty/channel/MonoSendManyTest.java

Implement NettyOutbound.sendGroup with one send operation

Add NettyOutbound.send/sendObject API with a predicate for enforcing flush operation

---

src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
src/main/java/reactor/netty/http/server/WebsocketServerOperations.java

Removing reactive bridge was added as a fix for #444.
The removing functionality forces PublisherSender to invoke cancel
and ChannelOperationsHandler to drain the queued messages.
As PublisherSender functionality is not part of ChannelOperationsHandler
anymore there is no need to remove ChannelOperationsHandler from the pipeline.

fix #768 Do not remove the reactive bridge in case of a close frame.

---

src/docs/asciidoc/http-server.adoc

According to https://github.com/reactor/reactor-netty/issues/387#issuecomment-404280715

Documentation fix for error: "neither SslContextBuilder nor SslContext is specified"

---

src/main/java/reactor/netty/NettyOutbound.java
src/main/java/reactor/netty/NettyPipeline.java

There is not need of a flush strategy as a result of the changes
in the write/flush operations implementation.

Deprecate NettyOutbound.options and NettyPipeline.SendOptions

---

build.gradle
src/main/java/reactor/netty/Metrics.java
src/main/java/reactor/netty/NettyPipeline.java
src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java
src/main/java/reactor/netty/http/server/HttpServer.java
src/main/java/reactor/netty/http/server/HttpServerBind.java
src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java
src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
src/main/java/reactor/netty/tcp/TcpClient.java
src/main/java/reactor/netty/tcp/TcpMetricsHandler.java
src/main/java/reactor/netty/tcp/TcpServer.java
src/main/java/reactor/netty/tcp/TcpUtils.java
src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
src/test/java/reactor/netty/http/HttpsMetricsHandlerTests.java
src/test/java/reactor/netty/tcp/TcpMetricsTests.java
src/test/java/reactor/netty/tcp/TcpSecureMetricsTests.java
src/test/resources/grafana_dashboard.json

Add TCP/HTTP Metrics

---

src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/tcp/TcpClientConnect.java
src/main/java/reactor/netty/tcp/TcpClientRunOn.java

Revert change 7393c610518fdfbbe15dca0e06a80656cd9b7d16.
It is not relevant anymore because of the switch to Reactor Pool.

Enable ColocatedEventLoopGroup for the client

---

src/main/java/reactor/netty/channel/MonoSendMany.java
src/test/java/reactor/netty/channel/MonoSendManyTest.java

This commit also makes sure producer errors are serialized after queue drain

fix #807 Safely call removeListener on MonoSendMany terminal signal

---

src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
src/main/java/reactor/netty/http/websocket/WebsocketInbound.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

This PR provides `receiveCloseStatus` for `WebSocketInbound`

#533 drafts `receiveCloseStatus` method

---

src/main/java/reactor/netty/FutureMono.java
src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
src/main/java/reactor/netty/channel/FluxReceive.java
src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
src/test/java/reactor/netty/http/client/HttpRedirectTest.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

Close the connection when the follow redirect predicate throws RuntimeException
Close the connection when trying to release the ByteBuf in FluxReceive#drainReceiver.

fix #825 Close the connection when the compression predicate throws RuntimeException

---

build.gradle
src/main/java/reactor/netty/ByteBufFlux.java

The dependency to reactor-pool should exclude the transitive dependency to reactor-core

Adapt to Mono.using changes

---

src/main/java/reactor/netty/http/server/Http2StreamBridgeHandler.java
src/main/java/reactor/netty/http/server/HttpServerBind.java
src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

reactor-netty supports users to add some netty handlers themselves, So we add a SniHandler to the handler chain to let our server to support sni, this worked well, but recently when we upgrade the reactor-netty to `0.8.11.RELEASE`, we found that it will  lost `https` schema when the http request is routed to upstream. 
This PR tries to fix this problem, detect whether secure or not when the first http request comes, so  users can add SniHandler or SslHandler themselves, without using the reactor-netty's api to support more customized requirement.

Detect whether secure or not when the first http request comes to support  SniHandler added by user.

---

src/main/java/reactor/netty/http/HttpResources.java
src/main/java/reactor/netty/resources/ConnectionProvider.java
src/main/java/reactor/netty/resources/LoopResources.java
src/main/java/reactor/netty/tcp/TcpResources.java
src/main/java/reactor/netty/udp/UdpResources.java

Specify fire-and-forget disposeLoopsAndConnections() behaviour for
TcpResources, HttpResources
Specify fire-and-forget shutdown() behaviour for UdpResources

fix #850 Specify fire-and-forget dispose() behaviour for LoopResources, ConnectionProvider

---

src/main/java/reactor/netty/http/server/ConnectionInfo.java
src/main/java/reactor/netty/http/server/HAProxyMessageReader.java
src/main/java/reactor/netty/http/server/Http2StreamBridgeHandler.java
src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

HAProxyMessage is sub class of `ReferenceCounted`, so it should be released to avoid memory leak.
And `REMOTE_ADDRESS_FROM_PROXY_PROTOCOL` attribute should not be removed from  channel, or else the second http request and the subsequent requests in the same connection will lose the removeAddress info.

HAProxyMessage should be released to avoid memory leak.

---

src/main/java/reactor/netty/http/server/HAProxyMessageDetector.java
src/main/java/reactor/netty/http/server/HttpServer.java
src/main/java/reactor/netty/http/server/ProxyProtocolSupportType.java
src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

We are using the following architecture: 
```
User's Http Request -> HaProxy(with proxy protocol enabled) -> spring-cloud-gateway -> realServer.
```
We configured the spring-cloud-gateway to enable proxy protocol support, but this bring us a new problem: it is hard to check if `spring-cloud-gateway` is alive,  most http health check tools does not support proxy protocol, so if `spring-cloud-gateway` can support proxy-protocol-enabled/proxy-protocol-disabled requests at the same time, it should be better.
So I create this PR to support proxy-protocol `AUTO` mode, this mode can auto detect whether the client(or reverse proxy server) has enabled proxy protocol, so the `HttpServer` can support proxy-protocol-enabled and proxy-protocol-disabled clients at the same time.
The proxy-protocol auto …

Add proxy protocol auto detect feature.

---

src/main/java/reactor/netty/ReactorNetty.java
src/main/java/reactor/netty/channel/BootstrapHandlers.java
src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
src/main/java/reactor/netty/channel/MonoSendMany.java
src/main/java/reactor/netty/http/HttpOperations.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientOperations.java
src/main/java/reactor/netty/http/server/ConnectionInfo.java
src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java
src/main/java/reactor/netty/resources/PooledConnectionProvider.java
src/main/java/reactor/netty/tcp/TcpServerBind.java

Resolve some of the errorprone warning, including `ReferenceEquality`, `StringSplitter`, and suppress the `unchecked `, `rawtype `and `deprecation `warning.
There are still two type of warning unresolved, including `FunctionalInerfaceMethodChanged` and `FutureReturnValueIgnored`.Should I suppress them or resolve them?

resolve the errorprone warning.

---

build.gradle

Micrometer is an optional dependency, meaning that the exported version is only informative.
reactor-netty could technically work with any 1.2.x version, but support has ended.
NB: reactor-core will soon pin to 1.3.x as well, which is the LTS version, so one more reason to align on 1.3.0.

Pin Micrometer optional dep to 1.3.0 rather than latest.release

---

build.gradle
src/main/java/reactor/netty/resources/PooledConnectionProvider.java

Adapt to a change in Netty connection pool
https://github.com/netty/netty/issues/9542

Update Netty version to 4.1.41.Final

---

src/main/java/reactor/netty/ByteBufFlux.java
src/main/java/reactor/netty/channel/FluxReceive.java
src/test/java/reactor/netty/http/client/HttpClientTest.java

Fixed memory leak when `timeout` occurs.
Related to #876

Fixed memory leak in ByteBufFlux#aggregate

---

src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/UriEndpointFactory.java
src/test/java/reactor/netty/http/client/HttpRedirectTest.java

Hello,
We're using reactor-netty in our application through Spring WebClient to download various content from the internet. There are some sites that do not have HTTPS support, so we need to download their content on plain HTTP. Unfortunately the current implementation of redirect causes all relative redirects to be routed to the HTTPS version of the site, which makes it impossible to download from  the site if it has no support of HTTPS, but on the other hand makes relative redirects.

Add keeping of scheme on relative redirection of http requests

---

build.gradle

- the `Import-Package` clause was missing an entry
`io.netty.util.internal;version="[ 4.1,5)"`
- the `Bundle-SymbolicName` clause was changed to project name instead
of a more fully qualified name

fix #920 OSGI: explicit SymbolicName and fix imports-exports

---

build.gradle
src/jarFileTest/java/reactor/netty/AbstractJarFileTest.java
src/jarFileTest/java/reactor/netty/JarFileShadingTest.java

The bnd plugin only applies to the default `jar` task. Since we're now
using the shadow plugin, `shadowJar` has no OSGI data in its MANIFEST.
This commit fixes the situation by applying the bnd plugin convention to
the shadowJar task. It also copies the bnd configuration since this is
not inherited.

fix #913 Apply BND convention to shadowJar as well

---

src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConfiguration.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientOperations.java
src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
src/test/java/reactor/netty/http/client/WebsocketTest.java

Fix for the situation in https://github.com/spring-cloud/spring-cloud-gateway/issues/729 where Spring Cloud Gateway responds to ping frames from a websocket server instead of proxying them to the client. I used the project from that issue to verify the functionality.
Please see the following commits in spring-framework and spring-cloud-gateway that will make this configurable by a new `spring.cloud.gateway.httpclient.websocket.proxy-ping` property:
https://github.com/spring-projects/spring-framework/compare/master...JacobASeverson:proxy-ping
https://github.com/spring-cloud/spring-cloud-gateway/compare/master...JacobASeverson:issue-729

fix #663 Allow client to proxy ping frames instead of respond

---

src/main/java/reactor/netty/http/server/HttpServerOperations.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

Switching `auto-read` to `true` allows to detect disconnected client,
otherwise the disconnected client event will be detected on the next
attempt to read/write.

fix #940 Switch auto-read to true when LastHttpContent received on the server

---

src/main/java/reactor/netty/http/server/Http2StreamBridgeHandler.java

fix #965 Http2StreamFrameToHttpObjectCodec expects DefaultHttpContent when it does the encoding

---

src/main/java/reactor/netty/http/server/HttpServer.java
src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
src/main/java/reactor/netty/http/websocket/WebSocketSpec.java
src/main/java/reactor/netty/http/websocket/WebsocketSpecImpl.java
src/test/java/reactor/netty/http/client/WebsocketTest.java

fix #970 Separate HTTP and WebSocket compression configuration when on the server side.

---

src/main/java/reactor/netty/http/server/ConnectionInfo.java
src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

#976 
changes:
- Added splitting for "x-forwarded-proto" multiple values. 
- Added test codes.

fix #976 Support for "X-Forwarded-Proto" headers Multiple Values

---

src/test/java/reactor/netty/http/client/HttpRedirectTest.java

By default auto-redirect is not enable and it should NOT redirect.
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientOperations.java#L536
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/http/client/HttpClientOperations.java#L597
this backfills the test around this

Backfills passing test about redirect behavior

---

src/main/java/reactor/netty/resources/PooledConnectionProvider.java
src/test/java/reactor/netty/resources/PooledConnectionProviderTest.java

With every acquire the PooledRef object is changed while the channel is the same,
used the OWNER attribute in order to obtain the current PooledRef.

fix #1012 Ensure invalidate() is invoked on the correct PooledRef

---

src/test/java/reactor/netty/http/client/HttpRedirectTest.java

To complete https://github.com/spring-cloud/spring-cloud-sleuth/pull/1554, we need to allow visibility into implicit handling such as redirects or auto-retry on failure. This could be most easily accomplished on our side, if it uses the onXXX hooks. Alternatives could be evaluated as well.

Adds test showing implicit redirects are invisible to metrics/tracing

---

src/main/java/reactor/netty/http/client/HttpClientConnect.java

Thus connection state observers of RESPONSE_RECEIVED will be invoked before
HttpObserver and HttpIOHandlerObserver
Keep CONFIGURED and exception handling in HttpObserver in order to be able to
handle redirecting and retrying functionality.

Move RESPONSE_RECEIVED from HttpObserver to HttpIOHandlerObserver

---

src/main/java/reactor/netty/tcp/TcpClient.java
src/main/java/reactor/netty/tcp/TcpServer.java
src/main/java/reactor/netty/udp/UdpClient.java
src/main/java/reactor/netty/udp/UdpServer.java
src/test/java/reactor/netty/http/client/HttpClientTest.java

fix #1041 Ensure one and the same MicrometerChannelMetricsRecorder instance is used when enabling metrics

---

src/main/java/reactor/netty/tcp/TcpClient.java
src/main/java/reactor/netty/tcp/TcpServer.java
src/main/java/reactor/netty/udp/UdpClient.java
src/main/java/reactor/netty/udp/UdpServer.java

Motivation: `#doOnLifecycle` cannot be extended when a new `doOn*` method is introduced.

Deprecate server/client #doOnLifecycle method in favour of #doOn* methods

---

src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java
src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java

When MeterFilter.maximumAllowableTags configuration is available
on the system and the action onMaxReached is DENY, Micrometer will return
NoopMeter. Such meters will not be cached and thus OOM will be prevented.
Related to #1010

Do not cache NoopMeter

---

src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConfiguration.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java
src/main/java/reactor/netty/http/server/HttpServer.java
src/main/java/reactor/netty/http/server/HttpServerBind.java
src/main/java/reactor/netty/http/server/HttpServerConfiguration.java
src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java
src/test/java/reactor/netty/channel/AddressResolverGroupMetricsTest.java
src/test/java/reactor/netty/channel/ByteBufAllocatorMetricsTest.java
src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
src/test/java/reactor/netty/resources/PooledConnectionProviderMetricsTest.java

The new API is a variant of HttpServer/HttpClient#metrics(boolean) that also accepts
a function that receives the actual uri and returns the uri tag value
that will be used for the metrics with Metrics#URI tag.
Related to #1010

Add HttpServer/HttpClient#metrics(boolean, Function<String, String>)

---

src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/server/HttpServerBind.java
src/main/java/reactor/netty/resources/DefaultLoop.java
src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
src/main/java/reactor/netty/resources/DefaultLoopNIO.java
src/main/java/reactor/netty/resources/DefaultLoopNativeDetector.java
src/main/java/reactor/netty/resources/DefaultLoopResources.java
src/main/java/reactor/netty/resources/LoopResources.java
src/main/java/reactor/netty/tcp/TcpClientRunOn.java
src/main/java/reactor/netty/tcp/TcpResources.java
src/main/java/reactor/netty/tcp/TcpServerRunOn.java
src/main/java/reactor/netty/udp/UdpClientRunOn.java
src/main/java/reactor/netty/udp/UdpResources.java
src/main/java/reactor/netty/udp/UdpServerRunOn.java
src/test/java/reactor/netty/resources/DefaultLoopResourcesTest.java

In favour of LoopResources#onChannel(Class, EventLoopGroup)
This is in preparation for Unix Domain Sockets support
Fixes #453

fix #453 Deprecate LoopResources #onChannel/onServerChannel/onDatagramChannel

---

README.md
build.gradle
gradle.properties
gradle/releaser.gradle
src/docs/asciidoc/getting-started.adoc
src/jarFileTest/java/reactor/netty/JarFileShadingTest.java

This commit introduces the new versioning scheme, using -SNAPSHOT
instead of .BUILD-SNAPSHOT as the qualifier for snapshots.
The whole scheme is detailed in the reference documentation, same as
in core, and adaptations are made to the build script to accommodate it.
See reactor/reactor#683

[build] Officially use new versioning scheme for 1.0 Europium

---

src/main/java/reactor/netty/http/server/Http2StreamBridgeHandler.java

A test will be provided as part of `Http2 for HttpClient` implementation.

When HttpServer in H2 mode, release FullHttpRequest in case of failure

---

src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConfig.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientTcpConfig.java
src/main/java/reactor/netty/http/server/HttpServer.java
src/main/java/reactor/netty/http/server/HttpServerBind.java
src/main/java/reactor/netty/http/server/HttpServerConfig.java
src/main/java/reactor/netty/http/server/HttpServerTcpConfig.java
src/main/java/reactor/netty/tcp/TcpClient.java
src/main/java/reactor/netty/tcp/TcpServer.java
src/main/java/reactor/netty/transport/ClientTransportConfig.java
src/main/java/reactor/netty/transport/ServerTransport.java
src/main/java/reactor/netty/transport/ServerTransportConfig.java
src/main/java/reactor/netty/transport/Transport.java
src/main/java/reactor/netty/transport/TransportConfig.java
src/test/java/reactor/netty/http/client/HttpClientTest.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

Add deprecated `HttpServer/HttpClient#tcpConfiguration` and `HttpServer/HttpClient#from`
in order to keep the backwards compatibility.
The methods implementation invokes the corresponding `HttpServer`/`HttpClient` methods.

Add HttpServer/HttpClient#tcpConfiguration and HttpServer/HttpClient#from

---

build.gradle
src/main/java/reactor/netty/resources/DefaultLoop.java
src/main/java/reactor/netty/resources/DefaultLoopEpoll.java
src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
src/main/java/reactor/netty/resources/DefaultLoopNIO.java
src/main/java/reactor/netty/resources/LoopResources.java
src/main/java/reactor/netty/tcp/TcpResources.java
src/main/java/reactor/netty/udp/UdpResources.java

This can happen when EpollSocketChannel etc. is constructed.
Fixes #1152

fix #1152 Ensure newSocketStream() is not invoked when obtaining information for the channel class

---

src/main/java/reactor/netty/tcp/TcpClient.java
src/main/java/reactor/netty/tcp/TcpClientBootstrap.java
src/test/java/reactor/netty/tcp/TcpClientTests.java

Add deprecated TcpClient#bootstrap in order to keep the backwards compatibility.
The method implementation invokes the corresponding TcpClient methods.

Add TcpClient#bootstrap

---

src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientCookie.java
src/main/java/reactor/netty/http/client/HttpClientCookieWhen.java
src/main/java/reactor/netty/http/client/HttpClientDoOn.java
src/main/java/reactor/netty/http/client/HttpClientFinalizer.java
src/main/java/reactor/netty/http/client/HttpClientHeaders.java
src/main/java/reactor/netty/http/client/HttpClientHeadersWhen.java
src/main/java/reactor/netty/http/client/HttpClientObserve.java
src/main/java/reactor/netty/http/client/HttpResponseDecoderSpec.java
src/main/java/reactor/netty/http/client/WebsocketFinalizer.java
src/main/java/reactor/netty/http/server/HttpRequestDecoderSpec.java
src/main/java/reactor/netty/http/server/HttpServer.java
src/main/java/reactor/netty/http/server/HttpServerBind.java
src/main/java/reactor/netty/http/server/HttpServerHandle.java
src/main/java/reactor/netty/http/server/HttpServerObserve.java
src/main/java/reactor/netty/tcp/TcpClient.java
src/main/java/reactor/netty/tcp/TcpServer.java
src/main/java/reactor/netty/udp/UdpClient.java
src/main/java/reactor/netty/udp/UdpServer.java
src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
src/test/java/reactor/netty/resources/PooledConnectionProviderTest.java

- options, attributes can be added with `#attr`, `#selectorAttr`, `#option` and `#selectorOption`
- local address can be added with `#bindAddress`
- group can be added with `#runOn`
- remoteAddress can be added with `#remoteAddress`
- resolver can be added with `#resolver`

Deprecate #bootstrap in favour of methods exposed on client/server level

---

gradle/doc.gradle

reactor.netty.resources.NettyBlockHoundIntegration was removed when Netty started to provide
BlockHound integration

Remove exclusion for class that does not exist

---

src/main/java/reactor/netty/http/server/HttpServerOperations.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

fix #1180 Ensure that the custom status code phrase is preserved when creating a FullHttpResponse

---

src/main/java/reactor/netty/http/client/HttpClientOperations.java

With this change the request will be retried if for some reason the connection close event
appears after acquiring the connection from the pool and before sending the actual request.

Retry the request once if the connection was closed before sending the actual request

---

src/main/java/reactor/netty/http/client/HttpClientInfos.java
src/main/java/reactor/netty/http/client/HttpClientRequest.java
src/test/java/reactor/netty/http/client/HttpClientTest.java

All request settings are now available also from `HttpClientResponse`
Fixes #1031

fix #1031 Request headers are available from HttpClientRequest and HttpClientResponse

---

src/main/java/reactor/netty/channel/ChannelOperations.java
src/main/java/reactor/netty/resources/PooledConnectionProvider.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

fix #1165 Change the state after notifying that the connection is acquired successfully.

---

src/main/java/reactor/netty/NettyPipeline.java
src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConfiguration.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientDoOnError.java
src/main/java/reactor/netty/http/client/HttpClientOperations.java
src/main/java/reactor/netty/http/client/HttpClientRequest.java
src/test/java/reactor/netty/http/client/HttpClientTest.java

ReadTimeoutHandler is added when request sending is finished successfully.
The handler is removed before returning the connection to the pool.
The setting on request level overrides the one on client level.
Fixes #1159

Fix #1159 Expose requestTimeout setting on HttpClient/HttpClientRequest level

---

reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java
reactor-netty-core/src/test/java/reactor/netty/transport/TransportTest.java
reactor-netty-core/src/test/resources/logback.xml

`ByteBufFormat` controls the format and verbosity of logging for `ByteBuf` and `ByteBufHolder`
Fixes #989

fix #989 Add wiretap(String, LogLevel, ByteBufFormat)

---

src/main/java/reactor/netty/NettyPipeline.java
src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConfiguration.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientDoOnError.java
src/main/java/reactor/netty/http/client/HttpClientOperations.java
src/main/java/reactor/netty/http/client/HttpClientRequest.java
src/test/java/reactor/netty/http/client/HttpClientTest.java

Rename HttpClientRequest#requestTimeout to HttpClientRequest#responseTimeout
Related to https://github.com/reactor/reactor-netty/issues/1159#issuecomment-667877218

Rename HttpClient#requestTimeout to HttpClient#responseTimeout

---

src/main/java/reactor/netty/tcp/TcpServerBind.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

Wait for the connections with active requests to finish for the given time and then close the connections
no matter if the requests finished successfully or are interrupted because of a timeout.
Fixes #1247

fix #1247 When graceful shutdown close immediately the connections with no active requests

---

reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java
reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java

A forward merge of the fix for #1257 (0.9.x) cannot be achieved because of
the changes in the implementation, so the fix for 1.0.0 is done separately.

fix #1257 Target host should not be resolved when proxy is configured (1.0.0)

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java

The headers on `HttpClient` level are initialised when the `HttpClient` configuration
is created, no need to initialise it when preparing the request.
`ACCEPT_ENCODING` header is properly set when the compression is enabled,
no need to set it when preparing the request.

fix #1274 Fix NPE when executing parallel requests

---

src/main/java/reactor/netty/http/client/HttpClient.java
src/main/java/reactor/netty/http/client/HttpClientConfiguration.java
src/main/java/reactor/netty/http/client/HttpClientConnect.java
src/main/java/reactor/netty/http/client/HttpClientOperations.java

With `BiConsumer` Reactor Netty provides the headers from the previous
request and the current redirect request.
Fixes #1265

fix #1265 Expose a variant of HttpClient#followRedirect with BiConsumer

---

src/main/java/reactor/netty/channel/FluxReceive.java
src/main/java/reactor/netty/http/server/HttpServerOperations.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

Ensure the buffered data is discarded on response complete when the connection
is marked as non persistent, this includes also errors returned by the Publisher.
Fixes #1286

fix #1286 Ensure the buffered data is discarded on response complete

---

src/main/java/reactor/netty/resources/ConnectionProvider.java
src/main/java/reactor/netty/resources/PooledConnectionProvider.java
src/test/java/reactor/netty/http/client/HttpClientTest.java

By default the background eviction is disabled.

Expose an API for enabling the connection pool background eviction

---

src/main/java/reactor/netty/http/server/HttpServerOperations.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

fix #1333: When HEAD request, remove Transfer-Encoding only if there is Content-Length

---

reactor-netty-core/src/main/java/reactor/netty/ByteBufFlux.java
reactor-netty-core/src/main/java/reactor/netty/ByteBufMono.java
reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
reactor-netty-core/src/test/java/reactor/netty/ByteBufFluxTest.java
reactor-netty-core/src/test/java/reactor/netty/ByteBufMonoTest.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java

This is the same as ByteBufFlux#fromString except it returns Mono and not Flux
If the provided source has more than one element, a reduction will be used
as the resulting Publisher should be Mono.

Add new API ByteBufMono#fromString

---

.github/dependabot.yml
build.gradle
reactor-netty-core/build.gradle

There is no need to add manually to the maven publications the artifact produced by shadowJar.
This is related to a change between version 5.2.0->6.0.0
https://github.com/johnrengelman/shadow/issues/586

Artifact produced by shadowJar is published automatically to local maven repository

---

src/main/java/reactor/netty/channel/FluxReceive.java

This is a quick fix for the regression introduced with #1185
Related to #1370 and #1350

Guarantee there is no race between subscribe and other operations invoked in an event loop

---

src/main/java/reactor/netty/NettyPipeline.java
src/main/java/reactor/netty/http/server/HttpServer.java
src/main/java/reactor/netty/http/server/HttpServerBind.java
src/main/java/reactor/netty/http/server/HttpServerConfiguration.java
src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
src/test/java/reactor/netty/http/server/HttpServerTests.java

An API for specifying an idle timeout on the connection when it is waiting for an HTTP request.

fix #1345 Add API HttpServer#idleTimeout (for Reactor Netty version 0.9.x)

---

reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

An API for specifying an idle timeout on the connection when it is waiting for an HTTP request.

fix #1345 Add API HttpServer#idleTimeout (for Reactor Netty version 1.0.x)

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNativeDetector.java

Reactor Netty has compile dependency on `netty-transport-native-epoll`
and an optional dependency on `netty-transport-native-kqueue`.

When searching for native transport, try first to load epoll

---

build.gradle
reactor-netty-core/build.gradle
reactor-netty-core/src/jarFileTest/java/reactor/netty/JarFileShadingTest.java
reactor-netty-http-brave/build.gradle
reactor-netty-http/build.gradle

Fixes #1392 
Based on functionality in version `0.9.x`
https://github.com/reactor/reactor-netty/blob/03c22c8fe0c29a204de298f0c16b852d9c7d223a/build.gradle#L90-L95
<details>
<summary>MANIFEST.MF for reactor-netty-core</summary>
```mf
Manifest-Version: 1.0
Automatic-Module-Name: reactor.netty.core
Bnd-LastModified: 1606798238098
Bundle-ManifestVersion: 2
Bundle-Name: reactor-netty-core
Bundle-SymbolicName: io.projectreactor.netty.reactor-netty-core
Bundle-Version: 1.0.2.BUILD-202012010450
Created-By: 1.8.0_261 (Oracle Corporation)
Export-Package: reactor.netty;version="1.0.2.BUILD-202012010450";uses:
="io.micrometer.core.instrument,io.netty.buffer,io.netty.channel,io.n
etty.util.concurrent,org.reactivestreams,reactor.core,reactor.core.pu …
```

fix #1392 Reintroduce OSGi and adapt OSGi Bundle-Version to new Europium scheme

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java

Fixes #1394 
In case of HTTP/1.1
- if the scheme is HTTPS and there IS NO security provider specified -> the default one is used
- if the scheme is HTTP and there IS security provider specified -> the security provider is removed
In case of HTTP/2
- if the scheme is HTTPS and the specified protocol is H2C -> the protocol will be replaced with H2.
The security provider will be configured AFTER the protocol so that Reactor Netty can choose the correct
default security provider based on the protocol.
- if the scheme is HTTP and the specified protocol is H2 -> the protocol will be replaced with H2C.
The specified security provider is removed.

fix #1394 Ensure the correct protocol (H2C/H2) is applied in case SslHandler is applied based on the http/https scheme

---

reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

According to the specification (below) the emitted WebSocketCloseStatus will be
WebSocketCloseStatus.ABNORMAL_CLOSURE, but the CloseWebSocketFrame
will be still created with status code "-1" as 1006 cannot be set as a status code for
CloseWebSocketFrame.
"1006 is a reserved value and MUST NOT be set as a status code in a
Close control frame by an endpoint.  It is designated for use in
applications expecting a status code to indicate that the
connection was closed abnormally, e.g., without sending or
receiving a Close control frame."
Fixes #1406

fix #1406 When connection is closed abnormally, emit WebSocketCloseStatus.ABNORMAL_CLOSURE

---

build.gradle
reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopIOUring.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNativeDetector.java
reactor-netty-http/build.gradle

This PR adds `netty-incubator-transport-native-io_uring` support which is still in the `incubator`.
https://netty.io/news/2020/11/16/io_uring-0-0-1-Final.html
Reactor Netty has only optional dependency to `netty-incubator-transport-native-io_uring` so that it can be built but does not bring `netty-incubator-transport-native-io_uring` as a transitive dependency.
Enabling `io_uring` transport:
- `io_uring` transport requires a dependency (the current version is `0.0.2.Final`)
```
<dependency>
<groupId>io.netty.incubator</groupId>
<artifactId>netty-incubator-transport-native-io_uring</artifactId>
<version>0.0.2.Final</version>
<classifier>linux-x86_64</classifier>
</dependency>
```
- Linux kernel version 5.9.0 (for more detail see the link above)
If the requirements above are met `io_uring` …

Add io_uring support

---

reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Extend the UDS test to check also the scheme.
Fixes #1434

fix #1434 When UDS, the scheme is determined by SslHandler availability in the pipeline

---

reactor-netty-core/build.gradle
reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java
reactor-netty-http/build.gradle

When running on `MacOS` and `MacOSDnsServerAddressStreamProvider`
is `NOT` available the log below with `WARN` log level will appear.
Related to https://github.com/netty/netty/pull/10848
11:55:45.619 [Test worker] WARN  i.n.r.d.DnsServerAddressStreamProviders -
Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider,
fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.
java.lang.ClassNotFoundException: io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at java.lang.Class.forName0(Native …

When running on MacOS use MacOSDnsServerAddressStreamProvider

---

docs/asciidoc/http-client.adoc
docs/asciidoc/http-server.adoc
docs/asciidoc/tcp-client.adoc
docs/asciidoc/tcp-server.adoc
docs/asciidoc/udp-client.adoc
docs/asciidoc/udp-server.adoc
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClient.java
reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java
reactor-netty-core/src/main/java/reactor/netty/transport/logging/AdvancedByteBufFormat.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/wiretap/custom/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/wiretap/custom/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/wiretap/custom/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/wiretap/custom/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/client/wiretap/custom/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/server/wiretap/custom/Application.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java

- Clarify `replacements for reactor.netty.tcp.TcpClient#bootstrap`
- Clarify `replacements for reactor.netty.http.client.HttpClient#from`
- Clarify `replacements for reactor.netty.http.client.HttpClient#tcpConfiguration`
- Clarify `replacements for reactor.netty.http.server.HttpServer#tcpConfiguration`
- Clarify `replacements for reactor.netty.http.server.HttpServer#from`
- Add a javadoc for
`reactor.netty.transport.logging.AdvancedByteBufFormat#SIMPLE`
`reactor.netty.transport.logging.AdvancedByteBufFormat#HEX_DUMP`
`reactor.netty.transport.logging.AdvancedByteBufFormat#TEXTUAL`
- Update the javadoc for various `reactor.netty.transport.Transport#wiretap` methods
- Update in the wire logging reference documentation
Fixes #1397

fix #1397 Update the javadoc and the reference documentation

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLog.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogFactory.java
reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogTest.java

Provides two factories methods into `AccessLog` to allow filtering logs on predicate matching, with or without custom String format.

fix #1417 Add helpers for filtering the access log

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopResources.java

When extra event loop groups are created while initialising DefaultLoopResources
there is no need for quietPeriod and timeout as these extra event loop groups were
never used.

Shutdown immediately the extra event loop groups created when initialising DefaultLoopResources

---

build.gradle
src/main/java/reactor/netty/ReactorNetty.java
src/main/java/reactor/netty/resources/PooledConnectionProvider.java

`reactor.netty.pool.getPermitsSamplingRate` and
`reactor.netty.pool.returnPermitsSamplingRate` are exposed
in order to be able to enable Reactor Pool's `SamplingAllocationStrategy`

Add system properties for enabling SamplingAllocationStrategy

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java

The rest of the deprecated methods already mention the version when they will be removed.
https://projectreactor.io/docs/netty/snapshot/api/deprecated-list.html

Add the version when the deprecated method will be removed.

---

docs/asciidoc/http-client.adoc
docs/asciidoc/http-server.adoc
docs/asciidoc/tcp-client.adoc
docs/asciidoc/tcp-server.adoc
docs/asciidoc/udp-client.adoc
docs/asciidoc/udp-server.adoc
reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClient.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpServer.java
reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java
reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpServer.java
reactor-netty-core/src/test/java/reactor/netty/resources/DefaultLoopResourcesTest.java
reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/warmup/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/warmup/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/warmup/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/warmup/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/client/warmup/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/server/warmup/Application.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java

The warmup triggers an initialisation of the event loop groups, the host name resolver,
loads the necessary native libraries for the transport and native libraries
for the security if security is enabled.
Related to #560, #1023, #1425

Add warmup functionality for the servers/clients

---

src/main/java/reactor/netty/http/client/HttpClientDoOnError.java
src/test/java/reactor/netty/UrlExceptionTest.java

解决当获取url 是出现异常，无法获取正确的异常  
例如
httpClient
.request(HttpMethod.GET)
.uri(Mono.error(new IllegalArgumentException()))
.responseSingle((httpClientResponse, byteBufMono) -> {
HttpResponseStatus status = httpClientResponse.status();
if (status.code() != HttpStatus.OK.value()) {
throw new HttpServerErrorException(HttpStatus.valueOf(status.code()));
}
return byteBufMono.asString();
});
应该获取
IllegalArgumentException
结果获取到 NullPointerException

url java.lang.NullPointerException: null

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

There are use cases when the target server may want to reject the incoming
request immediately and to close the connection. Instead of scheduling
the first channel.read() when the request body is sent, the first channel.read()
will be scheduled once the HttpHeaders are sent.
Fixes #1478

fix #1478 Schedule the first channel.read() once the HttpHeaders are sent

---

reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

According to the specification the endpoint may echo the received Close frame,
and Reactor Netty echos the received Close frame:
https://tools.ietf.org/html/rfc6455#section-5.5.1
```
If an endpoint receives a Close frame and did not previously send a
Close frame, the endpoint MUST send a Close frame in response.  (When
sending a Close frame in response, the endpoint typically echos the
status code it received.)
```
However for the emitted Close status (the one that is used by the application),
if a status code is not defined or empty, the Close status should be considered 1005,
so Reactor Netty will emit 1005 instead of -1 with `WebsocketInbound#receiveCloseStatus`.
https://tools.ietf.org/html/rfc6455#section-7.1.5
```
If this Close control frame contains no status code, _The WebSocket …
```

fix #1485 When CloseWebSocketFrame with -1 status code (undefined/empty), emit WebSocketCloseStatus.EMPTY

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Reactor Netty always works with HTTP/1.1 abstraction. In order to be able to handle HTTP/2 traffic, special handlers are added to the pipeline, which convert from HTTP/2 <-> HTTP/1.1 when reading and writing. So when Reactor Netty returns `FullHttpResponse` this means that `endStream=true` will be added.

Ensure endStream=true when responding with 500 ISE when server in HTTP/2 mode

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSecure.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

Loading `HttpClientSecure` will trigger initialisation of the default `SslProvider`,
which in case of `H2C` is not necessary.

Do not load HttpClientSecure when the protocol is H2C

---

src/main/java/reactor/netty/ReactorNetty.java

When ReactorNetty is used in a multi-classloaders context, PERSISTENT_CHANNEL and CONNECTION attributeKey instantitation may throw an IllegalArgumentException. This fix test the existence of the AttributeKeys before creating them.

fix #1471 Test existence of an AttributeKey before creation

---

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Fixes #1512 
When the server is in `H2` mode, every channel created per stream is always closed.
With this change the terminate functionality is moved as a listener following
`LastHttpContent` instead of waiting for `channelInactive` event.

Ensure an error is propagated in case the client drops the connection

---

reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java

I addition to the error propagation add also a debug info with channel info
so that the logs can be correlated.

Add more debug info for inbound double subscription use case

---

reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java

- In case of memory leaks there will be a record whether
the buffer was provided to the receiver or not.
- Add a special logger so that when debugging memory leaks only
this logger can be enabled in order to have memory leak hints in place.

Add memory leak hint when the inbound message is provided to the receiver

---

build.gradle

Update `jacoco` version to `0.8.6`
`BlockHound` requires `-XX:+AllowRedefinitionToAddDeleteMethods` when java >= 13

Specify source and target java compatibility to 1.8

---

reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientConfig.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpResources.java
reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java
reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpClientConfig.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpResources.java
reactor-netty-core/src/test/java/reactor/netty/resources/DefaultLoopResourcesTest.java
reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
reactor-netty-core/src/test/java/reactor/netty/resources/PooledConnectionProviderCustomMetricsTest.java
reactor-netty-core/src/test/java/reactor/netty/tcp/BlockingConnectionTest.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java
reactor-netty-core/src/test/java/reactor/netty/udp/UdpClientTest.java
reactor-netty-http/src/main/java/reactor/netty/http/HttpResources.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

When there isn't a custom name resolver and the global LoopResources
are in use then all client transports will share one and the same name resolver.
Fixes #1515

Ensure client transports use one and the same name resolver when no custom configuration

---

gradle/javadoc.gradle

Since 1.0.0, the javadoc produced doesn't follow the same styling as reactor-core and 0.9.x javadocs due to the way the aggregation of individual modules javadocs is configured.
Notably, the CSS is different and links to javadocs of external classes (like JDK classes or `Flux`/`Mono`) don't appear.
This change fixes that.

Ensure "aggregateJavadoc" task configuration is the same as the "javadoc" task configuration

---

gradle.properties

The check for backwards compatibility should be against the previous release
and not GA. Some APIs are added after GA so we need to guarantee backwards
compatibility for these APIs also.

Check for backwards compatibility against the previous release

---

reactor-netty-core/src/main/java/reactor/netty/transport/AddressUtils.java
reactor-netty-core/src/test/java/reactor/netty/transport/AddressUtilsTest.java
reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

```
Forwarded: by=<identifier>;for=<identifier>;host=<host>;proto=<http|https>
<identifier>
an IP address (v4 or v6, optionally with a port, and ipv6 quoted and enclosed in square brackets)
```

Ensure Forwarded header is parsed according to the specification

---

.github/workflows/check_transport.yml
.github/workflows/publish.yml
gradle/releaser.gradle
gradle/setup.gradle

This commit changes the release process to be based on GitHub Actions.
CI is already performed on GHA, but that workflow will now only run
for pull_request trigger.
We define helper tasks and methods in the setup.gradle file to help
interpret the version number. The trigger is pushing a commit to an
active maintenance branch.
The new workflow uses GitHub Environments to manage access to secrets,
especially in the case of milestones and releases as it introduces
signing of artifacts in these cases. It is split into 4 jobs, 3 of
which are conditional and depend on a GitHub Environment.
Notably:
- Add a function to qualify a version number as one of RELEASE,
MILESTONE, SNAPSHOT or BAD
- Add a GitHub Actions oriented task, `qualifyVersionGha`, which
produces gha step output for the current …

GitHub Actions Release Process: signing, artifactory, sonatype

---

reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
reactor-netty-core/src/test/java/reactor/netty/transport/ProxyProviderTest.java

Throw IAE in case neither address nor host is specified for the proxy

---

.github/workflows/check_transport.yml
.github/workflows/publish.yml

Sporadic failures are observed on GitHub Actions when running on Ubuntu 20.04/18.04
Related to https://github.com/actions/virtual-environments/issues/3185

Add workaround for "ConnectTimeoutException: connection timed out" on GitHub Actions

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java

update annotation of HttpClient.ResponseReceiver.response() method

---

reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java

Print in the logs SSLEngine instance in use and not only the name of the class.

Print in the logs SSLEngine instance in use

---

reactor-netty-http/src/main/java/reactor/netty/http/client/FailedHttpClientRequest.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientRequest.java

The `#responseTimeout` Javadoc and Netty's [`ReadTimeoutHandler` Javadoc](https://netty.io/4.0/api/io/netty/handler/timeout/ReadTimeoutHandler.html) don't seem to match.
> Raises a `ReadTimeoutException` when no data was read within a certain period of time.
This PR tries to clarify the response timeout configuration.
Also, does it make sense to introduce `#readTimeout` and deprecate these methods as their name is misleading?

Rephrase `responseTimeout` Javadoc

---

src/main/java/reactor/netty/http/client/HttpClientConnect.java

- When `Connection reset by peer` is observed mark the connection as non-persistent,
do not wait for the channel close event to invalidate the connection.
Fixes #1622

When "Connection reset by peer" is observed mark the connection as non-persistent

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpResponseDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpRequestDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpDecoderSpecTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

API for configuring whether or not to allow duplicate `Content-Length` headers with the same value.
By default this is not allowed and such messages are rejected.
When this is configured to allow duplicate `Content-Length` headers, they have to have the same value,
otherwise such messages are rejected. The duplicated `Content-Length` headers are replaced
with a single valid `Content-Length` header.
Fixes #1636

Add HttpDecoderSpec#allowDuplicateContentLengths(boolean)

---

reactor-netty-http/src/main/java/reactor/netty/http/server/logging/BaseAccessLogHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/logging/BaseAccessLogHandlerTests.java

- Common log format must contain the IP address of the client (remote host)
which made the request to the server.
- Response duration must be without "ms".

Access log must contain only the remote IP without a port

---

docs/asciidoc/tcp-client.adoc
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/read/connection/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/send/connection/Application.java

Example with `Connection#outbound` and `Connection#inbound` as an alternative of I/O handler.
Fixes #532

Add an example for long-living TCP client connection

---

reactor-netty-core/build.gradle

The shadow jar is published under `reactor.netty.internal.shaded.reactor.pool` in reactor-netty-core and filtered in `Export-Package`.
To be used in reactor-netty-http it should not be filtered.
Fixes https://github.com/reactor/reactor-netty/issues/1650

fix #1650 reactor.netty.internal is no longer exclude from MANIFEST

---

reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
reactor-netty-core/src/test/java/reactor/netty/ConnectionTest.java

In case of Reactor Netty <-> Brave integration, the first Reactor Netty RIGHT handler
is not `ReactiveBridge`, but the handler that populates the `TraceContext` so that the
custom Netty handlers can obtain it.

Ensure addHandlerLast adds the handler before the first Reactor Netty RIGHT handler

---

reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsRecorder.java
reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpMetricsTests.java
reactor-netty-core/src/test/java/reactor/netty/udp/UdpMetricsTests.java
reactor-netty-http/src/main/java/reactor/netty/http/ContextAwareHttpMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/ContextAwareHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/ContextAwareHttpClientMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

New abstract classes are exposed so that the custom metrics recorder
can access the ContextView associated with the Mono/Flux
- ContextAwareChannelMetricsRecorder
- ContextAwareHttpClientMetricsRecorder
- ContextAwareHttpServerMetricsRecorder
Fixes #1628

Add API for ContextView aware metrics recorder

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

When a handler is added to the pipeline (`Connection#addHandler`) with `doOnChannelInit` callback
it must stay until channel close. This means that in case the `Connection` is `PooledConnection`,
the `PooledConnection` must be bound after channel init invocation.
Every handler added with `Connection#addHandler` is removed on `onTerminate` event.
In case of `PooledConnection`, `onTerminate` event is channel released to the pool,
this leads to a handler removed from the pipeline on channel release to the pool,
which is not expected for a handler added with `doOnChannelInit` callback.
This is related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1690#issuecomment-854416606
The handlers for Reactor Netty <-> Brave integration are added with with `doOnChannelInit` callback

Handlers added on channel init must stay until channel close

---

reactor-netty-http/src/main/java/reactor/netty/http/Cookies.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerInfos.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRequest.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerResponse.java
reactor-netty-http/src/main/java/reactor/netty/http/server/ServerCookies.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpCookieHandlingTests.java

https://datatracker.ietf.org/doc/html/rfc6265#section-4.2.2
Although cookies are serialized linearly in the `Cookie` header,
servers SHOULD NOT rely upon the serialization order.  In particular,
if the `Cookie` header contains two cookies with the same name (e.g.,
that were set with different `Path` or `Domain` attributes), servers
SHOULD NOT rely upon the order in which these cookies appear in the
header.
Fixes #1641

Expose an API for obtaining all cookies with one and the same name

---

reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpServerRoutes.java
reactor-netty-http/src/test/java/reactor/netty/http/server/DefaultHttpServerRoutesTest.java

Original issue: #1665 
This PR fixes the `StringIndexOutOfBoundsException` by checking the length of the string before accessing char 0

Issue-1665: StringIndexOutOfBoundsException when using directory route

---

reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpServerRoutes.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpCookieHandlingTests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/DefaultHttpServerRoutesTest.java

Original issue: #1668
This PR fixes the ChannelBindException detection by using a non i18n part of the exception message

Issue-1668: ChannelBindException detection fails

---

reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

Original issue: #1673
This PR fixes the failed test cases on env language != en

Issue-1673: Use non language specific test conditions

---

reactor-netty-core/src/main/java/reactor/netty/FutureMono.java
reactor-netty-core/src/test/java/reactor/netty/FutureMonoTest.java

closes #1684 
Signed-off-by: Oleh Dokuka <odokuka@vmware.com>
Signed-off-by: Oleh Dokuka <oleh.dokuka@icloud.com>

ensures no compete on onSubscribe and onComplete calls

---

docs/asciidoc/alloc-metrics.adoc

This metric was deprecated in 0.9.x with #1215 and
removed in 1.0.x with 0359c4fcf7f0bb85a01e5425af91ad7e415bb0fe
Fixes #1710

Remove reactor.netty.bytebuf.allocator.used.tiny.cache.size from the documentation

---

reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java
reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

Every name resolver keeps an opened channel that is used for the name resolution.
The name resolver should be shared when the `NameResolverProvider` and
the default `LoopResources` are the same, thus the opened channels will be kept to a minimum.
This is related to the Gitter discussion
https://gitter.im/reactor/reactor-netty?at=60ddeafb258ebf6d92fc9c50

Share the name resolver when the NameResolverProvider and the default LoopResources are the same

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRequest.java

Clarify that `HttpServerRequest` provides only the URI parameters captured via `{}`
Fixes #1716

Update javadoc for HttpServerRequest#params

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java

In case of `H2C`, `FullHttpRequest` is received.
When the `FullHttpRequest` has content with 0 readableBytes, the content is released immediately.
Ensure `SimpleCompressionHandler#decode` can handle `FullHttpRequest` with freed content,
this can happen in cases when the response is delayed.
Related to https://github.com/spring-projects/spring-boot/issues/27176

Ensure SimpleCompressionHandler#decode can handle FullHttpRequest with freed content

---

reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java
reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java

This will guarantee the channel hash is calculated correctly as there are cases
when the metrics recorder supplier returns always different instances of the metrics recorder.
Fixes #1707

Obtain the metrics resolver on the configuration step when the metrics are enabled

---

reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientSecure.java

In some cases,  a 'null' is returned while calling 'SslProvider.defaultClientProvider()' and this is causing a problem with [this LoC ](https://github.com/reactor/reactor-netty/blob/v1.0.3/reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSecure.java#L97)where it expects not null for SslProvider. This logging will help identify the cause of the problem in such cases.

Added logging for exception while creating default SSL provider

---

docs/asciidoc/udp-client.adoc
docs/asciidoc/udp-server.adoc
reactor-netty-core/src/main/java/reactor/netty/DisposableChannel.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopEpoll.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpClientConfig.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpConnection.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpOperations.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpServerConfig.java
reactor-netty-core/src/test/java/reactor/netty/udp/UdpClientTest.java
reactor-netty-core/src/test/java/reactor/netty/udp/UdpServerTests.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/client/uds/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/server/uds/Application.java

Add support for Unix domain datagram sockets when using native epoll/kqueue transport

---

reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java

Obtain the remote address from the `ChannelHandlerContext` while in the `write` method and not in the callback.
Fixes #1766

Fix NPE when reporting metrics to Micrometer

---

reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpServerRoutes.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpPredicate.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpRouteHandlerMetadata.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRoutes.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

In current version,reactor netty hasn't really concept about ‘route’,we can't define route directly use code.In reactory netty,`HttpRouteHandler` is the route,when one request come in,we iterate `HttpRouteHandler` list to find one `HttpRouteHandler` can handle income request,if no `HttpRouteHandler` can handle request return http status code 404(mean no route). In the iterate process we use `Predicate<? super HttpServerRequest>` to match request one by one,when `Predicate<? super HttpServerRequest>` return true,it means there is one route for this request,so i think in reactory netty `Predicate<? super HttpServerRequest>` is  the "route".

#1669  for discussion only

---

reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

The pool and the metrics are one and the same object.
The implementation already keeps all pools in a ConcurrentMap.
Add test to keep track that the pool and the metrics are the same object.
Fixes #1790

Remove WeakHashMap cache

---

docs/asciidoc/http-server.adoc
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/multipart/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/multipart/custom/Application.java
reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerFormDecoderProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRequest.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/CustomBlockHoundIntegration.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerFormDecoderProviderTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerPostFormTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
reactor-netty-http/src/test/resources/largeFile1.txt

When the request is `POST` and have `Content-Type` with value
`application/x-www-form-urlencoded` or `multipart/form-data`,
the API returns a `Flux<HttpData>` containing received form/multipart data.
Fixes #3, #1351

Add API HttpServerRequest#receiveForm()

---

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

HTTP/2 pool owner is stored in the connection and not in the individual stream.

Ensure HTTP/2 pool owner is taken from the connection and not from the stream

---

reactor-netty-core/src/main/java/reactor/netty/resources/MicrometerPooledConnectionProviderMeterRegistrar.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java

MicrometerPooledConnectionProviderMeterRegistrar does not implement
ConnectionProvider.MeterRegistrar as we want to work directly with the pool
otherwise we need to keep another map with weak references which is not acceptable
Additional change for #1797

MicrometerPooledConnectionProviderMeterRegistrar works directly with the pool

---

docs/asciidoc/http-client.adoc
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/channeloptions/Application.java

These socket options are available with Java 11

[documentation] Add an example with ExtendedSocketOptions.TCP_KEEP* options for NIO transport

---

docs/asciidoc/http-client.adoc
docs/asciidoc/tcp-client.adoc
reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java
reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java

Add API for configuring a custom HostsFileEntriesResolver

---

build.gradle
gradle/asciidoc.gradle
gradle/setup.gradle
gradle/wrapper/gradle-wrapper.properties
reactor-netty-core/build.gradle
reactor-netty-examples/build.gradle
reactor-netty-http-brave/build.gradle
reactor-netty-http/build.gradle
reactor-netty-incubator-quic/build.gradle
reactor-netty/build.gradle

This PR is separated on several commits in order to make the review process easier.
These commits are done in one and the same PR as otherwise the build cannot pass and all of them address the migration to Gradle 7.
1. Update Gradle to 7.2.
2. Remove the optional dependencies in the generated pom.xml.
- There is no version of `org.springframework.build.gradle:propdeps-plugin` for Gradle 7.
The plugin is removed and Reactor Netty does not list anymore the optional dependencies in the generated pom.xml.
- All modules are now `java-library`.
- All dependencies with `compile` are moved to `api`, those with `optional` - `compileOnly`, `testCompile` - `testImplementation` and `testRuntime` - `testRuntimeOnly`.
3. Remove the usage of the Gradle deprecated functionality.
4. Update Asciidoctor to …

Upgrade to Gradle 7

---

build.gradle
reactor-netty-core/build.gradle
reactor-netty-http/build.gradle
reactor-netty-incubator-quic/build.gradle

This is needed for generating `SelfSignedCertificate` on Java version >= 15

Add testRuntimeOnly dependency to org.bouncycastle:bcpkix-jdk15on

---

reactor-netty-http/src/main/java/reactor/netty/http/websocket/WebsocketInbound.java
reactor-netty-http/src/main/java/reactor/netty/http/websocket/WebsocketOutbound.java

Clarify in javadoc that some status codes must not be used as such in websocket close frame

---

docs/asciidoc/conn-provider-metrics.adoc
reactor-netty-core/src/main/java/reactor/netty/Metrics.java
reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionPoolMetrics.java
reactor-netty-core/src/main/java/reactor/netty/resources/DelegatingConnectionPoolMetrics.java
reactor-netty-core/src/main/java/reactor/netty/resources/MicrometerPooledConnectionProviderMeterRegistrar.java
reactor-netty-core/src/test/java/reactor/netty/resources/PooledConnectionProviderCustomMetricsTest.java
reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java

Please review this PR, which adds two methods in the ConnectionPoolMetrics interface:
The added methods (maxAllocatedSize, and maxPendingAcquireSize) simply expose the delegated methods from the original InstrumentedPool.PoolMetrics. This will most likely resolve the #1872 issue.

#1872: Implement additional metrics from reactor-pool

---

reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
reactor-netty-core/src/test/java/reactor/netty/transport/ProxyProviderTest.java

Properly transform http.nonProxyHosts into regex pattern in ProxyProvider

---

reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpResources.java
reactor-netty-core/src/test/java/reactor/netty/resources/ConnectionProviderTest.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Resources.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpConnectionProvider.java

HTTP/2 connection pool inherits the configuration from its parent pool.
HTTP/2 connection pool name is a combination of `http2` and the parent pool's name.
Fixes #1800

Introduce functionality for mutating the ConnectionProvider configuration

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java

This functionality is needed for HTTP/2 connection pool

Move DefaultPooledConnectionProvider#poolFactoryPerRemoteHost and #maxConnections to PooledConnectionProvider

---

docs/asciidoc/http-client.adoc
docs/asciidoc/tcp-client.adoc
reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java

Allow to config dns bind address in NameResolverSpec
FIx [1920](https://github.com/reactor/reactor-netty/issues/1920)

config dns bind address in NameResolverSpec

---

reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpConnectionProvider.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

The connection is removed from the pool when:
- The connection is closed.
- The connection has reached its life time and there are no active streams.
- The connection has no active streams.
- When the client is in one of the two modes: 1) `H2` and `HTTP/1.1` or 2) `H2C` and `HTTP/1.1`,
and the negotiated protocol is `HTTP/1.1`.
The connection is filtered out when:
- The connection has reached its life time and there are active streams. In this case, the connection stays
in the pool, but it is not used. Once there are no active streams, the connection is removed from the pool.
- The connection has reached its max active streams configuration. In this case, the connection stays
in the pool, but it is not used. Once the number of the active streams is below max active streams configuration, …

New HTTP/2 connection pool implementation

---

docs/asciidoc/eventloop-metrics.adoc
docs/asciidoc/http-client.adoc
docs/asciidoc/http-server.adoc
docs/asciidoc/tcp-client.adoc
docs/asciidoc/tcp-server.adoc
docs/asciidoc/udp-client.adoc
docs/asciidoc/udp-server.adoc
reactor-netty-core/src/main/java/reactor/netty/Metrics.java
reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerEventLoopMeterRegistrar.java
reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
reactor-netty-core/src/test/java/reactor/netty/transport/TransportEventLoopMetricsTest.java

this PR adds a metric for the pending tasks scheduled in netty event loops.
Fixes #1398

Expose pending tasks of eventloops as metrics (#1398)

---

reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java

computeIfAbsent pessimistically locks instead of optimistically trying to return an existing entry.

Add a pre-screen before locking inside computeIfAbsent

---

.github/workflows/check_netty_snapshots.yml
.github/workflows/check_transport.yml
.github/workflows/publish.yml

According to
https://github.com/actions/setup-java#supported-distributions
```
NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore.
It is highly recommended to migrate workflows from adopt to temurin to keep receiving
software and security updates. See more details in the Good-bye AdoptOpenJDK post.
```

[build] Switch from `adopt` to `temurin` as used java distribution

---

reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java

Meter builders are mutable and not thread safe.

Do not cache Meter builders

---

reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java

Additional read operations are needed on the server and the client when websocket handshake
is performed, this is a result of behaviour change in Netty https://github.com/netty/netty/pull/11966

Additional read operation is needed when websocket handshake

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java

Prevent error when trying to add IdleTimeout when server setup with protocols HTTP/1.1 and HTTP/2 Clear-Text.
Fixes #1990

Prevent error when trying to add IdleTimeout

---

docs/asciidoc/http-client-conn-provider.adoc
docs/asciidoc/http-client.adoc
docs/asciidoc/tcp-client-conn-provider.adoc
docs/asciidoc/tcp-client.adoc
reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/pool/config/Application.java

Connection pool documentation is separated for TCP and HTTP.
Some configurations related to HTTP are not applicable in TCP use case.
Clarify that in the TCP use case the connections are never returned to the pool.
Related to
https://github.com/reactor/reactor-netty/issues/1937#issuecomment-995568920
https://github.com/reactor/reactor-netty/issues/532#issuecomment-1018614618

[doc] Separate connection pool documentation

---

reactor-netty-core/build.gradle
reactor-netty-http/build.gradle

When we release a version there is no need to keep this exclusions.
The backwards compatibility is checked always against the previous
version and not againts GA version.

Remove japicmp exclusions

---

.github/workflows/check_netty_snapshots.yml
.github/workflows/check_transport.yml
.github/workflows/codeql-analysis.yml
.github/workflows/publish.yml

This commit makes several modifications to our workflows to make them
more secure:
- explicitly have GITHUB_TOKEN read-only by default
- split tagging steps in their own jobs, limiting the scope of needed
write permission to these short-lived jobs

[build] Hardening of GitHub actions

---

reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Http2 streams close events are missed in case a full response is sent before having fully read the request.
Fixes #1978

Http2 streams not closed if request data is not fully consumed

---

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2StreamBridgeClientHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

Both `Http2FrameCodec` and `Http2MultiplexHandler` has to be available
in the pipeline when checking whether max active streams limit has been reached.
In case of `H2C` upgrade these handlers are added only on a successful upgrade.
Fixes #1982

Use the correct owner when invalidating the stream on close

---

reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
reactor-netty-http/src/test/java/reactor/netty/BaseHttpTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

This fix handles the use case when everything is received on the server and the response is delayed,
then additional read operation needs to be scheduled on writing `LastHttpContent`.
Extend the test to handle all compatible `H2` and `H2C` combinations.
Additional fix for #1978

Additional read operation needs to be scheduled on writing LastHttpContent

---

reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java

In Micrometer Recorders, use simple Object instead of MeterKey if it's possible.

Replace MeterKey by Object key

---

.github/workflows/check_transport.yml
reactor-netty-http-brave/build.gradle

This commit changes the `check_transport.yml` workflow so that it runs a
first job to check spotless and japicmp. The test matrix, which run longer,
depend on that first job succeeding.
We output a few tips to fix spotless failures and to indicate japicmp
failures need to be discussed with the maintainers, as pointers intended
for contributors.

Run spotless/japicmp as a preliminary job in ci

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java

This PR is an attempt to fix a concurrency issue where sometimes an event loop thread may handle almost all http client connections.
The issue may happen when a server is used as a proxy, where requests are forwarded to a remote server using web clients, and when many requests are received concurrently while the connection pool is empty. In this case, it can happen that many event loop threads have subscribed to the connection pool, but then one single event loop thread is used to publish almost all connections to client subscribers that are acquiring a connection from the pool. It's a kind of work/stealing issue.
The solution used consists in storing the client event loop in the connection pool subscriptions and reuse it when establishing the web client connection.
The issue is very hard …

Propagate the client thread in the ConnectionPool subscription context

---

gradle.properties

Reactor Netty QUIC version to 0.1.0-SNAPSHOT
Reactor BOM to 2022.0.0

Update Reactor Netty version to 1.1.0-SNAPSHOT

---

build.gradle
reactor-netty-core/build.gradle
reactor-netty-http-brave/build.gradle
reactor-netty-http/build.gradle
reactor-netty-incubator-quic/build.gradle
reactor-netty-incubator-quic/src/test/resources/logback.xml

Add `2022` to the files touched in `2022`.
Correct the wrong `2011-Present`.

Correct the start/end year in the copyright

---

build.gradle
docs/asciidoc/http-client.adoc
docs/asciidoc/tcp-client.adoc
docs/asciidoc/tcp-server.adoc
docs/asciidoc/udp-client.adoc
reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/Metrics.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java
reactor-netty-core/src/main/java/reactor/netty/channel/ConnectSpans.java
reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyHandlerContext.java
reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTracingObservationHandler.java
reactor-netty-core/src/main/java/reactor/netty/tcp/MicrometerSslReadHandler.java
reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java
reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeObservations.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeSpans.java
reactor-netty-core/src/main/java/reactor/netty/transport/AddressResolverGroupMetrics.java
reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionObservations.java
reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionSpans.java
reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

Connect, Hostname resolution and TLS handshake timers now are Observation
Co-authored-by: Marcin Grzejszczak <mgrzejszczak@vmware.com>
Note: Context propagation and Timers caches will be tracked in separate PRs

Update reactor-netty-core timers to use the new Observation

---

docs/asciidoc/http-client.adoc
docs/asciidoc/http-server.adoc
reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java
reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
reactor-netty-http/build.gradle
reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSpans.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyHttpClientTracingObservationHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyHttpServerTracingObservationHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerObservations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerSpans.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java

HttpClient/HttpServer response times now are Observation
Co-authored-by: Marcin Grzejszczak <mgrzejszczak@vmware.com>

Update reactor-netty-http timers to use the new Observation

---

.github/workflows/check_transport.yml

The message is intended as a hint on how to fix failing steps above it.
This commit makes itmore explicit, both in text and by the choice of
color coding.
Previously, the separate hints had some colored background, green and
orange respectively. This made it look like the japicmp step was the one
detected as failed, which was counterintuitive.
The message now explicitly tells the reader to look at the previous
steps in the job, and the colors have been changed to:
- drive focus to the whole message by having a header with orange bg
- highlight the individual calls to action with white font on black bg
- highlight the gradle command with black font on white bg

Improve readability of preliminary how-to-fix hint in CI

---

reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java

`HttpClientTracingObservationHandler`/`HttpServerTracingObservationHandler`
provides contextual name based on the request method
`io.micrometer.tracing.handler.HttpClientTracingObservationHandler#getSpanName`
`io.micrometer.tracing.handler.HttpServerTracingObservationHandler#getSpanName`

Do not override the contextual name for HttpClientContext/HttpServerContext

---

reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

Connection metrics for the client are provided with another name
and by the `ConnectionProvider`.

Ensure server connections metrics are not reported for the client

---

reactor-netty-core/src/main/java/reactor/netty/Connection.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/lifecycle/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/lifecycle/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/lifecycle/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/lifecycle/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/client/lifecycle/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/udp/server/lifecycle/Application.java
reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/test/java/reactor/netty/channel/ChannelOperationsHandlerTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

In Netty 5 there isn't separate `ChannelHandler` for inbound and outbound.
`Connection#addHandler(...)` can't make any more a decision whether to add
a handler as first or last. (as first are added handlers for outbound, as last - for inbound).

Deprecated Connection#addHandler(...)

---

reactor-netty-core/src/test/java/reactor/netty/ConnectionTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

This is in preparation for integration with Netty 5.
`ChannelDuplexHandler` and `ChannelInboundHandlerAdapter` are removed in Netty 5.

[tests] Switch to ChannelHandlerAdapter

---

reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java

This PR corrects a bad value for the TLS handshake duration time metric.
Before, the handshake start time was wrongly starting when the channel was registered, but the handshake start time must corresponds to the time just before the initial hanshake message is sent out by the netty SslHandler.
To correct the problem, we now register two handlers: 
- a tls metric handler which is registered just before the netty SslHandler. The start time of the handshake starts when the tls metric handler is activated (just before the ssl handler will send the initial handler)
- an ssl read handler, which is registered just after the netty SslHandler, which is used to just control reads, as before.

Wrong metric value for TLS handshake time

---

docs/asciidoc/http-client-conn-provider.adoc
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/pool/Application.java

Show that with one and the same `HttpClient` instance, one can
initiate many requests that always will use a new connection.
Related to comment https://github.com/reactor/reactor-netty/issues/1828#issuecomment-1060399563

[doc] Extend the example for disabling the connection pool

---

.github/workflows/check_transport.yml
reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/ContextAwareHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

Ensure Reactor Context is properly propagated on the client side when H2/H2C.

Enable HttpClient/HttpServer metrics when protocol is H2/H2C

---

reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

This is related to https://github.com/reactor/reactor-pool/pull/156

Ensure the Pool implementation for the test class implements the new abstract method config()

---

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java

The PR provides an enhancement for the Http2Pool in order to reduce  _ConcurrentLinkedDeque.size()_ method calls, which is not a constant time operation. 
Indeed, it has been observed that the CLDQ size method may consume around 18% of CPU when there is a high load of http client requests while all streams are currently unavailable.

Optimize Http2Pool by reducing calls to CLDQ size method

---

reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java

When a SOCKS proxy is used with a TcpClient, and when more than one message are sent **before** the tunnel is fully established with the SOCKS proxy, then the messages are buffered by the netty _ProxyHandler_ and won't be forwarded to the destination server after the tunnel is fully established.
This is because when you write multiple messages like for example this:
```
Connection connection = TcpClient.create().proxy(spec -> spec.type(ProxyProvider.Proxy.SOCKS5)... 
connection.outbound().sendString(Flux.just("Message1", "Message2", ...)
```
Then if the tunnel is not yet established, the netty ProxyHandler will buffer the messages using a reactor-netty _MonoSendMany.SendManyInner_ ChannelPromise, where some listeners will be added.
But, the problem is that the MonoSendMany.SendManyInner …

Ensure channel promises support listeners when SOCKS proxy handler is used

---

build.gradle

According to gradle doc - the default for `maxGranularity` is `-1` and this is `-1 denotes the highest granularity and corresponds to an atomic test`

[test] Remove maxGranularity in order to see parameterized tests failures

---

reactor-netty-http/src/test/java/reactor/netty/channel/ChannelOperationsHandlerTest.java

`HttpOperations#addHandler` adds extractor to the pipeline

[test] Use addHandler to add extractor to the pipeline

---

reactor-netty-core/src/main/java/reactor/netty/resources/ColocatedEventLoopGroup.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java

`EventLoopGroup.next()` should be called only in cases it will be used
for example establishing a connection.
`Pool.acquire(...)` in most cases will reuse the connections and in
these cases `EventLoopGroup.next()` invocation is not needed.

Ensure PooledConnectionProvider check only for event loop in the thread local

---

reactor-netty-http/build.gradle

Add `bouncycastle` dependency for `noMicrometer` tests similar to the standard tests.
This change is added for `1.0.x` because one may decide to build Reactor Netty with java version where one won't be able to create a `SelfSignedCertificate`

[tests] Add bouncycastle dependency

---

reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

`SocketException` with message `Connection reset` may be thrown
when running the tests with Java 17
This change is added for `1.0.x` because one may decide to build Reactor Netty with Java 17

[tests] Add SocketException to the list with possible exceptions

---

.github/workflows/check_netty_snapshots.yml
.github/workflows/check_transport.yml
.github/workflows/publish.yml
build.gradle

Reactor Netty integration with Netty 5 is based on Java 17
Netty 5 requires Java 11

Build with Java 17

---

build.gradle
gradle.properties
settings.gradle

The new integration will be handled with #2215

Temporary exclude reactor-netty-incubator-quic as there is no version for Netty 5

---

reactor-netty-http-brave/README.md
reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/ReactorNettyHttpTracing.java
reactor-netty-http-brave/src/test/java/reactor/netty/http/brave/ITTracingHttpClientDecoratorTest.java
reactor-netty-http-brave/src/test/java/reactor/netty/http/brave/ITTracingHttpServerDecoratorTest.java

An integration with `Micrometer Observation API` is provided as a replacement
for `Reactor Netty <-> Brave` integration

Deprecate reactor-netty-http-brave module

---

build.gradle
reactor-netty-core/build.gradle
reactor-netty-examples/build.gradle
reactor-netty-http/build.gradle
reactor-netty/build.gradle

- Add dependency to `Netty Contrib` (`codec-haproxy`, `codec-extras`, `socks-proxy`) `5.0.0.Final-SNAPSHOT`
- Add dependency to `netty-buffer:4.1.77.Final`
- Update artifactId to `netty5-*`

Update to Netty 5.0.0.Alpha2

---

reactor-netty-core/build.gradle
reactor-netty-http/build.gradle
reactor-netty/build.gradle

`*-native-*` is the artifact for the native code
`*-classes-*` is the artifact for the java code

Netty's native code is separated from the java code

---

reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

- There is no `VoidPromise` anymore so no need to handle this use case in `ProxyProvider`

Move from ChannelOutboundHandlerAdapter to ChannelHandlerAdapter

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpResponseDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpRequestDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpDecoderSpecTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpResponseDecoderSpecTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpRequestDecoderSpecTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Remove maxChunkSize as it was removed from HttpObjectDecoder

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpDecoderSpecTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

`Netty 5` does not support this configuration.

Deprecate HttpDecoderSpec#maxChunkSize

---

docs/asciidoc/faq.adoc

After upgrading spring versions in our stack we started to see `Connection prematurely closed BEFORE response`.
During investigation I found an introduction of max-keep-alive-requests property from Netty. I wanted to mention this as a point to check in the faq.
change: https://github.com/reactor/reactor-netty/pull/1867/files#diff-537f1e33d6e1428b0fcac7e1fe10ba87e6cc7aadc6f240fdb73fbe3103baae74R717
evaluation logic: https://github.com/reactor/reactor-netty/pull/1867/files#diff-d39ea30f5b5b199e58b3fb87763a4d3e303fcbd45e9c360565920c9b81bf950eR290
With default to unlimited.
change: https://github.com/spring-projects/spring-boot/commit/34b94d889826bc0d5075bface8420b79e932f0ad#diff-829ef53f73b35e9544921e277455052df073d15569867a2ee8be29daebf2a19fR388
- …

Update faq for connection closed BEFORE error

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientFormEncoder.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientWithTomcatTest.java

`HttpClient#sendForm` API uses `BiConsumer` and not `BiFunction`.
The user cannot change the encoder in the callback.
When a custom factory is provided, apply the changes when the control is again in Reactor Netty.
Fixes #2259

Ensure a custom factory can be used with HttpClient#sendForm

---

build.gradle
reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-core/src/test/java/reactor/netty/resources/ConnectionProviderTest.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java

This draft PR is an improvement to allow http client users to specify a hook function that can be used to configure a custom scheduler to schedule timers for pending connections acquisition.
By default, it's the **Schedulers.parallel** scheduler which is used, as before, but the intent is to let users to specify their own implementation for the timer service used by reactor-netty (timer scheduled for pending connections pool acquisition).
Example usage of a client that is configured with a netty hashed wheel timer service:
```
HashedWheelTimer timer = new HashedWheelTimer(10, TimeUnit.MILLISECONDS, 1024);
ConnectionProvider provider = ConnectionProvider
.builder(POOL_NAME)
.pendingAcquireTimeout(Duration.ofMillis(10000))
.pendingAcquireTimer((r, d) -> {
Timeout t = …
```

Allow to configure connection pool aquire timers

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoop.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopEpoll.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNIO.java
reactor-netty-core/src/main/java/reactor/netty/resources/LoopResources.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpResources.java
reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpClientConfig.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpResources.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpServerConfig.java

In Netty 5 we have now
```
/**
* Creates a new {@link Channel}.
*/
public interface ChannelFactory<T extends Channel> {
/**
* Creates a new channel.
*/
T newChannel(EventLoop eventLoop) throws Exception;
}
```
```
/**
* Creates a new {@link ServerChannel}.
*/
public interface ServerChannelFactory<T extends ServerChannel> {
/**
* Creates a new channel.
*/
T newChannel(EventLoop eventLoop, EventLoopGroup childEventLoopGroup) throws Exception;
}
```

Adapt to the new ChannelFactory/ServerChannelFactory

---

build.gradle
reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/BufferFlux.java
reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
reactor-netty-core/src/main/java/reactor/netty/channel/MonoSend.java
reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
reactor-netty-core/src/test/java/reactor/netty/channel/MonoSendManyTest.java
reactor-netty-examples/build.gradle
reactor-netty-http/build.gradle
reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/Http2ConnectionInfoTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpSendFileTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpsSendFileTests.java
reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
reactor-netty-http/src/test/java/reactor/netty/transport/ByteBufAllocatorMetricsTest.java

- `Resource`/`Send` are moved to `io.netty5.util`
- Temporary build with `natives` from `5.0.0.Alpha2`
- Temporary disable tests related to `file transfer` and `HTTP/2`

Update to Netty 5.0.0.Alpha3-SNAPSHOT

---

reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogHandlerH1Tests.java

`WebsocketTest#firefoxConnectionTest`
https://datatracker.ietf.org/doc/html/rfc6455#section-4.1
`The request MUST include a header field with the name Sec-WebSocket-Version.  The value of this header field MUST be 13.`
`The request MUST include a header field with the name Sec-WebSocket-Key.  The value of this header field MUST be a
nonce consisting of a randomly selected 16-byte value that has been base64-encoded (see Section 4 of [RFC4648]).
The nonce MUST be selected randomly for each connection.`

Tests need adaptation to work with Netty 5 changes and the new Buffer API

---

reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

When using netty5, the _HttpServerTests.testExpectErrorWhenConnectionClosed_ test does not pass anymore.
When it receives a request (using SSL), the test first closes the channel, then it sends a response and at this point it expects to get  an error (because the socket has been closed before sending the response):
```
.handle((req, res) -> {
// "FutureReturnValueIgnored" is suppressed deliberately
res.withConnection(conn -> conn.channel().close());
return res.sendString(Flux.just("OK").hide())
.then()
.doOnError(t -> {
error.set(t);
latch.countDown();
});
})
```
But in netty5, the above test does not work anymore. Notice that it works when **not** using SSL.
Analysis:
1. When closing the channel, the SslHandler sends a close-notify to the client and flushes [from SslHandler.java, line …

testExpectErrorWhenConnectionClosed test is broken when using SSL and netty5

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

The request termination happens also as a scheduled task in a listener, there is no ordering.

Ensure the next request is started once the previous is terminated

---

build.gradle
reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTimerObservationHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java
reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java

Fix exception when generating reference documentation.
```
Jun 22, 2022 10:52:13 AM io.micrometer.docs.metrics.MetricSearchingFileVisitor visitFile
SEVERE: Failed to parse file [/.../reactor-netty/reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java] due to an error
java.lang.IllegalStateException: There's no nested type with name [Http2ConnectionProviderMeters.Http2ConnectionProviderMetersTags]
at io.micrometer.docs.commons.ParsingUtils.lambda$keyValueEntries$1(ParsingUtils.java:79)
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at io.micrometer.docs.commons.ParsingUtils.lambda$keyValueEntries$2(ParsingUtils.java:78)
at java.base/java.util.Collections$SingletonList.forEach(Collections.java:4966)
at …
```

Switch to Micrometer 1.10.0-SNAPSHOT version

---

reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java

Add create method with name, maxConnections, metricsEnabled parameters.
Related to https://github.com/reactor/reactor-netty/issues/2313

Add create method with metrics parameter in ConnectionProvider (#2313)

---

reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerEventLoopMeterRegistrar.java
reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
reactor-netty-core/src/test/java/reactor/netty/transport/TransportEventLoopMetricsTest.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpTrafficHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

This change is adapting the code to the changes in Netty 5 snapshot.
Modifications:
- Remove the usage of syncUninterruptibly (https://github.com/netty/netty/pull/12481)
- Adapt to the changes in ChannelHandler: userEventTriggered(...) is renamed to inboundEventTriggered(...) (https://github.com/netty/netty/pull/12497)
- triggerOutboundEvent(...) is added (https://github.com/netty/netty/pull/12497)
- shutdown(...) and channelShutdown(...) are added (https://github.com/netty/netty/pull/12468)

Updates to latest netty5 changes: userEventTriggered/half close/sync

---

reactor-netty-examples/build.gradle
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/sse/Application.java

reactor-netty-examples does not need dependency to the old ByteBuf API

---

reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpTrafficHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Some of the `ChannelHandler`/`ChannelHandlerContext` methods names are changed with
https://github.com/netty/netty/pull/12505
- `fireExceptionCaught(...)` is now `fireChannelExceptionCaught(...)`
- `exceptionCaught(...)` is now `channelExceptionCaught(...)`
- `fireInboundEventTriggered(...)` is now `fireChannelInboundEvent(...)`
- `inboundEventTriggered(...)` is now  `channelInboundEvent(...)`

Adapt the code to the changes in the ChannelHandler/ChannelHandlerContext methods names

---

reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/transport/AddressResolverGroupMetrics.java
reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
reactor-netty-core/src/test/java/reactor/netty/resources/PooledConnectionProviderCustomMetricsTest.java
reactor-netty-core/src/test/java/reactor/netty/transport/TransportEventLoopMetricsTest.java
reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

Fixing issues described in #2187 by wrapping only metrics related code in try-catch and logging issues on warn level.

Issue 2187

---

.github/workflows/check_transport.yml
reactor-netty-http/src/test/java/reactor/netty/http/HttpTests.java

Enable `HttpTests#streamAndPoolDefaultCompression`

Remove the temporary workarounds in CI build

---

reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java

This was wrong migration see https://github.com/reactor/reactor-netty/pull/2299
`ByteBufMono -> BufferFlux`

Ensure BufferMono is used when full request is needed

---

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java

This PR is proposing an additional improvement for the original PR #2237.
While debugging another problem in _HttpMetricsHandlerTest_, I found that when the _AbstractHttpServerMetricsHandler.write_ method is getting an exception thrown by _recordWrite_, then the _recordInactiveConnection_ is never called, see [here](https://github.com/reactor/reactor-netty/blob/1.0.x/reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java#L114-L132).
So, this is too bad because the long adder that is incremented [from here](https://github.com/reactor/reactor-netty/blob/1.0.x/reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java#L158) is then never decremented by the missed call to _recordInactiveConnection_, resulting in …

Ensure active connections is decremented

---

reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java

This PR attempts to remove usage of Usafe (see netty PR from https://github.com/netty/netty/pull/12511).
Looking at the recent changes in the netty PR, it seems that calls like "channel.unsafe().closeForcibly()" are replaced by "channel.close();"
So, I simply did the same in this PR, but ... I'm not sure.
@violetagg , can you help on this please ?

Remove netty5 Unsafe class

---

build.gradle
gradle/javadoc.gradle
reactor-netty-core/build.gradle
reactor-netty-http/build.gradle
reactor-netty-incubator-quic/build.gradle

The exception below is thrown when Java version specified in the `PATH` is `> 8`
```
Unrecognized VM option 'AllowRedefinitionToAddDeleteMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized VM option 'AllowRedefinitionToAddDeleteMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Process 'Gradle Test Executor 159' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 159' finished with non-zero exit value 1
at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:414)
at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(Defau …
```

With Java toolchain in place AllowRedefinitionToAddDeleteMethods is not needed

---

build.gradle

With Reactive Streams 1.0.4 version there is
`javadoc: warning - Error fetching URL: https://www.reactive-streams.org/reactive-streams-1.0.4-javadoc/`

[doc ]Use Reactive Streams 1.0.3 version for javadoc generation

---

reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java

```
/.../reactor-netty/reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java:99:
warning: [unchecked] unchecked method invocation: method addLast in interface Deque is applied to given types
timerRecordingHandlers.addLast(defaultHandler);
^
required: E
found: ObservationHandler
where E is a type-variable:
E extends Object declared in interface Deque
/.../reactor-netty/reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java:99:
warning: [unchecked] unchecked conversion
timerRecordingHandlers.addLast(defaultHandler);
^
required: E
found:    ObservationHandler
where E is a type-variable:
E extends Object declared in interface Deque
```

[test] Fix warnings "unchecked method invocation"/"unchecked conversion"

---

.github/workflows/check_transport.yml
reactor-netty-core/src/test/java/reactor/netty/resources/DefaultLoopResourcesTest.java
reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
reactor-netty-core/src/test/java/reactor/netty/resources/PooledConnectionProviderCustomMetricsTest.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java
reactor-netty-core/src/test/java/reactor/netty/udp/UdpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

blocking JDK Future methods have moved to FutureCompletableStage interface: see https://github.com/netty/netty/pull/12548
The code needs to be adapted.
Also, we need to use temporary PR for netty-contrib/socks-proxy

Adapt to changes made in Future interface

---

reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

This PR is an attempt to sabilise the HttpMetricsHandlerTests, because now in netty5, channel listeners execution is rescheduled at the end of the current event loop queue, see Netty PR [#9489 Always notify FutureListener via the EventExecutor](https://github.com/netty/netty/pull/9489)
So, this is problem for the HttpMetricsHandlerTests tests, because when we receive a response from a server, we start to verify metrics, while the metrics may be not be already up-to-date because they are updated using channel listeners, which may not be executed yet at the time we receive a response.
See for example [AbstractHttpServerMetricsHandler.java](https://github.com/reactor/reactor-netty/blob/netty5/reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java#L122 …

Make HttpMetricsHandlerTests stable

---

docs/asciidoc/getting-started.adoc
docs/asciidoc/http-client-conn-provider.adoc
docs/asciidoc/http-client.adoc
docs/asciidoc/proxy.adoc
docs/asciidoc/wire-logger.adoc

Ensure the examples code is fully visible

[doc] Update Reactive Streams version in the reference documentation

---

.github/workflows/check_transport.yml

let's use socks-proxy from netty-contrib main branch, because the PR is now merged: https://github.com/netty-contrib/socks-proxy/pull/11

Use socks-proxy from main branch

---

gradle/errorprone.gradle
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

- Remove errorproneJavac specific for JDK 8
https://github.com/tbroyer/gradle-errorprone-plugin#jdk-8-support
- Suppress warning
```
/.../reactor-netty/reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java:942: warning: [UnnecessaryParentheses]
These grouping parentheses are unnecessary; it is unlikely the code will be misinterpreted without them
return switch (protocol) {
^
(see https://errorprone.info/bugpattern/UnnecessaryParentheses)
Did you mean 'return switch protocol {'?
```

Remove errorproneJavac specific for JDK 8

---

.github/workflows/check_transport.yml
reactor-netty-core/src/main/java/reactor/netty/BufferFlux.java
reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoop.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopEpoll.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNIO.java
reactor-netty-core/src/main/java/reactor/netty/resources/LoopResources.java

Adapt to the new EventLoop API for checking the channel compatibility

---

docs/asciidoc/http-client.adoc
docs/asciidoc/http-server.adoc
docs/asciidoc/tcp-client.adoc
docs/asciidoc/tcp-server.adoc
docs/asciidoc/udp-client.adoc
docs/asciidoc/udp-server.adoc

With 3 parallel versions of Reactor Netty (1.0.x, 1.1.x and 2.0.x), the reference documentation
has to point to the concrete version of Reactor Netty for each it is built

[doc] Javadoc link in reference documentation points to a concrete version

---

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMeters.java
reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java
reactor-netty-core/src/main/java/reactor/netty/channel/ConnectSpans.java
reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProviderMeters.java
reactor-netty-core/src/main/java/reactor/netty/resources/MicrometerPooledConnectionProviderMeterRegistrar.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeObservations.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeSpans.java
reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMeters.java
reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMetrics.java
reactor-netty-core/src/main/java/reactor/netty/transport/EventLoopMeters.java
reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionObservations.java
reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionSpans.java
reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerEventLoopMeterRegistrar.java
reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMeters.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSpans.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttp2ConnectionProviderMeterRegistrar.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerMeters.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerObservations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerSpans.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java

`KeyName.getKeyName` is renamed to `KeyName.asString`

Adapt to the changed API for Micrometer's KeyName

---

.github/workflows/check_netty_snapshots.yml
.github/workflows/check_transport.yml

GitHub Actions complain with:
```
The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead.
For more details see https://github.com/actions/virtual-environments/issues/5583
```

Bump MacOs image version to 11

---

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

According to the specification
https://www.rfc-editor.org/rfc/rfc9113.html#section-6.8
`Receivers of a GOAWAY frame MUST NOT open additional streams on the connection`
Reactor Netty by default is running with graceful shutdown which means that `GOAWAY`
might be received and the connection to be still alive.
`Http2Pool` should consider this use case and stop offering a connection that received `GOAWAY`.
Fixes #2396

Do not open a stream on a connection that received GOAWAY

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopEpoll.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopIOUring.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopKQueue.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNativeDetector.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HAProxyMessageReader.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java

In preparation for better GraalVM support

Use pattern for the field name when checking the classpath

---

reactor-netty5-core/src/main/java/reactor/netty5/transport/ClientTransport.java
reactor-netty5-core/src/main/java/reactor/netty5/transport/ProxyProvider.java
reactor-netty5-core/src/test/java/reactor/netty5/transport/ProxyProviderTest.java
reactor-netty5-http/build.gradle
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClient.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientProxyProvider.java
reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientProxyProviderTest.java

This is in preparation for removing `netty5-codec-http` dependency from `reactor-netty-core`.
This dependency is transitively available via `netty-handler-proxy` dependency.
Related to #1953

Introduce HttpClientProxyProvider with HTTP related configurations

---

docs/asciidoc/http-client.adoc
docs/asciidoc/http-server.adoc
docs/asciidoc/tcp-client.adoc
docs/asciidoc/tcp-server.adoc

`TCP`/`HTTP` are now supporting `UDS` for all transports - native and NIO.
Related to #2392

Update reference documentation for UDS support

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/IdleTimeoutHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java

Ensure `GOAWAY` is send in case of `HTTP/2`
https://www.rfc-editor.org/rfc/rfc9113.html#section-6.8
`The GOAWAY frame (type=0x07) is used to initiate shutdown of a connection`
Fixes #2412

Ensure HttpServer#idleTimeout configuration is applied for both HTTP/1.1 and HTTP/2

---

reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

This PR is a revamp of the HttpMetricsHandlerTests and also fixes a concurrency issue in testServerConnectionsRecorder, which sometimes fails with this exception:
```
HttpMetricsHandlerTests > testServerConnectionsRecorder(HttpProtocol[], HttpProtocol[], ProtocolSslContextSpec, ProtocolSslContextSpec, HttpProtocol) > reactor.netty.http.HttpMetricsHandlerTests.testServerConnectionsRecorder(HttpProtocol[], HttpProtocol[], ProtocolSslContextSpec, ProtocolSslContextSpec, HttpProtocol)[8] FAILED
java.lang.AssertionError: expectation "expectNext(Hello World!)" failed (expected: onNext(Hello World!); actual: onError(reactor.netty.http.client.PrematureCloseException: Connection prematurely closed DURING response))
at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
at …
```

Revise HttpMetricsHandlerTests and fix testServerConnectionsRecorder

---

reactor-netty5-core/src/test/java/reactor/netty5/ReactorNettyTest.java

`ChannelMetadata` is removed from the API
https://github.com/netty/netty/pull/12678

[test] Adapt to the changes in AbstractChannel

---

reactor-netty5-core/src/test/java/reactor/netty5/tcp/TcpServerTests.java

This PR adapts to the recent PR made in netty5: https://github.com/netty/netty/pull/12684
Modifications:
- The ChannelOption RCVBUFFER_ALLOCATOR has been renamed to READ_HANDLE_FACTORY 
- The AdaptiveRecvBufferAllocator class has been renamed to AdaptiveReadHandleFactory. 
Before, the AdaptiveRecvBufferAllocator was taking 3 parameters in the constructor:  int minimum, int initial, int maximum, and the old class was extending DefaultMaxMessagesRecvBufferAllocator which was using maxMessagesPerRead=1 by default.
Now, AdaptiveReadHandleFactory constructor now takes 4 parameters: int maxMessagesPerRead, int minimum, int initial, int maximum

Adapt to RecvBufferAllocator changes

---

reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java

There are no other `ChannelHandlers` in the pipeline except `ServerTransport.Acceptor`, thus
it is not needed to propagate the event.

ServerTransport.Acceptor#exceptionCaught should not propagate the event

---

build.gradle
reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
reactor-netty-core/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-core/reflect-config.json
reactor-netty-core/src/test/java/reactor/netty/NativeConfigTest.java
reactor-netty-http/build.gradle
reactor-netty-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-http/reflect-config.json
reactor-netty-http/src/test/java/reactor/netty/NativeConfigTest.java

When a `ChannelHandler` is added to the `Netty` channel pipeline and if the `ChannelHandler`
implements `ChannelInboundHandler`/`ChannelOutboundHandler`,
`io.netty.channel.ChannelHandlerMask#mask0` will inspect the `ChannelHandler's` methods for
`io.netty.channel.ChannelHandlerMask.Skip` annotation.
When there are no reflection hints, `NoSuchMethodException` is thrown when trying to query the methods with reflection.
This will lead to methods marked as not skippable, although the program will be able to run
without any problems, when all methods are marked as not skippable, one might observe performance issues.
Fixes #2419

Add reflection hints for better native-image support

---

reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

The HttpMetricsHandlerTests testServerConnectionsMicrometer is still unstable. 
Sometimes, the following assertion fails because the SERVER_CONNECTIONS_TOTAL is 1, [see this failing assertion](https://github.com/reactor/reactor-netty/blob/1.0.x/reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java#L626) 
Reproduced the problem in github using netty5 branch while validating the multipart porting draft PR.
What I can imagine is the following probable scenario:
1. the testServerConnectionsMicrometer is finishing an HTTP2 test, so the tearDown is in progress, and the client connection pool is disposing, but the server has not yet seen the close, so the SERVER_CONNECTIONS_TOTAL meter is still set to 1
2. now, the testServerConnectionsMicrometer starts a next test …

HttpMetricsHandlerTests testServerConnectionsMicrometer still unstable

---

reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

This PR fixes some tests which are not closing some ChannelGroups and their associated Executor.

Ensure ChannelGroup and associated Executor are closed

---

reactor-netty5-core/src/test/java/reactor/netty5/ReactorNettyTest.java

This PR adapts the ReactorNettyTest to the recent change made in Netty PR [12702](https://github.com/netty/netty/pull/12702), where the AbstractChannel.doWrite signature method has changed.
before, it was:
```
void doWrite(ChannelOutboundBuffer in) throws Exception;
```
now, it is:
```
void doWrite(ChannelOutboundBuffer in,  WriteHandleFactory.WriteHandle writeHandle) throws Exception;
```

Adapt ReactorNettyTest to Netty AbstractChannel change

---

reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java

[test] Use crafted Appender instead of mocking

---

reactor-netty5-core/build.gradle
reactor-netty5-http/build.gradle

Do not add io.netty:netty5-resolver-dns-native-macos:osx-x86_64 as required dependency

---

.github/workflows/check_transport.yml

The Netty contribs (codec-extras, codec-haproxy, socks-proxy) have been merged into their main branches with the following fixed PRs:
- Rename Statics to InternalBufferUtils (https://github.com/netty/netty/pull/12739)
- Remove Charset constants from CharsetUtil (https://github.com/netty/netty/pull/12741)
So, we can now point to the contribs main branches instead of their PR branches

Use Netty contribs from main branches

---

reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpConnectionProviderTest.java

Ensure HttpClientConfig#connectionProvider returns the original provider used to create HttpClient

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java

Set the trailing headers directly when constructing DefaultLastHttpContent

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java

If there is no subscription we may not need this object.

Defer the creation of the request/response object

---

reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogArgProviderH2Tests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogHandlerH2Tests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/logging/LoggingTests.java

Netty fixed the checks for HTTP/2 headers' compliance with RFC: https://github.com/netty/netty/pull/12760
This fixes the CI build against Netty 4.1 SNAPSHOT
https://github.com/reactor/reactor-netty/actions/runs/3106167960

[test] Ensure HTTP/2 tests comply with RFC requirements for HTTP/2 headers

---

.github/workflows/check_transport.yml
reactor-netty-core/build.gradle
reactor-netty-http-brave/build.gradle
reactor-netty-http/build.gradle

This commit improves the japicmp integration in the build:
1) Add a finalizedBy task that prints a filtered report
The basic text report uses * and ! as markers for binary and source
incompatible changes respectively. Additionally, a MODIFIED class is
marked with ***. This task attempts at pinpointing the incompatible
changes only in the report, and printing these lines.
This report is called out in the "how to fix" tip in the CI preliminary
step.
2) Ensure sourceModified changes are considered
See reactor/reactor#722.
If a change is binary compatible but not source compatible, using
`onlyBinaryCompatibleModified = true` will mask the issue. This
change uses `onlyModified = true` instead. This is slightly more
verbose, but this is alleviated by (1).
3) Exclude NEW_DEFAULT_METHOD as a …

Improve JapiCmp: avoid misses, improve reporting and exclusions

---

reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java

A response with `Content-Length: 0` is already sent so any other additional data will be dropped.
https://github.com/netty/netty/pull/12836

[test] Adapt to Netty change to drop the data when it is unexpected

---

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

When a _TLS close_notify_ is received and when the _close_notify_ ack is replied, then the Netty _SslHandler_ just does not close the channel. Instead of that, in that case it fires a _SslCloseCompletionEvent.SUCCESS_ event down the pipeline, and the closing of the channel is left to other handlers.
And since the [TLS RFC](https://www.rfc-editor.org/rfc/rfc5246#section-7.2.1) states that _the party receiving a close_notify MUST respond with a close_notify alert of its own and close down the connection immediately_, let's do this in Reactor-Netty.
This patch won't avoid AbortedExceptions or PrematureCloseException exceptions in case a close_notify is being received while a request is being written, or while a response is waited for, but it may address some of the pain highlighted by #2498, …

Close connection when a TLS close_notify is received and acknowledged.

---

build.gradle
reactor-netty5-core/src/main/java/reactor/netty5/NettyOutbound.java
reactor-netty5-core/src/main/java/reactor/netty5/ReactorNetty.java
reactor-netty5-core/src/test/java/reactor/netty5/NettyOutboundTest.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientConfig.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/Http2StreamBridgeServerHandler.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerConfig.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerOperations.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/SimpleCompressionHandler.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/WebsocketServerOperations.java
reactor-netty5-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty5-http/reflect-config.json
reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientOperationsTest.java
reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java
reactor-netty5-http/src/test/java/reactor/netty5/http/server/logging/AccessLogHandlerH1Tests.java
reactor-netty5-http/src/test/java/reactor/netty5/http/server/logging/AccessLogHandlerH2Tests.java

- Fix memory leaks when processing `EmptyLastHttpContent`
- Avoid buffer leak by closing the `HttpRequest` passed to the `WebSocketServerHandshaker.handshake` method
- Declare `ReactorNetty#BOUNDARY` as on-heap non-releasable buffer
- Do not close the empty full message when invoking `SimpleCompressionHandler` out of the pipeline
- `Http2StreamBridgeServerHandler.channelRead` method should use `Resource.dispose()` method
- [HttpServer] Ensure `Http2FrameCodec` is created only when there is a need for protocol upgrade
- [HttpClient] Ensure `Http2FrameCodec.Encoder` is closed when upgrade is rejected. Ensure `Http2FrameCodec.Encoder` is closed when `Exception` happened before decoding the server response
- Fix memory leaks in tests

Leak detection properties are added for the test execution

---

reactor-netty5-core/src/main/java/reactor/netty5/BufferFlux.java
reactor-netty5-core/src/main/java/reactor/netty5/BufferMono.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java

When possible use `BufferAllocator#compose(...)` for creating `CompositeBuffer` instead of `CompositeBuffer#extendWith` as the first performs better.
More information https://github.com/netty/netty/issues/12757

Use BufferAllocator#compose(...) for creating CompositeBuffer

---

reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java

The functionality is not used and will be removed in Reactor Netty 2.0.0

Deprecate ReactorNetty#toPrettyHexDump

---

reactor-netty5-core/src/test/java/reactor/netty5/resources/DefaultLoopResourcesTest.java

More information https://github.com/netty/netty/pull/12865

Temporary disable the check for KQueue as there is issue with MacOS natives

---

gradle/asciidoc.gradle

As per https://github.com/micrometer-metrics/micrometer-docs-generator/wiki/1.0.0-Migration-Guide 
```
micrometer-docs-generator-metrics and micrometer-docs-generator-spans are deprecated in favor of the new module 
micrometer-docs-generator which generates both metrics and spans (and observation conventions) documents.
```

Migrate to the new micrometer-docs-generator

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java

Netty 5 supports only strict cookie validation.

Deprecate Cookie encoder/decoder settings

---

reactor-netty5-http/src/main/java/reactor/netty5/http/client/AbstractHttpClientMetricsHandler.java

Under heavy load, an HttpClient may get the following NPE (using H2C):
```
10:54:05.730 [reactor-http-nio-6] WARN r.n.h.c.AbstractHttpClientMetricsHandler - [2a3a0c7d, L:/127.0.0.1:51440 - R:/127.0.0.1:8080](H2 - 6999) Exception caught while recording metrics.
java.lang.NullPointerException: null
at java.base/java.util.Objects.requireNonNull(Objects.java:208)
at io.micrometer.core.instrument.ImmutableTag.<init>(ImmutableTag.java:37)
at io.micrometer.core.instrument.Tag.of(Tag.java:31)
at io.micrometer.core.instrument.Tags.of(Tags.java:265)
at io.micrometer.core.instrument.AbstractTimerBuilder.tags(AbstractTimerBuilder.java:60)
at io.micrometer.core.instrument.Timer$Builder.tags(Timer.java:358)
at reactor.netty5.http.client.MicrometerHttpClientMetricsRecorder.lambda$recordDataSentTime$1(Mic …
```

Avoid NPE in AbstractHttpClientMetricsHandler write listener

---

reactor-netty5-core/build.gradle
reactor-netty5-core/src/main/java/reactor/netty5/transport/ClientTransport.java
reactor-netty5-core/src/main/java/reactor/netty5/transport/ProxyProvider.java
reactor-netty5-core/src/test/java/reactor/netty5/ConnectionTest.java
reactor-netty5-core/src/test/java/reactor/netty5/transport/ClientTransportTest.java
reactor-netty5-core/src/test/java/reactor/netty5/transport/ProxyProviderTest.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClient.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientProxyProvider.java
reactor-netty5-http/src/test/java/reactor/netty5/http/client/ClientTransportTest.java
reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientProxyProviderTest.java

Move HTTP proxy functionality from `ProxyProvider` to `HttpClientProxyProvider`.
Fixes #1953

Remove transitive dependency netty5-codec-http from reactor-netty5-core

---

reactor-netty5-http/src/main/java/reactor/netty5/http/client/AbstractHttpClientMetricsHandler.java

This PR removes the following compilation warnings introduced by PR #2539:
``
reactor-netty5-http/src/main/java/reactor/netty5/http/client/AbstractHttpClientMetricsHandler.java:108: warning: [NarrowingCompoundAssignment] Compound assignments from int to byte hide lossy casts
flags |= REQUEST_SENT;
^
(see https://errorprone.info/bugpattern/NarrowingCompoundAssignment)
Did you mean 'flags = (byte) (flags | REQUEST_SENT);'?
reactor-netty5-http/src/main/java/reactor/netty5/http/client/AbstractHttpClientMetricsHandler.java:151: warning: [NarrowingCompoundAssignment] Compound assignments from int to byte hide lossy casts
flags |= RESPONSE_RECEIVED;
``

Suppress NarrowingCompoundAssignment warnings

---

reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java
reactor-netty-core/src/main/java/reactor/netty/channel/ConnectSpans.java
reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTracingObservationHandler.java
reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionObservations.java
reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionSpans.java
reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSpans.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyPropagatingReceiverTracingObservationHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/observability/ReactorNettyPropagatingSenderTracingObservationHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerObservations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerSpans.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md
Reactor Netty will publish the following spans
```
SpansAssert.assertThat(bb.getFinishedSpans().stream().filter(f -> f.getTraceId().equals(current.context().traceId()))
.collect(Collectors.toList()))
.hasASpanWithName("hostname resolution",
spanAssert -> spanAssert.hasTagWithKey("net.peer.name")
.hasTagWithKey("net.peer.port")
.hasTagWithKey("reactor.netty.protocol")
.hasTagWithKey("reactor.netty.status")
.hasTagWithKey("reactor.netty.type"))
.hasASpanWithName("connect",
spanAssert -> spanAssert.hasTagWithKey("net.peer.name")
.hasTagWithKey("net.peer.port") …
```

Ensure Reactor Netty follows the requirements for span name and tags

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientFormEncoder.java

Create file uploads with streams always via `DefaultHttpDataFactory`. This ensures that they are added to `DefaultHttpDataFactory#requestFileDeleteMap` and thus they will be cleaned at the end of the operation.

Fix memory leak in HttpClient#sendForm for file uploads with streams

---

.github/workflows/check_transport.yml
build.gradle
reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/http/server/multipart/Application.java
reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/http/server/multipart/custom/Application.java
reactor-netty5-http/build.gradle
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClient.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientFinalizer.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientForm.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientFormEncoder.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerFormDecoderProvider.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerOperations.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerRequest.java
reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientTest.java
reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientWithTomcatTest.java
reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerFormDecoderProviderTests.java
reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerPostFormTests.java
reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java

Related to #2221
This PR is an attempt to reintegrate the Multipart feature into netty5 branch using new netty-contrib multipart codec.
The old multipart code that has bee reintegrated comes from the latest 1.0.x branch.

Reintegrate multipart into netty5 branch

---

reactor-netty-core/build.gradle
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpMetricsTests.java
reactor-netty-http/build.gradle
reactor-netty-http/src/noMicrometerTest/java/reactor/netty/http/client/HttpClientNoMicrometerTest.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

Ensure that when there is no dependency to micrometer artifacts, there is no dependency to context-propagation also.
Fixes the exception below observed while executing junit tests:
```
java.lang.NoSuchMethodError: io.micrometer.context.ContextSnapshot.setAllThreadLocalsFrom(Ljava/lang/Object;)Lio/micrometer/context/ContextSnapshot$Scope;
at reactor.core.publisher.ContextPropagation.lambda$contextRestoreForHandle$4(ContextPropagation.java:137)
at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:292)
```

Ensure junit tests do not have dependency to context-propagation

---

reactor-netty-http-brave/build.gradle

Now that `reactor-netty-http-brave` is deprecated in favour of the integration with `Micrometer Tracing`, the dependency that `reactor-netty` has to this artifact is removed.
The integration is still there if one adds a direct dependency to `reactor-netty-http-brave`. It is just removed from the `reactor-netty`.
Remove the plugin for javadoc as it brings  to `reactor-netty` a runtime dependency to `reactor-netty-http-brave`

Remove from reactor-netty artifact the integration with Brave

---

reactor-netty5-core/src/main/java/reactor/netty5/DisposableChannel.java
reactor-netty5-core/src/main/java/reactor/netty5/FutureMono.java
reactor-netty5-core/src/main/java/reactor/netty5/channel/ChannelOperations.java
reactor-netty5-core/src/main/java/reactor/netty5/resources/DefaultLoopResources.java
reactor-netty5-core/src/main/java/reactor/netty5/resources/DefaultPooledConnectionProvider.java
reactor-netty5-core/src/main/java/reactor/netty5/udp/UdpOperations.java
reactor-netty5-core/src/test/java/reactor/netty5/FutureMonoTest.java
reactor-netty5-core/src/test/java/reactor/netty5/NettyOutboundTest.java
reactor-netty5-http/src/main/java/reactor/netty5/http/HttpOperations.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/Http2Pool.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/HttpClientOperations.java
reactor-netty5-http/src/main/java/reactor/netty5/http/client/WebsocketClientOperations.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerOperations.java
reactor-netty5-http/src/main/java/reactor/netty5/http/server/WebsocketServerOperations.java
reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientTest.java
reactor-netty5-http/src/test/java/reactor/netty5/http/server/HttpServerTests.java

Reactor Netty does not need the type of cancellation provided by `Mono#fromCompletionStage`

Use FutureMono instead of Mono#fromCompletionStage

---

reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerRequest.java

The issues below were observed while generating javadoc
```
/.../reactor-netty/reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerRequest.java:99: warning: Tag @link: reference not found: Attribute
* returns a {@link Flux} of {@link HttpData} containing received {@link Attribute}/{@link FileUpload}.
/.../reactor-netty/reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerRequest.java:99: warning: Tag @link: reference not found: FileUpload
* returns a {@link Flux} of {@link HttpData} containing received {@link Attribute}/{@link FileUpload}.
/.../reactor-netty/reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerRequest.java:104: warning: Tag @link: reference not found: HttpData#retain()
* <p>{@link HttpData#retain()} disables auto …
```

Fix javadoc

---

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java

When `GO_AWAY` is received and there are no streams the connection is removed from the pool. If there are streams the connection is filtered and not used for creation of new streams.

Update `Http2Pool` javadoc

---

docs/asciidoc/http-client-conn-provider.adoc
reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java

Clarify that the connection pool can be disposed only when there are no active connections, idle connections and pending acquisitions.

Update documentation for `ConnectionProvider.Builder#disposeInactivePoolsInBackground`

---

reactor-netty-http/build.gradle
reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

Test HTTP/1.1 and HTTP/2 with/without enabled eviction in background.

Add test for `ConnectionProvider.Builder#disposeInactivePoolsInBackground`

---

reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java

Since version `1.0.11`, `MicrometerPooledConnectionProviderMeterRegistrar` is not an implementation of this interface. See #1806

Update `ConnectionProvider.MeterRegistrar` javadoc

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpResponseStatusCodesHandlingTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Ensure `CL`/`TE` headers are handled correctly for `204`/`205`/`304` status codes when server configured with `HTTP/2`

---

docs/asciidoc/tcp-client.adoc
docs/asciidoc/tcp-server.adoc
docs/asciidoc/udp-client.adoc
docs/asciidoc/udp-server.adoc
reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java

Update `ReactorNetty#IO_SELECT_COUNT` javadoc

---

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

Ensure `HttpServer` `Active Connections` metric is correct when connection closure before response write

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java

When a `Mono` is sent as a response or a single `ByteBuf` is sent as a response, `Reactor Netty` will send `FullHttpResponse` and thus is able to set `Content-Length` if such is not already set. Based on the `Content-Length`, `Reactor Netty` can decide whether or not a compression is needed.

Ensure `HttpServer` `minCompressionSize` is respected when `Content-Length` is not explicit and response is `Mono`

---

reactor-netty-examples/src/main/java/reactor/netty/examples/udp/qotm/QuoteOfTheMomentClient.java
reactor-netty-examples/src/main/java/reactor/netty/examples/udp/qotm/QuoteOfTheMomentServer.java

This PR attempts to provide a corresponding Reactor Netty version of the QOTM example available in Netty project.
Related to https://github.com/reactor/reactor-netty/issues/761

Add Reactor Netty version of the Quote of the Moment example #761

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopResources.java
reactor-netty-core/src/main/java/reactor/netty/resources/LoopResources.java

When a custom event loop group is configured for an H2/H2C http client (i.e using `HttpClient.runOn(LoopResources.create("client", 16, true))` for example), then in  _Forwarder_ kind of scenario when a JVM forwards a received H2/H2C request using the HttpClient to an upstream server, then in this case, it may happen that the custom event loops are unevenly distributed among the http client channels.
what happen is the following:
- One available Slot is being delivered to a borrower from one of the custom event loop [here](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java#L387-L388), so drain() is called from the custom event loop thread.
- if at this point there are many borrowers but no more streams are available …

Allow to configure colocation when creating LoopResources

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/IdleTimeoutHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java

- When the server is configured with `HTTP/1.1` and `H2C` ensure `Http2MultiplexHandler` is at the end of the pipeline because this handler doesn't forward all `channelRead` events.
- When the server is configured with `HTTP/1.1` and `H2` and the client sends `HTTP/1.1`, when `channelActive` event happens, `HttpTrafficHandler` is still not in the pipeline. In this use case add `IdleTimeoutHandler` when `HttpTrafficHandler` is added to the pipeline.
Fixes #2649

Ensure `IdleTimeoutHandler` receives always `channelRead` events

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java

Currently a client that's configured for HTTP 1.1, H2, and H2C is unable to make requests to both HTTPS and HTTP urls due to checks in HttpClientConnect.java which can be safely ignored as long as a backup protocol is configured.
The following changes are in line with discussion in this PR [#1403](https://github.com/reactor/reactor-netty/pull/1403#issuecomment-737087183). Specifically the table as follows.
Configured Client Protocols | Server URI scheme | Used Protocol | Current Status
--- | --- | --- | ---
{`H2`} | `http` | _error_ | Works
{`H2`} | `https` | `H2` (pre-known) | Works
{`H2C`} | `http` | `H2C` (pre-known) | Works
{`H2C`} | `https` | _error_ | Works
{`HTTP11`} | `http` | `HTTP11` | Works
{`HTTP11`} | `https` | `HTTP11` | Works
{`H2`, `H2C`} | `http` | `H2C` (pre-known) | …

Allow H1, H2, and H2C protocol for HttpClient

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/RedirectClientException.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java

Fix `NullPointerException` when `followRedirect` is true, but there is no `location` header

---

build.gradle

`jackson-databind` is used only in tests, url to `jackson-databind` javadoc is not needed for generating `Reactor Netty` javadoc

`Reactor Netty` javadoc generation does not need `jackson-databind` javadoc url

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java

Handling inbound streams (server pushes) is not supported and disabled. Use empty shared `ChannelHandler` for configuring `Http2MultiplexHandler`.

Use empty shared `ChannelHandler` for inbound stream handling on the `HttpClient`

---

reactor-netty-examples/src/main/java/reactor/netty/examples/tcp/securechat/SecureChatClient.java
reactor-netty-examples/src/main/java/reactor/netty/examples/tcp/securechat/SecureChatServer.java

Provide a corresponding Reactor Netty version of Secure chat server example as found in Netty project.
Related to #761

Add Reactor Netty version of secure chat server example reactor#761

---

reactor-netty-http/build.gradle
reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInformation.java
reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

- The host name and port are derived from the `Host`/`X-Forwarded-*`/`Forwarded` header associated with this request.
- When `X-Forwarded-*`/`Forwarded` header does not specify a port, add a port as per the scheme

Add `ConnectionInformation#hostName/hostPort`

---

reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java

This change is in addition to PR #2714

When the scheme is `https`/`wss`, the https default port is used as a fallback option

---

reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

Handle empty `HOST` header when processing connection information

---

reactor-netty-core/src/main/java/reactor/netty/channel/MeterKey.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientConfig.java
reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/Http2SettingsSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpResponseDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerFormDecoderProvider.java

This call requires an Object[] allocation and does boxing on primitives, so should not be used in high performance environments.
CPU usage before: 
CPU usage after:
sorry for the duplicate, wrong base branch on the first time

Replace Objects.hash()

---

reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

When graceful shutdown, ensure the streams are processed before closing connection

---

reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-core/src/test/java/reactor/netty/resources/PoolKeyTest.java

The SocketAddres.toString method to generate the FQDN is relatively heavy and it appears to be unnecessary given the socket address is being hashed and equaled already. This should work for unix domain sockets as well.
This code:
````java
System.out.println(AddressUtils.createUnresolved("127.0.0.1", 80));
System.out.println(AddressUtils.createUnresolved("127.0.0.1", 80).equals(AddressUtils.createUnresolved("127.0.0.1", 80)));
System.out.println(AddressUtils.createUnresolved("example.com", 80));
System.out.println(AddressUtils.createUnresolved("example.com", 80).equals(AddressUtils.createUnresolved("example.com", 80)));
System.out.println(AddressUtils.createResolved("example.com", 80));
System.out.println(AddressUtils.createResolved("example.com", …
```

Smarter usage of `FQDN` in `PoolKey`

---

reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
reactor-netty-core/src/test/java/reactor/netty/channel/FluxReceiveTest.java

This PR fixes the issue that appears when late inbound subscriber races with connection dispose

Ensure early dispose is delivered to late subscriber

---

reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java

Always takes into account any available `X-Forwarded-Port` header even if the `X-Forwarded-Host` header is missing.
Fixes #2751

Parse X-Forwarded-Port header even if X-Forwarded-Host is not present

---

reactor-netty-core/src/test/java/reactor/netty/NettyOutboundTest.java

Make it obvious that the test fails with `UnsupportedMessageTypeException`

---

reactor-netty-examples/src/main/java/reactor/netty/examples/http/echo/EchoServer.java
reactor-netty-examples/src/main/java/reactor/netty/examples/http/helloworld/HelloWorldServer.java

Iam getting error when try to run http2 on Netty examples
I found that it uses `Http11SslContextSpec` to generate certificates for both `http11` and `http2` which should use `Http2SslContextSpec` for `http2`

Use `Http2SslContextSpec` to build `SslContext` when `http2` enabled

---

reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java

Configure `Http2FrameCodec` with indefinite graceful shutdown timeout as the scheduling happens with `ServerTransport#disposeNow`
https://datatracker.ietf.org/doc/html/rfc9113#GOAWAY
```
The GOAWAY frame (type=0x07) is used to initiate shutdown of a connection... GOAWAY allows an endpoint to gracefully
stop accepting new streams while still finishing processing of previously established streams.
```
```
Once the GOAWAY is sent, the sender will ignore frames sent on streams initiated by the receiver if the stream has an
identifier higher than the included last stream identifier. Receivers of a GOAWAY frame MUST NOT open additional streams
on the connection...
```
```
A GOAWAY frame might not immediately precede closing of the connection
```
```
Activity on streams numbered lower than or …
```

When in graceful shutdown, send `GO_AWAY` to notify the client to stop opening streams

---

.github/workflows/check_netty_snapshots.yml
build.gradle
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpTrafficHandler.java

In case `H2C` client tries to connect to a secured `HTTP` server, the connection is directly closed. This is a result of this `Netty` change.
https://github.com/netty/netty/pull/13314

Depend on `Netty` `v4.1.91.Final`

---

reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
reactor-netty-core/src/test/java/reactor/netty/channel/MonoSendManyTest.java

this fix ensures that in case of async fusion, the queue.clear() method is called regardless it is cancellation or terminal (via onComplete/onError)

ensures queue.clear is called in terminal cases for ASYNC fusion

---

.github/workflows/check_netty_snapshots.yml
build.gradle
reactor-netty-http/src/test/java/reactor/netty/http/server/Http2ConnectionInfoTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

- Exclude tests in `Http2ConnectionInforTests` with `HOST` header empty
https://github.com/netty/netty/pull/13238
- Fix unix domain socket tests in `HttpServerTests` as local and remote addresses are now available 
https://github.com/netty/netty/pull/13323

Depend on `Netty` `v4.1.92.Final`

---

reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Motivation:
Sometimes, when initiating a graceful shutdown on an HTTP2 server, it may happen that some connections are closed without sending GOAWAY.
This may (not always) happen under the following conditions:
- the server is configured with H2/HTTP11 or H2C/HTTP11
- some streams are currently being processed on the server
- at this point a graceful shutdown is initiated
Under these conditions, the `channelGroup` that is associated to the `HttpServer` contains both stream channel as well as their corresponding parent socket channels. So, when the graceful shutdown is initiated, the [ServerTransport.disposeNow(Duration)](https://github.com/reactor/reactor-netty/blob/1.0.x/reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java#L549) method is iterating on all …

Server might not send GOAWAY when some streams are being processed

---

reactor-netty-http/src/test/java/reactor/netty/http/Http2SettingsSpecTests.java

We need to adapt the Http2SettingsSpecTests, because since Netty [PR#13369](https://github.com/netty/netty/pull/13369), the messages of the IllegalArgumentExceptions thrown when invalid Http2Settings are used have changed, and the following tests in the reactor-netty `Http2SettingsSpecTests` test are not passing anymore:
```
headerTableSizeBadValues
Expecting message to be:
"Setting HEADER_TABLE_SIZE is invalid: -1"
but was:
"Setting HEADER_TABLE_SIZE is invalid: -1, expected [0, 4294967295]"
maxFrameSizeBadValues
Expecting message to be:
"Setting MAX_FRAME_SIZE is invalid: -1"
but was:
"Setting MAX_FRAME_SIZE is invalid: -1, expected [16384, 16777215]"
maxHeaderListSizeBadValues
Expecting message to be:
"Setting MAX_HEADER_LIST_SIZE is invalid: -1"
but was:
"Setting MAX_HEADER_LIST_SIZE …
```

Adapt Http2SettingsSpecTests to new netty error messages 

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientFinalizer.java
reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketFinalizer.java

When I looked at the implementation of the class **HttpClientFinalizer** code, I found that the logic of the **responseContent** method was a bit strange. HttpClientFinalizer.contentReceiver represents **ChannelOperations::receive**, while ChannelOperations::receive internal implementation has already made a call to **ByteBufFlux.fromInbound** to return a **ByteBufFlux**, and a call and encapsulation of ByteBufFlux.fromInbound has also been made in the responseContent method, This is actually unnecessary, so you can directly refer to the internal implementation of ChannelOperations::receive in the responseContent method to generate ByteBufFlux, which will result in better performance and clearer logic. Similarly, there are similar issues with **WebsocketFinalizer:responseContent**, which …

responseContent() remove excess ByteBufFlux conversion

---

build.gradle
reactor-netty-http/build.gradle
reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java

Note:   Netty 4.x supports Brotli compression.  Brotli compression is available if and only if the Brotli4j library is on the runtime classpath.

Add `Brotli` compression test

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpResponseStatusCodesHandlingTests.java

Ensure any custom `CL`/`TE` header is removed when `304` response code

---

reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

This PR only contains a test in order to check if the Netty #13388 fix from 4.1.93.Final version is fixing the use case described in #2760.
Fixes #2760

Add test for IllegalReferenceCountException/sendObject

---

.github/workflows/check_transport.yml
docs/asciidoc/http-server.adoc
reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/read/timeout/Application.java
reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/RequestTimeoutException.java
reactor-netty-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-http/reflect-config.json
reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

`HttpServer`: Add API for read related timeouts

---

reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
reactor-netty-core/src/test/java/reactor/netty/transport/TransportConnectorTest.java

Fix issue https://github.com/reactor/reactor-netty/issues/2843 by closing channel on bind (and other) exception

Fix memory leak of HTTP server on bind failure

---

reactor-netty-examples/src/main/java/reactor/netty/examples/http/snoop/HttpSnoopClient.java
reactor-netty-examples/src/main/java/reactor/netty/examples/http/snoop/HttpSnoopServer.java

Add a 'http snoop server' sample which receives any request and tells the client the details of the request in a formatted string [#{761}](https://github.com/reactor/reactor-netty/issues/761)
This is a sample http server that corresponds to [HttpSnoopServer](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/snoop/HttpSnoopServer.java) in examples of project netty.
Please notice that the http snoop server is not the same as the http echo server.
It will return the details of the request, not only the request body.
So I think it is a good example for people who want to learn how to use reactor-netty to build a http server and have a full control of the request and response.
I have tested it and it works well.
I'm unfamilar with such PR operation, if there …

Add a `http snoop server` sample

---

reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

From time to time `HttpServerTests#testSniSupportHandshakeTimeout` fails on CI with
```
HttpServerTests > testSniSupportHandshakeTimeout() FAILED
java.lang.AssertionError:
Expecting actual not to be null
at reactor.netty.http.server.HttpServerTests.testSniSupportHandshakeTimeout(HttpServerTests.java:2259)
```

Fix flaky test

---

.github/workflows/check_graalvm.yml
build.gradle
gradle/javadoc.gradle
gradle/setup.gradle
reactor-netty-graalvm-smoke-tests/build.gradle
reactor-netty-graalvm-smoke-tests/src/test/java/reactor/netty/http/HttpTests.java
reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/jni-config.json
reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/reflect-config.json
reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/resource-config.json
settings.gradle

Temporary add the missing `GraalVM` metadata to the test as the PRs below are still in progress 
https://github.com/oracle/graalvm-reachability-metadata/pull/379
https://github.com/oracle/graalvm-reachability-metadata/pull/382

Add `GraalVM` smoke tests

---

reactor-netty-http/src/test/java/reactor/netty/TomcatServer.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientWithTomcatTest.java

This is a new attempt to fix the flaky test from HttpClientWithTomcatTest.testIssue2825, which was still sometimes getting some Premature Close Exception.
To summarize:
- The fix from #2864 significantly reduces the probability to get premature close exceptions when Tomcat sends an early final response 400 bad request while the client is still writing a large request body. Did a benchmark using a real network, it works well; no premature close exceptions.
- However, on localhost, and especially on the Github CI, the fix only alleviate the problem but we can't avoid it all the time:   sometimes, once the server has sent the 400 bad request, and once it has read up to 2 MB of extra request body, it may then close the connection using a TCP/RST, so in this case, if the client has not yet …

Fix HttpClientWithTomcatTest flaky test.

---

reactor-netty-http/src/test/java/reactor/netty/TomcatServer.java

Fix cross-site scripting (XSS) vulnerability github security alert in the TomcatServer class.
See https://github.com/reactor/reactor-netty/security/code-scanning/9

Fix cross-site scripting vulnerability in test

---

.github/workflows/check_reactor_core_3.6_snapshots.yml

`Reactor Netty 1.1.x` is included in `Reactor BOMs` `2022.0.x` and `2023.0.x`
thus we need to guarantee that `Reactor Netty` works properly
with `Reactor Core 3.5.x` and `Reactor Core 3.6.x`

Add nightly build with `Reactor Core` `3.6 SNAPSHOTs`

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

Ensure `HttpClient#mapConnect() / #doOnRequestError()` are called when `HttpClient#headersWhen()` is used

---

gradle/wrapper/gradle-wrapper.properties

According to the documentation the command below should be used for upgrade `./gradlew wrapper --gradle-version 7.6.3`

Bump `Gradle` to version `7.6.3`

---

reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

Ensure metrics are unregistered when inactive connection pool is disposed

---

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Reactor Netty’s HttpClient relies on Netty’s Http2FrameCodecBuilder. This codec, by default, **enforces** the MAX_HEADER_LIST_SIZE found in the SETTINGS sent by the server, meaning that If a request’s header list size exceeds the SETTINGS MAX_HEADER_LIST_SIZE limit, then HpackEncoder throws a **HeaderListSizeException**. Consequently, the request **is not sent**, and the client receives a PrematureCloseException error without any details.
Let's just add more specific root cause to the PrematureCloseException in order to make it meaningful in the case the request header size exceeds MAX_HEADER_LIST_SIZE (or if whatever Netty Http2 Codec exceptions are caught while writing the request out).
Example:
```
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE …
```

Add root cause exception when throwing PrematureCloseException

---

reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClient.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java

- 3s for close_notify flush timeout
- 0s for close_notify read timeout

Update TLS configuration defaults in javadoc

---

.github/workflows/check_graalvm.yml
reactor-netty-graalvm-smoke-tests/build.gradle
reactor-netty-graalvm-smoke-tests/src/test/resources/META-INF/native-image/jni-config.json

Apply a workaround for https://github.com/oracle/graal/issues/4304

Add `Windows OS` to the matrix for `GraalVM` CI tests

---

reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
reactor-netty-core/src/test/java/reactor/netty/channel/MicrometerChannelMetricsRecorderTests.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java
reactor-netty-http/src/test/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorderTests.java

When `HttpServer` is bound on any local address ensure that metrics `connections.total/active` are correct and show the corresponding number per local address.
Related to #2945

Ensure `HttpServer` metrics `connections.total/active` are correct when multiple local addresses

---

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

Ensure the real connection local address without any proxy information is used for `HttpServer` `connections.active` metrics

---

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java

Ensure `ChannelHandlerContext.isRemoved` is called only when in event loop

---

reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java

Websocket compression handler has to be located after the HTTP codec.
Fixes #3036

Ensure `websocket` `compression` is enabled when `server` is configured with `HttpProtocol.H2C` and `HttpProtocol.HTTP1.1`

---

docs/asciidoc/http-client.adoc
docs/asciidoc/tcp-client.adoc
reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java

Add an API for configuring the resolver to fallback to `TCP` if a timeout is detected. By default, the resolver will only try to use `TCP` if the response is marked as truncated.
Fixes #3059

Enable `DNS` `retryOnTimeout` with `TCP`

---

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/ContextAwareHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java

Ensure `remoteAddress` metrics tag is always the real remote address regardless whether there is proxy

---

reactor-netty-core/src/main/java/reactor/netty/Metrics.java
reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMeters.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMetricsRecorder.java
reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java
reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/ContextAwareChannelMetricsRecorder.java
reactor-netty-core/src/main/java/reactor/netty/channel/MeterKey.java
reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeObservations.java
reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/ContextAwareHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/ContextAwareHttpClientMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMeters.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java

Add proxy address information to the metrics

---

docs/asciidoc/http-client.adoc
docs/asciidoc/tcp-client.adoc
docs/asciidoc/udp-client.adoc
docs/asciidoc/udp-server.adoc
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClient.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientConnect.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpServer.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpClient.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpClientConnect.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpServer.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpServerBind.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClient.java
reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClientConnect.java
reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicServer.java

- Update javadoc
- Update reference documentation
Fixes #3070

Provide better exception message for invalid `PORT` env variable

---

reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java

Add tests for metric `pending.connections.time` with status `ERROR`

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

- Place `ResponseTimeoutHandler` before `HttpMetricsHandler` so that is an error happened it can be recorded
- Add test to verify that errors with establishing a connection are recorded
Fixes #3060

When metrics are enabled and `responseTimeout` is configured, ensure the correct order for `ChannelHandlers`

---

docs/asciidoc/conn-provider-metrics.adoc

Add info for `reactor.netty.connection.provider.pending.connections.time` metric

---

reactor-netty-http/src/main/java/reactor/netty/http/websocket/WebsocketSpec.java

Clarify maximum websocket frame length configuration

---

build.gradle
reactor-netty-http/build.gradle
reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java

Netty supports zstd compression.
This PR validates that zstd compression is working as expected.
https://github.com/luben/zstd-jni

validate zstd compression

---

docs/modules/ROOT/pages/faq.adoc
docs/modules/ROOT/pages/http-client.adoc

In both files, the documentation is related to HTTP client timeouts.

Fix links to `Connection Timeout` and `Timeout Configuration`

---

reactor-netty/build.gradle

There is wrong description in docsZip gradle task from reactor-netty/build.gradle, it should be removed.

Remove wrong description in docsZip

---

reactor-netty/build.gradle

when running "./gradlew antora", if the version is not a -SNAPSHOT version, then the pdf is generated in docs/build/assembler/reactor-netty/version/reactor-netty-reference-guide.pdf
for example:
- if version is 1.2.0, then "./gradlew antora" generates the pdf in docs/build/assembler/reactor-netty/1.2.0/reactor-netty-reference-guide.pdf
- if version is 1.2.0-M1, then "./gradlew antora" generates the pdf in docs/build/assembler/reactor-netty/1.2.0-M1/reactor-netty-reference-guide.pdf
so, now, when running "./gradlew publishToMavenLocal", the **docsZip** in reactor-netty/build.gradle is stripping the version, like this:
```
task docsZip(type: Zip) {
...
def isSnapshot = project.version.endsWith('-SNAPSHOT')
def version = project.version.takeWhile { it != '-' }
def pdfFile = …
```

Pdf is not included in milestone release

---

.github/workflows/check_transport.yml

The action `gradle/wrapper-validation-action` has been replaced by `gradle/actions/wrapper-validation`. See https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlewrapper-validation-action-has-been-replaced-by-gradleactionswrapper-validation

Replace gradle/wrapper-validation-action with gradle/actions/wrapper-validation

---

build.gradle
reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
reactor-netty-http/build.gradle
reactor-netty-http/src/main/java/reactor/netty/http/Http3SslContextSpec.java

- `QuicSslContextBuilder` does not extend `SslContextBuilder`.
- Add `Http3SslContextSpec`, similar to `Http2SslContextSpec` and `Http11SslContextSpec`.
Related to #1531

Make `ProtocolSslContextSpec` generic

---

reactor-netty-http/src/main/java/reactor/netty/http/Http3SettingsSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/Http3SettingsSpecTest.java

Add `HTTP/3` initial settings

---

build.gradle
gradle/setup.gradle
reactor-netty/build.gradle

Since the migration to Antora, it's not possible anymore to do a full build using jdk17:
```
sdk use java 17.0.10-zulu
./gradlew publishToMavenLocal
> Configure project :
1.2.0-SNAPSHOT is a snapshot, will use 1.2.0.BUILD-202404040843 for bnd
[Spotless] Local run detected, ratchet from origin/main
> Task :docs:generatePomFileForMavenJavaPublication FAILED
FAILURE: Build failed with an exception.
* Where:
Script '/Users/***/Documents/reactor-netty/gradle/setup.gradle' line: 153
* What went wrong:
Execution failed for task ':docs:generatePomFileForMavenJavaPublication'.
> Could not apply withXml() to generated POM
> Cannot invoke method children() on null object
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run …
```

Re enable full build with jdk17

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpProtocol.java
reactor-netty-http/src/main/java/reactor/netty/http/internal/Http3.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerBind.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java

Add `HttpProtocol#HTTP3`

---

.github/workflows/publish.yml

in the publish CI, the `cleanup` job is using a too broad permission (`permissions: write-all`) when deleting the docs-build artifact.
According to https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#delete-an-artifact, we can limit the permission to only the necessary level: `actions: write`

Limit permission in publish cleanup job

---

reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java

`SslProvider.SslContextSpec#sslContext(reactor.netty.tcp.SslProvider.ProtocolSslContextSpec)` is deprecated in favour of  `SslProvider.SslContextSpec#sslContext(reactor.netty.tcp.SslProvider.GenericSslContextSpec<?>)`

Deprecate `SslContextSpec#sslContext(reactor.netty.tcp.SslProvider.ProtocolSslContextSpec)`

---

docs/build.gradle
reactor-netty/build.gradle

This PR is an attempt to accelerate the build when using JDK17, and when you don't need to generate antora docs.
typically, it should accelerate commands like `./gradlew clean build`
to build the documentation:
- `./gradlew antora` (docs is generated to docs/build/site/ as before)
- or `./gradlew publishToMavenLocal`
modifications:
- the docs/build.gradle is not making the build depending on antora anymore
- removed the following unnecessary declaration in reactor-netty/build.gradle, which comes from spring-pulsar, we don't need this, and it forces the docsZip to be created when building or assembling the project:
```
artifacts {
archives docsZip
}
```
Fixes #3157

Build Antora only when publishing

---

build.gradle
reactor-netty-http/src/test/java/reactor/netty/tcp/SslProviderTests.java

`Reactor Netty` version `1.2.0` will be released with `Netty` version `> 4.1.98.Final`

Remove useless check

---

docs/modules/ROOT/pages/appendices.adoc

`:toc:` in `appendices.adoc` makes the table of contents to be rendered under the navigation on the left

Remove unnecessary `:toc:` from `appendices.adoc`

---

reactor-netty-http/src/main/java/reactor/netty/http/Http3SettingsSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/Http3SslContextSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/HttpProtocol.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java

Annotate `HTTP/3` server support as incubating

---

build.gradle
reactor-netty/build.gradle

Without this dependency the javadoc cannot be built correctly.
Related to #1531

Add dependency to `Netty HTTP3 Codec` for aggregated javadoc

---

reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

This is a change additional to the change made with #2755

Always use remote socket address for the metrics

---

.github/workflows/check_netty_snapshots.yml
.github/workflows/check_transport.yml

The `macos-11` label has been deprecated and will no longer be available after `6/28/2024`. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

Update to `macos-12` runner image

---

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java

Do not search for `HttpServerOperations` every time when a request info is needed.

Cache the request info when collecting metrics

---

docs/antora.yml

currently, authors are declared in two places:
- in docs/modules/ROOT/pages/about-doc.adoc: authors are declared in the [Multiple authors line](https://docs.asciidoctor.org/asciidoc/latest/document/author-attribute-entries), in the start page (about-adoc.adoc). Authors are then displayed when browsing antora documentation (in the start page).
- in antora.yml, using an author attribute: this was attempt to make the authors also appearing in the front page of the generated pdf.
But the authors are not currently included in the front page of the PDF.
this PR moves the author attribute from the antora attributes to the asciidoc attributes in the antora.yml, and this fixes the problem: authors are now displayed in the front page of the generated PDF.

Fix Authors attribute

---

docs/modules/ROOT/pages/about-doc.adoc

Reuse the {reactor-netty-github-repo-attribute} attribute when possible.

Reuse reactor-netty-github-repo-attribute when possible

---

reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

Ensure `HttpServerMetricsRecorder#recordServerConnectionInactive/Close` is invoked for websockets

---

reactor-netty-core/src/main/java/reactor/netty/Metrics.java
reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java
reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientConfig.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpMetricsTests.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpSecureMetricsTests.java
reactor-netty-http/src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java

When there is no proxy add `na` as a value tag.
Fixes #3218

Always add `proxy.address` tag for the client metrics

---

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java

Obtain the channel from `ChannelHandlerContext` instead of `HttpServerOperations`

---

reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java

Dispose metrics not only when `onErrorResume`, but also on a happy path.
Fixes #3226

Ensure `ConnectionProvider` metrics are disposed unconditionally when graceful shutdown

---

reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Fix the observed exception:
```
java.lang.IllegalStateException: Stream 3 in unexpected state HALF_CLOSED_LOCAL
at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeData(DefaultHttp2ConnectionEncoder.java:135)
at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeData(DecoratingHttp2FrameWriter.java:39)
at io.netty.handler.codec.http2.Http2FrameCodec.write(Http2FrameCodec.java:310)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:895)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java …
```

Ensure `ByteBuf#release` is invoked for already sent `HTTP/2` response

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java

Reduce the number of `ChannelFuture` listeners attached to the last message.

Immediately mark outbound as complete when sending `Mono` or `Object`

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java

When read is in process, delay the last flush until the read is done.

Add possibility to delay the last flush operation

---

reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AbstractAccessLogArgProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProviderH1.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java

Adapt access log to the delayed last flush operation

---

docs/asciidoc/eventloop.adoc
docs/asciidoc/http-client-conn-provider.adoc
docs/asciidoc/tcp-client-conn-provider.adoc

Extend the documentation for the shared (default) `ConnectionProvider` and `Event Loop Group`

---

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/ContextAwareHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java

Adapt metrics to the delayed last flush operation

---

.github/workflows/publish.yml

This proposes three enhacements related to Antora when publishing from the CI:
- first, the `deploySnapshot`, `deployMilestone`, and `deployRelease` were not depending on the `build-branch-doc` job. so far, it worked because the docs generation is faster then the `deploySnapshot`, `deployMilestone`, and `deployRelease` jobs. But for sake of robustness, let's explicitly make `deploySnapshot`, `deployMilestone`, and `deployRelease` depending on the `build-branch-doc` job.
- second, in case some flaky tests are taking place, the cleanup job is currently always executed, meaning that the generated docs zip is then deleted from the workflow run. So this prevents to rerun the deploy jobs, which will fail because the generated docs zip has been deleted by cleanup. To fix this: the cleanup job is …

Enhance robustness of publish.yml related to Antora

---

gradle/antora-docs.gradle
reactor-netty/build.gradle

This PR tries to enhance user experience when building reactor netty/antora:
1.  if the current JDK version is < JDK17 and if one invokes "./gradlew antora", the currently, the following error is logged:
```
Task 'antora' not found in root project 'reactor-netty' and its subprojects.
``` 
instead of that, a clear error should be logged in order to indicate that the current JDK version is lower than 17, and JDK17+ version is required:
```
./gradlew antora
> antora task requires JDK 17 or higher.
```
2. if the current JDK version is < JDK17 and if one invokes "./gradlew docs", and if the docs have not been previously built  with a JDK17+ version, then currently nothing is displayed. A clear  message should be logged in order to indicate that JDK17+ version is required to build the doc:
``` …
```

Enhance Antora gradle build

---

reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
reactor-netty-core/src/main/java/reactor/netty/channel/MonoSend.java

MonoSend.MAX_SIZE is a constant used by MonoSendMany and its SendManyInner class to request initial items from a publisher to send to an output Channel. This PR introduces a way to configure MonoSend.MAX_SIZE by using `reactor.netty.channel.send.prefetch.maxSize`(Upd. `reactor.netty.send.maxPrefetchSize`) system property. A custom value for the property may be necessary if requested items from publisher are large and requesting default number of items (128) requires too much memory. 
Fixes #3255

Make `MonoSend.MAX_SIZE` configurable by system property

---

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

Close the connection when decoding exception happens

---

reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/http3/Application.java
reactor-netty-http/build.gradle
reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3SettingsSpecTest.java
reactor-netty-http/src/http3Test/resources/logback.xml
reactor-netty-http/src/main/java/reactor/netty/http/Http3SettingsSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ChannelInitializer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java

Add `HTTP/3` client initial settings

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java

Add bind support for `DefaultPooledConnectionProvider`

---

docs/modules/ROOT/pages/http-client.adoc
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/http3/Application.java
reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3Tests.java
reactor-netty-http/src/main/java/reactor/netty/http/HttpResources.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http3ChannelInitializer.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http3Codec.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http3ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http3Pool.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http3StreamBridgeClientHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpConnectionProvider.java
reactor-netty-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-http/reflect-config.json
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpConnectionProviderTest.java

Initial `HTTP/3` client support

---

reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java
reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java

When an explicit `EventLoopGroup` is configured ensure only one connection pool is created

---

.gitignore
build.gradle
docs/package.json
gradle/antora-docs.gradle

This PR is an attempt to apply some modernization related to Antora gradle build.
It is related to https://github.com/spring-projects/spring-framework/pull/32864

Modernize Antora Build

---

.github/workflows/publish.yml
build.gradle
buildSrc/src/main/groovy/reactor/netty/docs/gradle/DeployDocs.groovy
reactor-netty/build.gradle

This PR is meant to publish javadoc and reference docs to docs.spring.io/projecrtreactor/reactor-netty/
In this PR, a new deployDocs gradle plugin is used to prepare/upload and install javadoc/reference docs.
The deployDocs gradle plugin is now using [SimpleSSH](https://github.com/RationaleEmotions/SimpleSSH/blob/master/README.md) java library which supports JDK 8, so it drastically simplifies everything.
note that SimpleSSH depends on an old com.jcraft:jsch project which is deprecated and this PR replaces it with https://github.com/mwiede/jsch, which can be used as a drop-in replacement for old com.jcraft:jsch.
on each push, the following docs will be updated here:
`https://docs.spring.io/projectreactor/reactor-netty/docs/VERSION/api/` (javadoc) …

Publish javadoc / reference docs to spring.io

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java

This PR polishes Javadoc for the `HttpClient.compress()`.

Polish Javadoc for HttpClient.compress()

---

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java

This is a regression caused by #3211
Fixes #3350

Do not record an exception when the request information is not available

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpInfos.java
reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

`HttpInfos#fullPath` and `HttpInfos#path` may throw `IllegalArgumentException` if the request uri violates `RFC2396`
Frameworks that use Reactor Netty may have their own request uri parser, therefor Reactor Netty will resolve on demand the path from the request uri.

Resolve on demand the path from the request uri

---

reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/Http3StreamBridgeServerHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

This is related only to `HTTP/1.1`, for `HTTP/2` and `HTTP/3` headers are always validated.
By default the validation is enabled.

`HttpDecoderSpec#validateHeaders()` specifies whether request/response headers are validated

---

gradle/wrapper/gradle-wrapper.properties

` ./gradlew wrapper --gradle-version=8.10.2`

Bump `Gradle` to version `8.10.2`

---

reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java

When `NettyOutbound#sendObject(java.lang.Object)` is used, it is Netty's responsibility to release the buffer on success/error
Fixes #3406

Ensure the buffer is not released twice

---

reactor-netty-http/build.gradle
reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java
reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerRequest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/forwardheaderhandler/CustomXForwardedHeadersHandler.java

The X-Forwarded-Prefix can be obtained via `HttpServerRequest#forwardedPrefix()`.

Parse X-Forwarded-Prefix request header

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpResponseDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpRequestDecoderSpec.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpDecoderSpecTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Support `allowPartialChunks` in the `HttpDecoderSpec`, closes https://github.com/reactor/reactor-netty/issues/3452

Support `allowPartialChunks` in the `HttpDecoderSpec`

---

.github/workflows/check_graalvm.yml
.github/workflows/check_netty_snapshots.yml
.github/workflows/check_transport.yml

`macOS-12` is deprecated and will be removed
https://github.com/actions/runner-images/issues/10721

Switch from `macOS-12` to `macOS-13` runner image

---

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java
reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/TracingHttpServerDecorator.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

When terminating detach the connection from request/response objects

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpDecoderSpec.java

FYI @reta, I stumbled across a typo in #3453

Fix typo in javadoc for `allowPartialChunks` setting

---

.github/workflows/check_graalvm.yml

There is an open issue with `action/setup-java` when `GraalVM` is configured

Temporary download manually `GraalVM` distribution

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

According to the spec https://www.rfc-editor.org/rfc/rfc9110.html#name-delete
```
A client SHOULD NOT generate content in a DELETE request unless it is made
directly to an origin server that has previously indicated, in or out of band, that
such a request has a purpose and will be adequately supported.
```
When a user sends `DELETE` with content this means there is an indication that the server supports this type of requests.

Ensure body is sent when `DELETE` and `Transfer-Encoding`

---

reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

- The server preface will be sent after receiving `SniCompletionEvent`
- TLS handshake metrics will be registered after receiving `SniCompletionEvent`
Fixes #3473

Delay sending the server preface when `SNI` is configured

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java

Ensure `HttpInfos#version` returns the correct protocol

---

gradle/wrapper/gradle-wrapper.properties

According to the documentation the command below should be used for upgrade 
`./gradlew wrapper --gradle-version=8.11`

Bump `Gradle` to version `8.11`

---

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopResources.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

When shutting down `EventLoopGroup`, `Netty` tries to add for an execution a task that will stop `EventLoops`. However if there is a CPU intensive task running on `EventLoop`, the execution of the shutting down task might never happen.
This change adds a timeout for `DefaultLoopResources#disposeLater` so that the user will be notified that some `EventLoops` cannot be stopped.
Note: Having blocking and CPU intensive tasks on `EventLoops` is strongly discouraged and can lead to unpredictable failures.
Fixes #3509

Add timeout for `DefaultLoopResources#disposeLater`

---

reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java
reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java
reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java

Configurations like `address`, `headers`, `password` are calculated just before sending the request. If a configuration is changed a new `connection pool` will be created.
Fixes #3501

Initialise lazy the `ProxyProvider` configuration

---

reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java

Ensure all ConnectionProvider built-in metrics are disabled when a custom recorder is provided

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java

When the incoming `LastHttpContent` is `EMPTY_LAST_CONTENT`, Reactor Netty directly completes the inbound. Handle the incoming `LastHttpContent` with no content in the same way instead of buffering it in `FluxReceive`.
Adapt the tests - instead of counting the received content on the server, directly count the outbound data on the client.

Handle the incoming `LastHttpContent` with no content as if it is `EMPTY_LAST_CONTENT`

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerOutboundCompleteTest.java

Ensure `HttpClient` sends full request when the send function does not change `NettyOutbound`

---

reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java

Calling `HttpOperations#initShortId()` could cause a `ClassCastException` if the underlying connection was replaced between checking its type and casting it to `AtomicLong`, for example if `ChannelOperations#terminate()` was called on another thread.
See also:
https://github.com/reactor/reactor-netty/blob/667f8c9cbf5a227a15f6d0a2f3aab7c4777613da/reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java#L515
Fixes #3541

Fix ClassCastException in `HttpOperations#initShortId()`

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

We have run into the issue with latest Apache HttpClient5 5.4.1 / Apache HttpCore5 5.3.1 as a client (Reactor Netty as the HTTP server with HTTP/1.1 and H2C protocols) that now tries HTTP/1.1 TLS Upgrade (RFC-2817) by default, see please [1] for context. The HttpServerRequest::receiveContent() never emits any value nor completes since no next / completion callbacks are called.
Closes https://github.com/reactor/reactor-netty/issues/3538

HttpServerRequest::receiveContent() never emits any value nor completes when HTTP/1.1 TLS Upgrade (RFC-2817) kicks in

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

This is a regression caused by #3481
Fixes #3548

Do not add `Transfer-Encoding` for `DELETE` with no body

---

gradle/wrapper/gradle-wrapper.properties
gradlew

` ./gradlew wrapper --gradle-version=8.12`

Bump `Gradle` to version `8.12`

---

reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java

Fix: https://github.com/reactor/reactor-netty/issues/3561

Remove unnecessary conditional statements in log

---

reactor-netty-examples/src/main/java/reactor/netty/examples/http/cors/HttpCorsServer.java

Provide a corresponding Reactor Netty version of CORS HTTP Server example as found
in Netty project.
Related to  #761

Add Reactor Netty version of `CORS` HTTP server example

---

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java

`DisposedChannel` is effective when request/response is terminated and replaces the actual channel. At that point `DisposedChannelConfig#setAutoRead` must be non operational as the inbound has already been read and the actual channel has already set auto-read to true.
The issue is also observed with the reproducible example provided by #3495
Fixes #3559

Ensure `DisposedChannelConfig#setAutoRead` does not change auto-read configuration

---

reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

Introduce a configuration option to specify the maximum number of connection pools a `ConnectionProvider` should create. Once the maximum number is exceeded, a warning message is logged.
Fixes #3318.

Configuration for setting maximum number of connection pools to be created

---

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java

`DisposedChannel` is effective when request/response is terminated and replaces the actual channel. At that point `ChannelOperations.DisposedChannel#close` must be non operational.
Fixes #3591

Make `ChannelOperations.DisposedChannel#close` non operational

---

docs/modules/ROOT/partials/proxy.adoc
reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java
reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/proxy/deferred/Application.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientProxyTest.java

The existing `proxy(...)` and `noProxy()` methods are static, applying the same configuration to all requests. In scenarios where proxy behavior needs to change dynamically based on the request (e.g., host-specific proxies, conditional proxy usage), this static approach is insufficient.
The `proxyWhen(...)` method fills this gap by allowing developers to provide a function that resolves proxy settings dynamically during request execution.
- Added support for the `proxyWhen(BiConsumer<HttpClientConfig, ? super ProxyProvider.TypeSpec>)` method to `HttpClient`.
- This method enables users to dynamically determine the proxy configuration on a per-request basis using a provided [`HttpClientConfig`](https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty …

Support for dynamic proxy configuration at the HTTP protocol level

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientWithTomcatTest.java

Ensure `HttpClient` does not add `Content-Length` header when the send function does not change `NettyOutbound` or returns `Mono#empty`

---

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java

Ensure `HttpClient` does not add `Content-Length` header when `GET/HEAD/DELETE` and the send `Publisher` does not provide content

---

.github/workflows/check_transport.yml
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java

Ensure `HttpInfos#version` returns the correct protocol when `Unix Domain Sockets`

---

reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java

When a bind operation is not expected the bind address supplier may return null.

Add `Nullability` to `NameResolverProvider.NameResolverSpec#bindAddressSupplier`

---

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java

Ensure `reactor.netty.http.server.connections.active` is updated when there is no `HttpServerOperations`

---

reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProviderH1.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProviderH2.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProviderH3.java
reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogArgProviderH1Tests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogArgProviderH2Tests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogArgProviderTests.java

Introduce `requestHeaderIterator` and `responseHeaderIterator` methods for iterating through headers in `AccessLogArgProvider` and its implementations.
Related to [#781 (comment)](https://github.com/reactor/reactor-netty/issues/781#issuecomment-2832035061)

Add request and response header iterators to `AccessLogArgProvider`

---

docs/modules/ROOT/pages/http-server.adoc
reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java
reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/errorLog/Application.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/errorLog/CustomFormatAndFilterErrorLogApplication.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/errorLog/CustomLogErrorFormatApplication.java
reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/errorLog/FilterLogErrorApplication.java
reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/AbstractErrorLogArgProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/BaseErrorLogHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/DefaultErrorLog.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/DefaultErrorLogArgProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/DefaultErrorLogHandler.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/DefaultErrorLoggingEvent.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/ErrorLog.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/ErrorLogArgProvider.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/ErrorLogFactory.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/ErrorLoggingEvent.java
reactor-netty-http/src/main/resources/META-INF/native-image/io.projectreactor.netty/reactor-netty-http/reflect-config.json
reactor-netty-http/src/test/java/reactor/netty/http/server/logging/error/ErrorLogTest.java

This PR introduces an **error logging mechanism** similar to Apache HTTPD's errorLog, addressing [#3257](https://github.com/reactor/reactor-netty/issues/3257). 
Currently, Reactor Netty does not log errors when exceptions are fired, so this update ensures that such errors are captured separately from access logs.
- Add `DefaultErrorLogHandler` handler to log error when exceptions are fired.
- The log format can be customized just like AccessLog using `ErrorLogFactory`. 
Log format customization, similar to `AccessLog`, is available using `ErrorLogFactory`.
- Filtering can also be done using `ErrorLogFactory`.
Filtering information includes `RemoteAddress`, `HttpServerInfos,` and `Throwable`.
- https://github.com/reactor/reactor-netty/issues/3257
For reference, this implementation follows …

Support error log handler for Http server

---

reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java

`MonoChannelPromise` has to be notified for any exception when selecting addresses.

Ensure the exception is propagated in case of delayed address resolution

---

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerFormDecoderProvider.java
reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerPostFormTests.java

Release the partial `HttpData` only if it is not released by Netty

---

reactor-netty-http/build.gradle
reactor-netty-http/src/http3Test/java/reactor/netty/http/server/logging/error/ErrorLogTest.java
reactor-netty-http/src/main/java/reactor/netty/http/server/logging/error/DefaultErrorLogHandler.java

`HttpServerInfos#connectionRemoteAddress()` gives the correct connection remote address for all HTTP versions.
This is important for the HTTP/3 use case.
Add tests for HTTP/3 use case.
Related to #3700

Http error log: when possible take the connection remote address from `HttpServerInfos`

---

.github/workflows/check_netty_snapshots.yml
.github/workflows/check_transport.yml

`windows-2019` runner is deprecated
https://github.com/actions/runner-images/issues/12045

Switch to `windows-2022` runner

---

.github/workflows/check_graalvm.yml
.github/workflows/check_transport.yml
build.gradle
docs/modules/ROOT/partials/eventloop.adoc
docs/modules/ROOT/partials/http-client-conn-provider.adoc
docs/modules/ROOT/partials/tcp-client-conn-provider.adoc
reactor-netty-core/build.gradle
reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopNIO.java
reactor-netty-core/src/main/java/reactor/netty/resources/LoopResources.java
reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java
reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpClient.java
reactor-netty-core/src/main/java/reactor/netty/udp/UdpServer.java
reactor-netty-core/src/main/java17/reactor/netty/resources/DefaultLoopIOUring.java
reactor-netty-core/src/test/java/reactor/netty/resources/DefaultLoopResourcesTest.java
reactor-netty-core/src/test/java/reactor/netty/udp/UdpClientTest.java
reactor-netty-graalvm-smoke-tests/build.gradle
reactor-netty-graalvm-smoke-tests/src/test/java/reactor/netty/http/HttpTests.java
reactor-netty-http/build.gradle
reactor-netty/build.gradle

IO_Uring is now part of Netty

---

reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3Tests.java
reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
reactor-netty-http/src/test/java/reactor/netty/http/Http2Tests.java
reactor-netty-http/src/test/java/reactor/netty/http/server/TrailerHeadersTests.java

https://www.rfc-editor.org/rfc/rfc9113.html#name-http-message-framing

`Trailers` must not include `pseudo-header` fields

---

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java

- Reset `maxConcurrentStreams` to `0` when invalidating a connection
- Add logging when an upgrade stream is opened

Add proper initialisation of `maxConcurrentStreams` when successful `HTTP/1.1` to `HTTP/2` upgrade

---

reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java

Small fix for the message if the handlerConfigurator is null

Fix message for `handlerConfigurator`

---

reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java

In tests both addresses are used by the clients thus both can appear as key in the connection pool.

Ensure both resolved and unresolved server bind addresses are used with `ConnectionProvider#disposeWhen`
