src/main/java/reactor/ipc/netty/channel/ClientContextHandler.java, src/main/java/reactor/ipc/netty/channel/CloseableContextHandler.java, src/main/java/reactor/ipc/netty/channel/ContextHandler.java, src/main/java/reactor/ipc/netty/channel/PooledClientContextHandler.java, src/main/java/reactor/ipc/netty/channel/ServerContextHandler.java, src/main/java/reactor/ipc/netty/http/client/HttpClient.java, src/main/java/reactor/ipc/netty/options/NettyOptions.java, src/main/java/reactor/ipc/netty/tcp/TcpClient.java, src/main/java/reactor/ipc/netty/udp/UdpClient.java, src/test/java/reactor/ipc/netty/http/HttpClientTests.java
=> fix #17 Add SNI support for all ClientContextHandlers

src/main/java/reactor/ipc/netty/ByteBufFlux.java, src/main/java/reactor/ipc/netty/ByteBufMono.java, src/main/java/reactor/ipc/netty/NettyOutbound.java, src/main/java/reactor/ipc/netty/http/Cookies.java, src/main/java/reactor/ipc/netty/http/HttpOperations.java, src/main/java/reactor/ipc/netty/http/client/HttpClient.java, src/main/java/reactor/ipc/netty/http/client/HttpClientException.java, src/main/java/reactor/ipc/netty/http/client/HttpClientOptions.java, src/main/java/reactor/ipc/netty/http/client/HttpClientRequest.java, src/main/java/reactor/ipc/netty/http/client/HttpClientResponse.java, src/main/java/reactor/ipc/netty/http/server/HttpServer.java, src/main/java/reactor/ipc/netty/http/server/HttpServerResponse.java, src/main/java/reactor/ipc/netty/http/server/HttpServerRoutes.java, src/main/java/reactor/ipc/netty/options/ClientOptions.java, src/main/java/reactor/ipc/netty/resources/LoopResources.java, src/main/java/reactor/ipc/netty/resources/PoolResources.java, src/main/java/reactor/ipc/netty/tcp/TcpClient.java, src/main/java/reactor/ipc/netty/tcp/TcpServer.java, src/main/java/reactor/ipc/netty/udp/UdpClient.java
@smaldini I had doubts on the actual behavior for some methods, and
the relevance of some sentences, for which I put TODOs in place.
=> Improve (or fix) several javadocs, use localhost:0 for TcpServer

src/main/java/reactor/ipc/netty/NettyConnector.java, src/main/java/reactor/ipc/netty/tcp/BlockingNettyContext.java, src/test/java/reactor/ipc/netty/tcp/BlockingNettyContextTest.java
=> BlockingNettyContext manages JVM shutdown hook

src/main/java/reactor/ipc/netty/udp/UdpServer.java, src/main/java/reactor/ipc/netty/udp/UdpServerOptions.java, src/test/java/reactor/ipc/netty/udp/UdpClientTest.java, src/test/java/reactor/ipc/netty/udp/UdpServerTests.java
- Rename UdpClient -> UdpServer
- Rename UdpClientOptions -> UdpOptions
- Add UdpClient
=> fix #137: Separate UdpClient/UdpServer

src/main/java/reactor/ipc/netty/http/HttpOperations.java, src/main/java/reactor/ipc/netty/http/server/HttpServerOperations.java, src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java
DO NOT COMMIT: this change depends on a PR in Netty: https://github.com/netty/netty/pull/7397 Once 4.1.18.Final is out we can remove the @Ignore marker added to the test and then commit the change.
=> Remove the special handling of status code 205

src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java, src/test/java/reactor/ipc/netty/channel/ChannelOperationsHandlerTest.java
DO NOT COMMIT: this change depends on a PR in Netty: netty/netty#7397
=> Test case for issue #196

src/main/java/reactor/ipc/netty/channel/ChannelOperations.java, src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java, src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java, src/main/java/reactor/ipc/netty/http/client/HttpClientWSOperations.java, src/test/java/reactor/ipc/netty/http/HttpErrorTests.java, src/test/java/reactor/ipc/netty/http/HttpTests.java
=> fix #237: Ensure HttpClient will emit an error when connection is

src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java, src/test/java/reactor/ipc/netty/http/server/HttpServerTests.java
There are use cases when chunks of one write operation are written
either using event loop or external thread. The implementation should
ensure that if the previous chunks are still pending then the next chunks
will be scheduled for write regardless whether in event loop or not.
=> fix #232: Ensure write chunks are always in a correct order.

src/main/java/reactor/ipc/netty/http/server/CompressionHandler.java, src/main/java/reactor/ipc/netty/http/server/FilteringHttpContentCompressor.java, src/test/java/reactor/ipc/netty/http/HttpCompressionClientServerTests.java
Reset compression threshold filter on handler terminated
Related to issue #292
=> When under compression threshold, filter also the LastHttpContent

build.gradle
- see release notes http://netty.io/news/2018/04/19/4-1-24-Final.html
=> Update Netty version to 4.1.24.Final

src/main/java/reactor/ipc/netty/http/server/HttpPredicate.java, src/main/java/reactor/ipc/netty/http/server/HttpServerRoutes.java
This is useful for handling preflight requests.
=> Add options and head to HttpServerRoutes

src/main/java/reactor/netty/http/server/HttpToH2Operations.java, src/test/java/reactor/netty/http/HttpTests.java
This is a temporary workaround for
https://github.com/netty/netty/pull/8147
Related to issue #395
=> Configure the channel auto read to true for HttpToH2Operations

src/main/java/reactor/ipc/netty/resources/DefaultPoolResources.java
Inactive connections are such that are created but not acquired
or are released to the pool. Active are such that are currently acquired.
=> Track active/inactive connections in the pool

src/main/java/reactor/netty/http/server/HttpServerOperations.java, src/main/java/reactor/netty/http/server/HttpServerResponse.java, src/main/java/reactor/netty/http/server/HttpServerRoutes.java, src/main/java/reactor/netty/http/server/WebsocketServerOperations.java, src/test/java/reactor/netty/http/client/WebsocketTest.java
Include #429 changes to HttpServer API.
cc @rstoyanchev #223
=> Allow custom websocket server maxFramePayloadLength

src/main/java/reactor/netty/http/client/UriEndpointFactory.java, src/test/java/reactor/netty/http/client/UriEndpointFactoryTest.java
Changes introduced in #228 are currently not on master. This PR cherry picks ffd10eb.
=> Handle parsing URI with query

src/main/java/reactor/netty/channel/BootstrapHandlers.java, src/main/java/reactor/netty/http/client/HttpClientConnect.java, src/main/java/reactor/netty/http/client/HttpClientSecure.java, src/main/java/reactor/netty/http/server/HttpServerSecure.java, src/main/java/reactor/netty/resources/PooledConnectionProvider.java, src/main/java/reactor/netty/tcp/ProxyProvider.java, src/main/java/reactor/netty/tcp/SslProvider.java, src/main/java/reactor/netty/tcp/TcpClient.java, src/main/java/reactor/netty/tcp/TcpServer.java, src/main/java/reactor/netty/tcp/TcpServerSecure.java, src/main/java/reactor/netty/tcp/TcpUtils.java, src/test/java/reactor/netty/http/client/HttpClientTest.java, src/test/java/reactor/netty/resources/PooledConnectionProviderTest.java, src/test/java/reactor/netty/tcp/TcpServerTests.java
Take into account SSL, Proxy, Logging, Compression and Protocol
when generating the pooled connection key
=> fix #407 Put more information into the key for pooled connections

src/main/java/reactor/ipc/netty/channel/ContextHandler.java, src/main/java/reactor/ipc/netty/channel/PooledClientContextHandler.java, src/main/java/reactor/ipc/netty/http/client/HttpClient.java, src/main/java/reactor/ipc/netty/http/server/HttpPredicate.java, src/main/java/reactor/ipc/netty/tcp/TcpClient.java, src/test/java/reactor/ipc/netty/http/server/UriPathTemplateTest.java
An out of order issue is causing client http request to be sent before SSL handshake terminates
=> Fix Out of Order handling with pool acquisition

src/main/java/reactor/ipc/netty/resources/DefaultLoopResources.java, src/test/java/reactor/ipc/netty/resources/DefaultLoopResourcesTest.java, src/test/java/reactor/ipc/netty/udp/UdpClientTest.java
Create NIO server/client loops only when there is no natives
=> Lazy initialisation for NIO server/client loops

src/main/java/reactor/ipc/netty/channel/ChannelOperationsHandler.java
This reverts commit 43d52617c743ee6e7e1395880fa7b1c3794fef01.
=> Revert "When it is the last drained element do not schedule the flush operation"

src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java
=> Use FutureMono#disposableWriteAndFlush instead of sendObject

src/main/java/reactor/netty/http/client/HttpClientConnect.java, src/main/java/reactor/netty/tcp/ProxyProvider.java, src/main/java/reactor/netty/tcp/TcpUtils.java, src/test/java/reactor/netty/http/client/HttpClientProxyTest.java
Convert the Proxy support to a deferred one in order to cover use case
when there is no address provided with HttpClient configuration, but
only uri is provided.
=> fix #523 NonProxyHost is not applied when only uri is supplied

src/main/java/reactor/netty/http/server/HttpServerHandle.java, src/main/java/reactor/netty/http/server/HttpServerOperations.java, src/main/java/reactor/netty/http/server/HttpServerState.java, src/main/java/reactor/netty/http/server/HttpToH2Operations.java, src/test/java/reactor/netty/http/server/HttpServerTests.java
Differentiate the state CONFIGURED when handlers can be
added to the pipeline from the state APPLYING_HANDLER
when the actual I/O handler will be applied.
=> Introduce a new HttpServer state: applying I/O handler

src/main/java/reactor/netty/http/server/ConnectionInfo.java, src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Simply removed an else to support X-Forwarded-Host and X-Forwarded-For
for the same request.
Thx @clement-buchart for the spot.
=> Support X-Forwarded-Host AND X-Forwarded-For

src/main/java/reactor/netty/tcp/ProxyProvider.java, src/test/java/reactor/netty/tcp/ProxyProviderTest.java
=> Eagly calculate address and password in ProxyProvider equals and hashcode

src/main/java/reactor/netty/http/client/HttpClientConnect.java, src/main/java/reactor/netty/http/client/HttpClientOperations.java, src/test/java/reactor/netty/http/client/HttpRedirectTest.java
returns correct number of redirections
=> fix #606 Ensure HttpClientRequest / HttpClientResponse#redirectedFrom 

src/main/java/reactor/netty/http/client/HttpClientOperations.java
=> Do not create aggregated ByteBuf when publisher empty or first element empty

src/main/java/reactor/ipc/netty/http/HttpOperations.java, src/main/java/reactor/ipc/netty/http/client/HttpClientOperations.java, src/main/java/reactor/ipc/netty/http/server/HttpServerOperations.java, src/test/java/reactor/ipc/netty/http/client/HttpClientTest.java
=> Handle Connection header with a comma separated list as value

src/docs/asciidoc/about-doc.adoc, src/docs/asciidoc/getting-started.adoc, src/docs/asciidoc/http-client.adoc, src/docs/asciidoc/http-server.adoc, src/docs/asciidoc/tcp-client.adoc, src/docs/asciidoc/tcp-server.adoc, src/docs/asciidoc/udp-client.adoc, src/docs/asciidoc/udp-server.adoc
I edited for spelling, punctuation, grammar, usage, and corporte voice. I also added leader paragraphs in places that didn't have them.
=> Editing pass for the Reactor Netty Reference Guide

src/main/java/reactor/netty/resources/PooledConnectionProvider.java, src/test/java/reactor/netty/resources/PooledConnectionProviderTest.java
When `FixedChannelPool` is in use and there is `TimeoutException` or
`IllegalStateException` when acquiring a channel then `inactiveConnections`
should not be decremented as there won't be a channel creation.
=> fix #673 Ensure PooledConnectionProvider.Pool#inactiveConnections is correct when TimeoutException

src/main/java/reactor/netty/http/server/HttpPredicate.java
See
https://github.com/spring-projects/spring-framework/blob/v5.1.6.RELEASE/spring-web/src/main/java/org/springframework/web/util/UriTemplate.java
=> Use an adaptation of Spring Framework UriTemplate for resolving path params

build.gradle
=> Declare an Java9 JPMS Automatic-Module-Name for netty

src/main/java/reactor/netty/http/client/HttpClient.java
Resolves https://github.com/reactor/reactor-netty/issues/816.
=> Fix Javadoc of HttpClient.followRedirect

src/main/java/reactor/netty/Metrics.java, src/main/java/reactor/netty/channel/BootstrapHandlers.java, src/main/java/reactor/netty/channel/ChannelMetricsHandler.java, src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java, src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java, src/main/java/reactor/netty/resources/PooledConnectionProvider.java, src/main/java/reactor/netty/resources/PooledConnectionProviderMetrics.java, src/test/java/reactor/netty/resources/PooledConnectionProviderMetricsTest.java
=> Add metrics for the connection pool

src/main/java/reactor/netty/resources/PooledConnectionProvider.java
We are using `reactor-netty 0.7.15.RELEASE` (netty version is 4.1.39.Final) , and recently we found that server may be get blocked. so we use `jstack` to analyze it, the following info show the problem:
```
"reactor-http-epoll-4" #120 daemon prio=5 os_prio=0 tid=0x00007f5f903d8800 nid=0x175a in Object.wait() [0x00007f5f37319000]
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:218)
- locked <0x00000000c834c238> (a io.netty.util.concurrent.DefaultPromise)
at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:32)
at io.netty.channel.pool.FixedChannelPool.close(FixedChannelPool.java:446)
at …
```
=> Avoid calling `Pool.close()` which may block reactor thread permanently.

src/main/java/reactor/netty/channel/BootstrapHandlers.java, src/main/java/reactor/netty/channel/ByteBufAllocatorMetrics.java, src/test/java/reactor/netty/channel/ByteBufAllocatorMetricsTest.java
=> Add metrics for the ByteBufAllocator

src/main/java/reactor/netty/channel/AddressResolverGroupMetrics.java, src/main/java/reactor/netty/channel/BootstrapHandlers.java, src/test/java/reactor/netty/channel/AddressResolverGroupMetricsTest.java
=> Add metrics for the AddressResolver

src/main/java/reactor/netty/Metrics.java, src/main/java/reactor/netty/channel/AddressResolverGroupMetrics.java, src/main/java/reactor/netty/channel/BootstrapHandlers.java, src/main/java/reactor/netty/channel/ChannelMetricsHandler.java, src/main/java/reactor/netty/channel/ChannelMetricsRecorder.java, src/main/java/reactor/netty/channel/MicrometerChannelMetricsRecorder.java, src/main/java/reactor/netty/http/HttpMetricsRecorder.java, src/main/java/reactor/netty/http/MicrometerHttpMetricsRecorder.java, src/main/java/reactor/netty/http/client/HttpClient.java, src/main/java/reactor/netty/http/client/HttpClientConnect.java, src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java, src/main/java/reactor/netty/http/client/HttpClientMetricsRecorder.java, src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java, src/main/java/reactor/netty/http/server/HttpServer.java, src/main/java/reactor/netty/http/server/HttpServerBind.java, src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java, src/main/java/reactor/netty/http/server/HttpServerMetricsRecorder.java, src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsRecorder.java, src/main/java/reactor/netty/tcp/TcpClient.java, src/main/java/reactor/netty/tcp/TcpServer.java, src/main/java/reactor/netty/udp/UdpClient.java, src/main/java/reactor/netty/udp/UdpServer.java, src/test/java/reactor/netty/channel/AddressResolverGroupMetricsTest.java, src/test/java/reactor/netty/channel/ByteBufAllocatorMetricsTest.java, src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java, src/test/java/reactor/netty/resources/PooledConnectionProviderMetricsTest.java, src/test/java/reactor/netty/tcp/TcpMetricsTests.java, src/test/java/reactor/netty/tcp/TcpSecureMetricsTests.java, src/test/java/reactor/netty/udp/UdpMetricsTests.java
Add HttpServer#metrics(boolean, HttpServerMetricsRecorder)
Add HttpClient#metrics(boolean, HttpClientMetricsRecorder)
Related to #798
=> Add TCP/UDP client/server #metrics(boolean, ChannelMetricsRecorder)

src/main/java/reactor/netty/http/HttpOperations.java
Test case HttpCompressionClientServerTests#testIssue825_2
=> Release the message when the compressionPredicate throws RuntimeException

src/main/java/reactor/netty/http/HttpOperations.java, src/test/java/reactor/netty/http/server/HttpServerTests.java
Release the message when the compressionPredicate throws RuntimeException
Additional fixes to #892
=> Ensure content will not be sent over the network when Content-Length:0 is specified

src/main/java/reactor/netty/channel/AddressResolverGroupMetrics.java, src/main/java/reactor/netty/channel/ChannelMetricsHandler.java, src/main/java/reactor/netty/channel/ChannelMetricsRecorder.java, src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java, src/main/java/reactor/netty/http/client/HttpClientMetricsRecorder.java, src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java, src/main/java/reactor/netty/http/server/HttpServerMetricsRecorder.java, src/test/java/reactor/netty/channel/AddressResolverGroupMetricsTest.java, src/test/java/reactor/netty/channel/ByteBufAllocatorMetricsTest.java, src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java, src/test/java/reactor/netty/http/HttpsMetricsHandlerTests.java, src/test/java/reactor/netty/tcp/TcpMetricsTests.java, src/test/java/reactor/netty/tcp/TcpSecureMetricsTests.java, src/test/java/reactor/netty/udp/UdpMetricsTests.java
`nanoTime` will be used instead of `currentTimeMillis`
=> Use nanoTime for the timers

src/main/java/reactor/netty/http/server/ConnectionInfo.java, src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
Obtain the headers once and not contains+get
=> fix #941 Fix NumberFormatException when X-Forwarded-Port is non numeric

src/main/java/reactor/netty/http/HttpInfos.java, src/main/java/reactor/netty/http/HttpOperations.java, src/test/java/reactor/netty/http/HttpOperationsTest.java
=> fix #948 Fix IllegalArgumentException while resolving the path

src/main/java/reactor/netty/http/client/HttpClient.java, src/main/java/reactor/netty/http/client/HttpClientDoOn.java, src/main/java/reactor/netty/http/client/HttpClientOperations.java, src/main/java/reactor/netty/http/client/HttpClientState.java, src/test/java/reactor/netty/http/client/HttpClientTest.java
=> fix #975 Add HttpClient.doAfterResponseSuccess that will be triggered only when the response is fully received

src/test/java/reactor/netty/http/client/HttpClientTest.java, src/test/java/reactor/netty/http/client/PostAndGetTests.java
See https://github.com/spring-cloud/spring-cloud-sleuth/pull/1554
=> Adds failing test for POST request parsing

src/main/java/reactor/netty/http/server/HttpServer.java, src/main/java/reactor/netty/http/server/HttpServerOperations.java, src/main/java/reactor/netty/http/server/HttpServerResponse.java, src/main/java/reactor/netty/http/server/HttpServerRoutes.java, src/main/java/reactor/netty/http/server/WebsocketServerOperations.java, src/main/java/reactor/netty/http/server/WebsocketServerSpec.java, src/main/java/reactor/netty/http/server/WebsocketServerSpecImpl.java, src/main/java/reactor/netty/http/websocket/WebsocketSpec.java, src/main/java/reactor/netty/http/websocket/WebsocketSpecImpl.java, src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java, src/test/java/reactor/netty/http/client/WebsocketTest.java
Websocket server/client configurations can differ.
=> Add separate builder for Websocket server configuration

src/main/java/reactor/netty/ReactorNetty.java, src/main/java/reactor/netty/resources/ConnectionProvider.java
=> Add System properties for connection pool - max idle time and leasing strategy

src/main/java/reactor/netty/resources/PooledConnectionProvider.java
Eviction predicate is not invoked on PooledRef#release, but only on #acquire.
Ensure the channels that are not persistent will be closed when DISCONNECTING
For channels that are closed there is no need to invoke #release as for them #invalidate
will be invoked.
=> Ensure the channels that are not persistent will be closed when DISCONNECTING

src/main/java/reactor/netty/http/client/HttpClient.java, src/main/java/reactor/netty/http/client/HttpClientDoOn.java
Related to #1000
Tested with #1000
=> Add HttpClient#doOnRedirect callback that will be invoked when the request is about to be redirected

src/main/java/reactor/netty/http/HttpInfos.java, src/main/java/reactor/netty/http/HttpOperations.java, src/main/java/reactor/netty/http/client/HttpClientDoOnError.java, src/main/java/reactor/netty/http/client/HttpClientMetricsHandler.java, src/main/java/reactor/netty/http/client/HttpClientOperations.java, src/main/java/reactor/netty/http/server/HttpServerMetricsHandler.java, src/main/java/reactor/netty/http/server/HttpServerOperations.java, src/test/java/reactor/netty/http/HttpOperationsTest.java
=> fix #999 Add HttpInfos#fullPath for not removing leading/trailing '/' symbol

src/main/java/reactor/netty/http/client/HttpClientOperations.java, src/main/java/reactor/netty/http/client/WebsocketClientOperations.java, src/test/java/reactor/netty/http/client/HttpClientOperationsTest.java, src/test/java/reactor/netty/http/client/HttpRedirectTest.java, src/test/java/reactor/netty/resources/PooledConnectionProviderTest.java
=> fix #1027 Ensure the connection is returned to the pool when follow redirect is enabled

src/main/java/reactor/netty/http/client/HttpClient.java, src/main/java/reactor/netty/http/client/HttpClientConfiguration.java, src/main/java/reactor/netty/http/client/HttpClientConnect.java, src/main/java/reactor/netty/http/client/HttpClientDoOnError.java, src/main/java/reactor/netty/http/client/HttpClientOperations.java, src/test/java/reactor/netty/http/client/HttpClientOperationsTest.java, src/test/java/reactor/netty/http/client/HttpClientTest.java
=> fix #995 Add API for disabling retry support for HTTP client

src/main/java/reactor/netty/http/server/HttpServer.java, src/main/java/reactor/netty/http/server/HttpServerBind.java, src/main/java/reactor/netty/http/server/HttpServerChannelGroup.java, src/main/java/reactor/netty/http/server/HttpServerConfiguration.java, src/test/java/reactor/netty/http/server/HttpServerTests.java
=> fix #1022 Add support for graceful shutdown

src/main/java/reactor/netty/channel/FluxReceive.java
=> When reading the incoming data enable auto-read when the queue is empty

src/main/java/reactor/netty/http/server/HttpServer.java, src/main/java/reactor/netty/http/server/HttpServerBind.java, src/main/java/reactor/netty/http/server/HttpServerConfiguration.java, src/main/java/reactor/netty/tcp/TcpServer.java, src/main/java/reactor/netty/tcp/TcpServerBind.java, src/main/java/reactor/netty/tcp/TcpServerChannelGroup.java, src/test/java/reactor/netty/http/server/HttpServerTests.java, src/test/java/reactor/netty/tcp/TcpServerTests.java
=> fix #1042 Add support for graceful shutdown for TcpServer

src/main/java/reactor/netty/http/server/HttpServer.java, src/main/java/reactor/netty/tcp/TcpServer.java, src/test/java/reactor/netty/http/server/HttpServerTests.java, src/test/java/reactor/netty/tcp/TcpServerTests.java
=> Polishing graceful shutdown

src/main/java/reactor/netty/channel/FluxReceive.java, src/test/java/reactor/netty/http/HttpTests.java
=> fix #1050 Ensure receiverFastPath is enabled before enabling auto-read option

src/main/java/reactor/netty/channel/ChannelOperations.java, src/main/java/reactor/netty/http/client/HttpClientOperations.java, src/test/java/reactor/netty/http/client/HttpClientTest.java
Related to https://github.com/spring-projects/spring-framework/issues/24846
=> Ensure HttpClient#doAfterResponseSuccess is sent after the inbound is completed

src/main/java/reactor/netty/channel/FluxReceive.java, src/test/java/reactor/netty/channel/FluxReceiveTest.java
=> fix #1016 Ensure the exception is propagated

src/main/java/reactor/netty/http/client/HttpClient.java, src/main/java/reactor/netty/http/client/HttpClientConfiguration.java, src/main/java/reactor/netty/http/client/HttpClientConnect.java, src/main/java/reactor/netty/http/client/HttpClientDoOnError.java, src/main/java/reactor/netty/http/client/HttpClientOperations.java, src/main/java/reactor/netty/http/client/WebsocketClientOperations.java, src/main/java/reactor/netty/http/client/WebsocketClientSpec.java, src/main/java/reactor/netty/http/client/WebsocketClientSpecImpl.java, src/test/java/reactor/netty/http/client/WebsocketClientOperationsTest.java, src/test/java/reactor/netty/http/client/WebsocketTest.java
=> fix #935 Add separate builder for Websocket client configuration

src/main/java/reactor/netty/resources/DefaultLoopEpoll.java, src/main/java/reactor/netty/resources/DefaultLoopKQueue.java, src/main/java/reactor/netty/resources/LoopResources.java, src/main/java/reactor/netty/resources/PooledConnectionProvider.java, src/main/java/reactor/netty/tcp/TcpResources.java, src/main/java/reactor/netty/transport/AddressUtils.java, src/main/java/reactor/netty/transport/ClientTransportConfig.java, src/main/java/reactor/netty/transport/ServerTransport.java, src/main/java/reactor/netty/transport/ServerTransportConfig.java, src/main/java/reactor/netty/transport/TransportConfig.java, src/main/java/reactor/netty/transport/TransportConnector.java, src/main/java/reactor/netty/udp/UdpClientConfig.java, src/main/java/reactor/netty/udp/UdpResources.java, src/main/java/reactor/netty/udp/UdpServerConfig.java, src/test/java/reactor/netty/resources/PooledConnectionProviderTest.java, src/test/java/reactor/netty/tcp/BlockingConnectionTest.java, src/test/java/reactor/netty/tcp/TcpClientTests.java, src/test/java/reactor/netty/tcp/TcpServerTests.java, src/test/java/reactor/netty/udp/UdpClientTest.java, src/test/java/reactor/netty/udp/UdpServerTests.java
Covers TCP transport
Related to #403
=> Add UDS support

src/main/java/reactor/netty/ReactorNetty.java, src/test/java/reactor/netty/ConnectionTest.java
Add tests for sender/receiver unavailable.
=> Fix exception message

src/main/java/reactor/netty/http/client/HttpClient.java, src/main/java/reactor/netty/http/client/HttpClientConfiguration.java, src/main/java/reactor/netty/http/client/HttpClientConnect.java, src/main/java/reactor/netty/http/client/HttpClientDoOnError.java, src/main/java/reactor/netty/http/client/HttpClientFinalizer.java, src/main/java/reactor/netty/http/client/UriEndpointFactory.java, src/main/java/reactor/netty/http/client/WebsocketFinalizer.java, src/test/java/reactor/netty/http/client/HttpClientTest.java, src/test/java/reactor/netty/http/client/UriEndpointFactoryTest.java
=> fix #1133 Add new API HttpClient#uri(URI)

src/main/java/reactor/netty/http/server/HttpServerOperations.java, src/test/java/reactor/netty/http/server/HttpServerTests.java
=> fix #1153 Ensure only Content-Length is set when creating full response

src/main/java/reactor/netty/http/server/HttpServerOperations.java
Related to https://github.com/reactor/reactor-core/issues/2279
=> Adapt to the changed API in reactor core

src/docs/asciidoc/getting-started.adoc
=> fix #1223 Update `how to use BOM with gradle` section in the reference documentation

build.gradle, gradle/wrapper/gradle-wrapper.properties, reactor-netty-core/build.gradle
Do not publish gradle metadata
Do not publish test fixtures
=> Upgrade gradle to 6.5.1

reactor-netty-core/src/main/java/reactor/netty/DisposableChannel.java, reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java, reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java, reactor-netty-core/src/main/java/reactor/netty/udp/UdpServer.java, reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java, reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java, reactor-netty-core/src/test/java/reactor/netty/transport/ServerTransportTest.java, reactor-netty-core/src/test/java/reactor/netty/udp/UdpServerTests.java
=> fix #1233 Ensure bindNow/connectNow/disposeNow does not swallow ArithmeticException

reactor-netty-core/src/test/java/reactor/netty/channel/MonoSendManyTest.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientFormEncoder.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpTests.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java, reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Adapt to the Processor changes
Adapt to the Context changes
=> Adapt to Reactor Core changes

reactor-netty-core/build.gradle, reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientConfig.java, reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java, reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java, reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java, reactor-netty-core/src/main/java/reactor/netty/udp/UdpClientConfig.java, reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java, reactor-netty-core/src/test/java/reactor/netty/resources/PooledConnectionProviderCustomMetricsTest.java, reactor-netty-core/src/test/java/reactor/netty/tcp/BlockingConnectionTest.java, reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java, reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java, reactor-netty-http/build.gradle, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
Related to #501, #538, #569, #710
=> Switch to Netty DNS resolver

reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java, reactor-netty-core/src/test/java/reactor/netty/transport/TransportTest.java
=> UdpServer.wiretap(String category, LogLevel level) the log level is always debug

.github/ISSUE_TEMPLATE/bug_report.md
This PR polishes the issue template for bug reports.
=> Polish issue template for bug report

reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java, reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java, reactor-netty-core/src/main/java/reactor/netty/tcp/TcpServerConfig.java, reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerBind.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java, reactor-netty-http/src/test/java/reactor/netty/tcp/SslProviderTests.java
=> fix #573 Add server SNI support

reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java, reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
=> Create the SSL LoggingHandler once and reuse it as it is sharable

src/docs/asciidoc/http-server.adoc, src/main/java/reactor/netty/http/server/ConnectionInfo.java, src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java, src/main/java/reactor/netty/http/server/Http2StreamBridgeHandler.java, src/main/java/reactor/netty/http/server/HttpServer.java, src/main/java/reactor/netty/http/server/HttpServerBind.java, src/main/java/reactor/netty/http/server/HttpServerConfiguration.java, src/main/java/reactor/netty/http/server/HttpTrafficHandler.java, src/main/java/reactor/netty/tcp/InetSocketAddressUtil.java, src/test/java/reactor/netty/http/server/ConnectionInfoTests.java, src/test/java/reactor/netty/tcp/InetSocketAddressUtilTest.java
Closes #990
Backporting #1282 to the 0.9.x
=> backport PR #1282

src/main/java/reactor/netty/tcp/TcpServerBind.java
=> fix #1235 Use log level DEBUG when DecoderException and no bound ChannelOperations

build.gradle, reactor-netty-http-brave/build.gradle, reactor-netty-http-brave/src/main/java/reactor/netty/http/server/BraveHttpServerTracing.java, reactor-netty-http-brave/src/main/java/reactor/netty/http/server/TracingContext.java, reactor-netty-http-brave/src/test/java/reactor/netty/http/server/ITBraveHttpServerTracingTest.java, reactor-netty-http-brave/src/test/resources/logback.xml, reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerState.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
=> Add Brave instrumentation for HttpServer

reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/ReactorNettyHttpTracing.java, reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/TracingHttpClientDecorator.java, reactor-netty-http-brave/src/test/java/reactor/netty/http/client/ITTracingHttpClientDecoratorTest.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java
=> Add Brave instrumentation for HttpClient

reactor-netty-http/src/main/java/reactor/netty/http/Http2SettingsSpec.java, reactor-netty-http/src/test/java/reactor/netty/http/Http2SettingsSpecTests.java
This is not supported at the moment
=> Disable pushEnabled setting

reactor-netty-core/src/test/java/reactor/netty/ConnectionObserverContextTest.java
This PR tests https://github.com/reactor/reactor-pool/issues/103
Related to #1327
=> Test that Reactor Pool propagates the Context

build.gradle, gradle/errorprone.gradle, reactor-netty-core/src/main/java/reactor/netty/DisposableChannel.java, reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java, reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/LoopResources.java, reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java, reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
=> fix #350 Fix the warnings produced by errorprone compiler plugin

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java, reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
=> Support data frames decompression/compression for HttpClient/HttpServer with HTTP/2 enabled

build.gradle, reactor-netty-core/build.gradle, reactor-netty-core/src/test/java/reactor/netty/BlockHoundIntegrationTest.java, reactor-netty-core/src/test/java/reactor/netty/CustomBlockHoundIntegration.java, reactor-netty-core/src/test/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration, reactor-netty-http/build.gradle, reactor-netty-http/src/test/java/reactor/netty/CustomBlockHoundIntegration.java, reactor-netty-http/src/test/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration
=> [tests] Enable BlockHound in tests

docs/asciidoc/http-client.adoc, docs/asciidoc/tcp-client.adoc, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/resolver/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/resolver/custom/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/resolver/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/resolver/custom/Application.java
=> fix #1431 Add DNS resolver examples to the reference documentation

build.gradle, reactor-netty-core/src/test/java/reactor/netty/resources/DefaultLoopResourcesTest.java
Related to https://github.com/netty/netty/issues/10926
=> [tests] Ensure the native transport is available when running with -PforceTransport=native

reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java
=> [tests] Test various HttpClient configurations that may affect the creation of the connection pool

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpTests.java
When there is `Expect: 100-continue` in the client request, at first the server will respond
eventually with `100 (Continue)` response. The server will return the final status code,
once the message body is received and processed.
When creating `HttpClientResponse`, Reactor Netty should wait for that final response.
https://tools.ietf.org/html/rfc7231#section-5.1.1
```
A server that sends a 100 (Continue) response MUST ultimately send
a final status code, once the message body is received and
processed, unless the connection is closed prematurely.
```
According to the specification it is not mandatory for the client to wait for `100 (Continue)` response in order to send the data.
https://tools.ietf.org/html/rfc7231#section-5.1.1
```
Requirements for clients:
...
A client that sends a …
```
=> fix #1482 Ensure the correct HttpClientResponse is created when client request with `Expect: 100-continue`

reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
=> [test] Test that the server selector channel is closed when the server is disposed.

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java
=> Add pending acquire requests to the pool state debug info

reactor-netty-core/src/main/java/reactor/netty/ChannelOperationsId.java, reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java, reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java, reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java, reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClientConfig.java, reactor-netty-core/src/main/java/reactor/netty/tcp/TcpServerConfig.java, reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java, reactor-netty-core/src/main/java/reactor/netty/transport/logging/AdvancedByteBufFormat.java, reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java, reactor-netty-core/src/main/java/reactor/netty/udp/UdpClientConfig.java, reactor-netty-core/src/main/java/reactor/netty/udp/UdpServerConfig.java, reactor-netty-core/src/test/java/reactor/netty/ChannelOperationsIdTest.java, reactor-netty-core/src/test/java/reactor/netty/transport/TransportTest.java, reactor-netty-http/src/main/java/reactor/netty/http/HttpInfos.java, reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/client/FailedHttpClientRequest.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpOperationsTest.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpTests.java
Request ID is a combination of the id of the underlying connection
and the serial number of the request received on that connection.
=> Add API for obtaining request ID

reactor-netty-core/src/main/java/reactor/netty/transport/AddressResolverGroupMetrics.java, reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransportConfig.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
=> Cache AddressResolverGroupMetrics per resolverGroup and recorder

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
=> Add pending acquire requests to the HTTP/2 pool state debug info

reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/TracingHttpServerDecorator.java, reactor-netty-http-brave/src/test/java/reactor/netty/http/brave/ITTracingHttpServerDecoratorTest.java
Related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1690
=> Ensure the custom Netty handlers are able to access tracing information

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java, reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java
=> Ensure uriTagValue metrics function is not shared amongst the clients

reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpOperationsTest.java
=> Remove the query and the fragment from the uri when decoding the path

reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
=> Add test that verifies that a custom User-Agent header is preserved

reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AbstractAccessLogArgProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogArgProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java, reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH2.java, reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogArgProviderTests.java, reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogTest.java
=> Expose a new API AccessLogArgProvider#cookies for obtaining cookies information

reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java, reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
=> Ensure the channel is recreated when retrying the connect operation

reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
The exception message is changed with
https://github.com/netty/netty/pull/11172
=> [test] Relax the test check

build.gradle, gradle.properties, reactor-netty-core/build.gradle, reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java, reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
=> Add a new API for disposing in background the inactive connection pools

src/main/java/reactor/netty/http/client/HttpClientConnect.java, src/test/java/reactor/netty/http/client/HttpClientTest.java
=> Do not retry the request when the headers/body were sent.

reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
=> Add system property for disabling strict Forwarded header validation

docs/asciidoc/conn-provider.adoc, docs/asciidoc/http-client.adoc, docs/asciidoc/tcp-client.adoc, reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java, reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/pool/config/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/pool/metrics/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/pool/config/Application.java
=> Extend the connection pool documentation

reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/TracingChannelOutboundHandler.java
Related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1957
=> Ensure TraceContext is available when executing the flush operation

reactor-netty-core/src/main/java/reactor/netty/transport/ClientTransport.java, reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java
=> Ensure custom AddressResolverGroup is preserved when changing LoopResources and there is no NameResolverProvider

reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
Handlers added with `doOnConnected` callback are available on every request regardless
whether the connection is newly connected or acquired.
Related to #571
=> [test] Handlers added with doOnConnected callback are available on every request

gradle/setup.gradle
=> [polish] Update pom dev list

reactor-netty-core/src/main/java/reactor/netty/resources/ColocatedEventLoopGroup.java, reactor-netty-http/src/test/java/reactor/netty/resources/ColocatedEventLoopGroupTest.java
=> When initialising ColocatedEventLoopGroup and in an event loop there is no need to submit a task

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
=> Ensure responseTimeout can be reset

codequality/checkstyle.xml, gradle/errorprone.gradle, gradle/javadoc.gradle, gradle/releaser.gradle
=> [chores] reactor netty root: recompute copyright notice range from git history

reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java
=> Add the missing deprecated tag

reactor-netty-http-brave/src/main/java/reactor/netty/http/brave/TracingHttpClientDecorator.java, reactor-netty-http-brave/src/test/java/reactor/netty/http/brave/ITTracingHttpClientDecoratorTest.java
=> Fix ClassCastException when cleaning the channel attributes

docs/asciidoc/getting-started.adoc, gradle.properties, gradle/asciidoc.gradle
=> [documentation] BOM snippets use version from gradle.properties

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
=> fix #1792 change log level from debug to warn

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
=> Obtain the pool owner just before the invalidate invocation

reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java, reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java, reactor-netty-http/src/test/java/reactor/netty/http/client/ConnectionPoolTests.java
=> When calculating the pool hash take into account LoggingHandler configuration

reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java, reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java, reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java
QUIC channel id is prepended with trace id
`(0d764edf1d7fbf6651fdedc08ed44c69efbaeee1)[id: 5dc8071b] Created a new QUIC channel`
=> Add handling for QUIC channel id

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientResponse.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerResponse.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java, reactor-netty-http/src/test/java/reactor/netty/http/server/TrailerHeadersTests.java, reactor-netty-http/src/test/java/reactor/netty/http/server/TrailingHeadersTests.java
=> Support sending trailer headers on the server and receiving such on the client

gradle/errorprone.gradle, reactor-netty-core/src/main/java/reactor/netty/ByteBufFlux.java, reactor-netty-core/src/main/java/reactor/netty/resources/ColocatedEventLoopGroup.java, reactor-netty-core/src/main/java/reactor/netty/tcp/TcpClient.java, reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
Fix/suppress the reported warnings
=> Update errorprone gradle plugin version to 2.0.2

build.gradle, reactor-netty-incubator-quic/build.gradle
The artifact id has been changed since version `0.0.21.Final`
=> Update Netty QUIC Codec to v0.0.23.Final

build.gradle, reactor-netty-core/build.gradle, reactor-netty-http/build.gradle
As discussed this morning, please review this PR for adding support for macos M1 arch (osx-aarch_64).
thanks.
=> Add support for Macos M1 architecture

docs/asciidoc/http-client.adoc, docs/asciidoc/http-server.adoc, docs/asciidoc/tcp-client.adoc, docs/asciidoc/tcp-server.adoc, docs/asciidoc/udp-client.adoc, docs/asciidoc/udp-server.adoc, docs/asciidoc/wire-logger.adoc
Add examples for the different wire logger formats
=> [documentation] Extract wire logger documentation is a separate file

docs/asciidoc/http-client.adoc, reactor-netty-core/src/main/java/reactor/netty/Metrics.java, reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttp2ConnectionProviderMeterRegistrar.java, reactor-netty-http/src/noMicrometerTest/java/reactor/netty/http/client/HttpClientNoMicrometerTest.java, reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
=> Expose metrics for the number of the active HTTP/2 streams

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpConnectionProvider.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpConnectionProviderTest.java
=> Ensure HttpConnectionProvider exposes correct maxConnections/maxConnectionsPerHost information

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
=> HttpServerOperations#isFormUrlencoded handles header value with charset

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
=> Ensure the correct Context is provided to ContextAwareHttpServerMetricsRecorder

reactor-netty-core/build.gradle, reactor-netty-core/src/test/java/reactor/netty/tcp/TcpMetricsTests.java, reactor-netty-core/src/test/java/reactor/netty/udp/UdpMetricsTests.java, reactor-netty-http/build.gradle, reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java, reactor-netty-http/src/test/java/reactor/netty/transport/AddressResolverGroupMetricsTest.java
=> Use MeterRegistryAssert for checking Timers existence

gradle.properties
Update Reactor Addons version to 3.5.0-SNAPSHOT
Update Reactor Pool version to 1.0.0-SNAPSHOT
=> Update Reactor Core version to 3.5.0-SNAPSHOT

reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java, reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java, reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
Caching is implemented with #2057
=> Remove TODOs related to caching Timers

gradle/wrapper/gradle-wrapper.properties
`./gradlew wrapper --gradle-version=7.4.1`
=> Upgrade to Gradle v7.4.1

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java
Ensure `PooledRef` is invalidated in the cases when a stream cannot be opened.
```
java.lang.NullPointerException: Cannot invoke "io.netty.handler.codec.http2.Http2FrameCodec.connection()" because "frameCodec" is null
at reactor.netty.http.client.Http2ConnectionProvider$DisposableAcquire.operationComplete(Http2ConnectionProvider.java:320)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at …
```
=> Ensure all cases, when Http2FrameCodec is not available, are handled properly

build.gradle
Update Micrometer Tracing dependency to version 1.0.0-M3
Update Micrometer Docs Generator dependency to version 1.0.0-M2
=> Update Micrometer dependency to version 2.0.0-M3

build.gradle, reactor-netty-core/build.gradle, reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java, reactor-netty-core/src/main/java/reactor/netty/observability/contextpropagation/propagator/ChannelContextContainerPropagator.java, reactor-netty-core/src/main/java/reactor/netty/observability/contextpropagation/propagator/ReactorContextContainerPropagator.java, reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java, reactor-netty-core/src/main/resources/META-INF/services/io.micrometer.contextpropagation.ContextContainerPropagator, reactor-netty-http/build.gradle, reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java, reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java, reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Co-authored-by: Marcin Grzejszczak <mgrzejszczak@vmware.com>
=> Added context propagation from caller thread/reactor context

build.gradle, reactor-netty-http/src/test/java/reactor/netty/CustomBlockHoundIntegration.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
This PR is an attempt to reduce metrics related test execution time.
For the moment it's just experimental, to see if CI tests are passing OK.
=> Make metric tests faster

gradle/wrapper/gradle-wrapper.properties
`./gradlew wrapper --gradle-version=7.4.2`
=> Upgrade to Gradle v7.4.2

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java
=> Do not return the connection to the pool in case SSLEngine has been closed

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
=> Ensure 4xx responses are reported by HttpServer metrics

reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java, reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java, reactor-netty-http/src/test/java/reactor/netty/tcp/SslProviderTests.java
=> Add API for providing SNI AsyncMapping

.github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> Configure dependabot to update GitHub Actions versions

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerBind.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
=> Removed unused methods

reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java, reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMetricsHandler.java, reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java, reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java, reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java, reactor-netty-core/src/test/java/reactor/netty/tcp/TcpMetricsTests.java, reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpTrafficHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HAProxyMessageReader.java, reactor-netty-http/src/main/java/reactor/netty/http/server/NonSslRedirectHandler.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
=> Move from ChannelInboundHandlerAdapter to ChannelHandlerAdapter

reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2StreamBridgeClientHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java, reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH2.java, reactor-netty-http/src/main/java/reactor/netty/http/server/logging/BaseAccessLogHandler.java
=> Move from ChannelDuplexHandler to ChannelHandlerAdapter

reactor-netty-core/src/main/java/reactor/netty/NettyPipeline.java, reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/client/PrematureCloseException.java
=> Move from ChannelInboundHandler to ChannelHandler

reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java
=> Move from ChannelOutboundHandler to ChannelHandler

reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/NonSslRedirectHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
=> Replace ChannelFutureListener#CLOSE to ChannelFutureListeners#CLOSE

reactor-netty-core/src/main/java/reactor/netty/resources/ColocatedEventLoopGroup.java
=> Adapt ColocatedEventLoopGroup to the new EventLoopGroup

reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpOperationsTest.java
=> Replace LastHttpContent.EMPTY_LAST_CONTENT with EmptyLastHttpContent

reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
=> Use directly SingleThreadEventExecutor

reactor-netty-core/src/main/java/reactor/netty/resources/DefaultLoopResources.java, reactor-netty-core/src/test/java/reactor/netty/resources/DefaultLoopResourcesTest.java, reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java, reactor-netty-core/src/test/java/reactor/netty/resources/PooledConnectionProviderCustomMetricsTest.java, reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java, reactor-netty-core/src/test/java/reactor/netty/transport/ClientTransportTest.java, reactor-netty-core/src/test/java/reactor/netty/udp/UdpClientTest.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
=> Move from NioEventLoopGroup to MultithreadEventLoopGroup

reactor-netty-core/src/main/java/reactor/netty/tcp/SniProvider.java, reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java, reactor-netty-core/src/test/java/reactor/netty/NettyOutboundTest.java, reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java, reactor-netty-http/src/test/java/reactor/netty/tcp/SslProviderTests.java
Adapt to the changes in `AbstractSniHandler`
=> Create SslHandler with BufferAllocator

reactor-netty-core/src/main/java/reactor/netty/transport/logging/ReactorNettyLoggingHandler.java
=> ReactorNettyLoggingHandler to use BufferFormat

reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java, reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java
=> Adapt TransportConnector to the changes in channel.register()

reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
=> SendManyInner implements FutureListener

reactor-netty-core/src/test/java/reactor/netty/NettyOutboundTest.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java
Move from ChannelFuture to Future
=> Move from ChannelFutureListener to FutureListener

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerFormDecoderProvider.java
This is an additional change to #2222
=> Remove imports to multipart

reactor-netty-http/src/main/java/reactor/netty/http/server/HAProxyMessageReader.java
=> HAProxyMessage is now a Resource

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpOperationsTest.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientOperationsTest.java, reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
HTTP content() is now payload()
Websocket content() is now binaryData()
=> Replace ByteBuf.release() with Buffer.close()

reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/websocket/WebsocketOutbound.java, reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
=> Migrate Websocket to the new API

reactor-netty-core/src/main/java/reactor/netty/NettyOutbound.java, reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java, reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java, reactor-netty-core/src/test/java/reactor/netty/NettyOutboundTest.java, reactor-netty-http/src/main/java/reactor/netty/http/HttpOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/websocket/WebsocketOutbound.java
=> Add new NettyOutbound#bufferAlloc

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
=> Move read request from handlerAdded to channelRegistered

reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java
=> Temporary exclude the check for the type of the executor

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
=> Replace usage ReferenceCountUtil.release(...) with Resource.dispose(...)

reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
=> DefaultLastHttpContent is not DefaultHttpContent anymore but HttpContent

reactor-netty-http/src/main/java/reactor/netty/http/client/AbstractHttpClientMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/logging/AccessLogHandlerH1.java
=> AbstractHttpClientMetricsHandler/AbstractHttpServerMetricsHandler/AccessLogHandlerH1 works now only with Buffer

README.md, reactor-netty-core/src/main/java/reactor/netty/BufferFlux.java, reactor-netty-core/src/test/java/reactor/netty/BufferFluxTest.java, reactor-netty-core/src/test/java/reactor/netty/transport/logging/ReactorNettyLoggingHandlerTest.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/test/java/reactor/netty/BufferFluxTest.java, reactor-netty-http/src/test/java/reactor/netty/channel/FluxReceiveTest.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java, reactor-netty-http/src/test/java/reactor/netty/http/client/UrlExceptionTest.java, reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java, reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpSendFileTests.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java, reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogHandlerH1Tests.java
There are no changes in the API
=> Rename ByteBuf with Buffer

reactor-netty-http/src/test/java/reactor/netty/http/server/logging/AccessLogHandlerH2Tests.java
=> DefaultHttp2DataFrame works with Send<Buffer>

.github/workflows/check_transport.yml, build.gradle, gradle.properties, reactor-netty-core/build.gradle, reactor-netty-examples/build.gradle, reactor-netty-http/build.gradle, reactor-netty-http/src/test/java/reactor/netty/http/HttpTests.java
Netty Contrib SNAPSHOT versions are needed for a successful build
=> Temporary build on CI Netty Contrib projects

reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java
Related to Netty 5 change https://github.com/netty/netty/pull/9529
=> Adapt to the changed semantic for EmbeddedChannel

reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpSendFileTests.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpsSendFileTests.java
=> Enable tests for transferring files

.github/workflows/check_transport.yml, reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java, reactor-netty-core/src/test/java/reactor/netty/transport/TransportEventLoopMetricsTest.java, reactor-netty-http/src/test/java/reactor/netty/resources/PooledConnectionProviderDefaultMetricsTest.java
Remove the temporary workarounds from CI build
=> Adapt to the changed in AbstractChannel

.github/workflows/check_transport.yml, reactor-netty-core/src/main/java/reactor/netty/channel/MonoSendMany.java
https://github.com/netty-contrib/socks-proxy/pull/10
=> Temporary build on CI with PR in sock-proxy

reactor-netty-core/build.gradle, reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java, reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java, reactor-netty-http/build.gradle, reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java, reactor-netty/build.gradle
Adapt to the changes in the `artifact id` for `context propagation` and `micrometer tracing`
=> Adapt to the changes in the context propagation API

.github/workflows/check_transport.yml, reactor-netty-core/src/test/java/reactor/netty/ReactorNettyTest.java
- Adapt to the changes for asynchronous connect in `AbstractChannel`
https://github.com/netty/netty/pull/12570
- Adapt the CI to the changes made in `Future` interface
https://github.com/netty/netty/pull/12569
=> Adapt to the changes for asynchronous connect in AbstractChannel

.github/workflows/check_transport.yml, build.gradle
=> Update to Netty 5.0.0.Alpha3

build.gradle
Update Micrometer Tracing dependency to version 1.0.0-M6
Update Micrometer Docs Generator dependency to version 1.0.0-M5
Update Context Propagation dependency to version 1.0.0-M3
=> Update Micrometer dependency to version 1.10.0-M3

README.md, docs/asciidoc/getting-started.adoc, docs/asciidoc/http-client-conn-provider.adoc, docs/asciidoc/http-client.adoc, docs/asciidoc/http-server.adoc, docs/asciidoc/proxy.adoc, docs/asciidoc/tcp-client-conn-provider.adoc, docs/asciidoc/tcp-client.adoc, docs/asciidoc/tcp-server.adoc, docs/asciidoc/udp-client.adoc, docs/asciidoc/udp-server.adoc, docs/asciidoc/wire-logger.adoc
- Update to the new Reactor Netty packages and fix the links
- Update to the new Netty 5 packages and fix the links
- Update Java version to 17 and fix the links
=> Update Reference Documentation

build.gradle, reactor-netty-core/build.gradle, reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java, reactor-netty-core/src/main/java/reactor/netty/internal/util/Metrics.java, reactor-netty-core/src/main/java/reactor/netty/observability/ReactorNettyTracingObservationHandler.java, reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/ContextPropagationUtils.java, reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java, reactor-netty-core/src/main/java/reactor/netty/transport/Transport.java, reactor-netty-core/src/main/java/reactor/netty/transport/TransportConfig.java, reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java, reactor-netty-http/build.gradle, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java, reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java, reactor-netty-http/src/noMicrometerTest/java/reactor/netty/http/client/HttpClientNoMicrometerTest.java, reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Make context propagation optional dependency
=> Use the new API Observation#parentObservation

gradle/wrapper/gradle-wrapper.properties
`./gradlew wrapper --gradle-version=7.5.1`
=> Upgrade to Gradle v7.5.1

build.gradle
- Micrometer dependency to version 1.10.0-M4
- Micrometer Tracing dependency to version 1.0.0-M7
- Micrometer Docs Generator dependency to version 1.0.0-M6
- Context Propagation dependency to version 1.0.0-M4
=> Update Micrometer dependencies

.github/workflows/check_transport.yml, reactor-netty5-core/src/test/java/reactor/netty5/NettyOutboundTest.java, reactor-netty5-core/src/test/java/reactor/netty5/udp/UdpClientTest.java, reactor-netty5-core/src/test/java/reactor/netty5/udp/UdpMetricsTests.java, reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/http/client/websocket/Application.java, reactor-netty5-examples/src/main/java/reactor/netty5/examples/documentation/udp/server/send/Application.java, reactor-netty5-http/src/test/java/reactor/netty5/http/HttpOperationsTest.java, reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientOperationsTest.java, reactor-netty5-http/src/test/java/reactor/netty5/http/client/HttpClientTest.java
This PR adapts to the recent change made in the following Netty PR:
Remove Charset constants from CharsetUtil (https://github.com/netty/netty/pull/12741)
=> Adapt to netty changes for CharsetUtil

reactor-netty-http/src/test/java/reactor/netty/http/observability/ObservabilitySmokeTest.java
Accommodate the breaking change in `SampleTestRunner` introduced by https://github.com/micrometer-metrics/tracing/pull/57
=> Adapt SampleTestRunner change in micrometer tracing

reactor-netty5-http/src/main/java/reactor/netty5/http/server/HttpServerOperations.java
https://github.com/netty/netty/pull/12832
=> Adapt to the changed DefaultHttpHeaders#validateKey

build.gradle, reactor-netty5-core/build.gradle, reactor-netty5-core/src/main/java/reactor/netty5/ReactorNetty.java, reactor-netty5-core/src/main/java/reactor/netty5/channel/MonoSend.java, reactor-netty5-core/src/main/java/reactor/netty5/channel/MonoSendMany.java, reactor-netty5-core/src/main/java/reactor/netty5/transport/logging/AdvancedBufferFormat.java, reactor-netty5-core/src/main/java/reactor/netty5/transport/logging/ReactorNettyLoggingHandler.java, reactor-netty5-core/src/test/java/reactor/netty5/transport/logging/ReactorNettyLoggingHandlerTest.java, reactor-netty5-http/build.gradle
Remove the dependency to the old ByteBuf API
=> [reactor-netty-core] Remove ByteBufHolder usage

build.gradle, reactor-netty-core/src/main/java/reactor/netty/channel/ChannelMeters.java, reactor-netty-core/src/main/java/reactor/netty/channel/ConnectObservations.java, reactor-netty-core/src/main/java/reactor/netty/channel/ConnectSpans.java, reactor-netty-core/src/main/java/reactor/netty/channel/MicrometerChannelMetricsHandler.java, reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProviderMeters.java, reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeObservations.java, reactor-netty-core/src/main/java/reactor/netty/tcp/TlsHandshakeSpans.java, reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMeters.java, reactor-netty-core/src/main/java/reactor/netty/transport/EventLoopMeters.java, reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionObservations.java, reactor-netty-core/src/main/java/reactor/netty/transport/HostnameResolutionSpans.java, reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientMeters.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientObservations.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSpans.java, reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerMeters.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerObservations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerSpans.java, reactor-netty-http/src/main/java/reactor/netty/http/server/MicrometerHttpServerMetricsHandler.java
Update Micrometer Tracing dependency to version 1.0.0-SNAPSHOT
Update Micrometer Docs Generator dependency to version 1.0.0-SNAPSHOT
Update Context Propagation dependency to version 1.0.0-SNAPSHOT
=> Update Micrometer dependencies to 1.10.0-SNAPSHOT before RC1

build.gradle
Update Micrometer Tracing dependency to version 1.0.0-RC1
Update Micrometer Docs Generator dependency to version 1.0.0-RC1
Update Context Propagation dependency to version 1.0.0-RC1
=> Update Micrometer dependencies to 1.10.0-RC1

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java, reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java, reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
this fix addresses https://github.com/rsocket/rsocket-java/issues/1050
=> ensures flux receiver terminates subscriber on dispose

reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
This PR just proposes a small refactoring in the FluxReceive class, and is a follow up from the #2441 issue (I actually did not have time to review it before it was merged).
So, first, just a nit: before the [getPending](https://github.com/reactor/reactor-netty/blob/1.0.x/reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java#L117) method, there are two lines separator;
Also, there are some duplicate codes between [cancel](https://github.com/reactor/reactor-netty/blob/1.0.x/reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java#L109-L114) and [dispose](https://github.com/reactor/reactor-netty/blob/1.0.x/reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java#L129-L134), as well as between the …
=> Small refactoring in FluxReceive

build.gradle
Update Micrometer Tracing dependency to version 1.0.0-SNAPSHOT 
Update Micrometer Docs Generator dependency to version 1.0.0-SNAPSHOT 
Update Context Propagation dependency to version 1.0.0-SNAPSHOT
=> Update Micrometer dependencies to 1.10.0-SNAPSHOT before GA

build.gradle
Update Micrometer Tracing dependency to version 1.0.0
Update Micrometer Docs Generator dependency to version 1.0.0
Update Context Propagation dependency to version 1.0.0
=> Update Micrometer dependencies to 1.10.0

build.gradle, reactor-netty5-core/build.gradle, reactor-netty5-core/src/main/java/reactor/netty5/resources/DefaultLoopIOUring.java, reactor-netty5-core/src/main/java/reactor/netty5/resources/DefaultLoopNativeDetector.java, reactor-netty5-http/build.gradle, reactor-netty5/build.gradle
`io_uring` transport is now part of Netty 5
Fixes #2217
=> Reintegrate io_uring transport into netty5 branch

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java, reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
=> Ensure Http2Pool can be stopped gracefully

build.gradle, reactor-netty-core/build.gradle, reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ChannelContextAccessorTest.java, reactor-netty-core/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java, reactor-netty-core/src/contextPropagationTest/java/reactor/netty/TestThreadLocalAccessor.java, reactor-netty-core/src/contextPropagationTest/java/reactor/netty/TestThreadLocalHolder.java, reactor-netty-core/src/contextPropagationTest/resources/logback.xml, reactor-netty-core/src/main/java/reactor/netty/ReactorNetty.java, reactor-netty-core/src/main/java/reactor/netty/contextpropagation/ChannelContextAccessor.java, reactor-netty-core/src/main/java/reactor/netty/contextpropagation/package-info.java, reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java, reactor-netty-core/src/main/resources/META-INF/services/io.micrometer.context.ContextAccessor, reactor-netty-http/build.gradle, reactor-netty-http/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java, reactor-netty-http/src/contextPropagationTest/resources/logback.xml, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java
This is a back port for PR #2588
=> Support context propagation for `ChannelHandler`

docs/asciidoc/http-client.adoc, docs/asciidoc/tcp-client.adoc, reactor-netty-core/build.gradle, reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java, reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java
- Support user-provided DnsCache for NameResolverProvider
=> Support configurable DNS resolver cache

reactor-netty-examples/src/main/java/reactor/netty/examples/tcp/telnet/TelnetClient.java, reactor-netty-examples/src/main/java/reactor/netty/examples/tcp/telnet/TelnetServer.java
This PR attempts to provide a corresponding Reactor Netty version of Telnet example available in Netty project.
=> Add Reactor Netty version of Telnet example #761

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java
Related to Gitter discussion
https://gitter.im/reactor/reactor-netty?at=63a967e50cd40c2e89a73d7d
=> Ensure response can disable `HttpServer` compression configuration

reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
=> Replace `AccessLogAppender` with `LogTracker`

reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java, reactor-netty-http/src/test/java/reactor/netty/http/server/ConnectionInfoTests.java
=> Handling `X-Forwarded-Host` with value `host:port`

reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicInitialSettingsSpec.java
=> Replace `Objects.hash()`

reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java
Extend the comments for `channel#close` invocation
=> Add `DEBUG` log for `ServerTransport#disposeNow`

docs/asciidoc/http-client.adoc, docs/asciidoc/tcp-client.adoc, reactor-netty-core/build.gradle, reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java, reactor-netty-core/src/test/java/reactor/netty/transport/NameResolverProviderTest.java
Support a user provided function to build a DnsAddressResolverGroup
=> Support a custom `DnsAddressResolverGroup` builder function

reactor-netty-core/src/main/java/reactor/netty/Metrics.java
=> Add API for configuring custom `ObservationRegistry`

reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
=> Ensure connection closed when non `200` status for request with `Expect` header and incoming data not completed

docs/asciidoc/eventloop.adoc, docs/asciidoc/http-client.adoc, docs/asciidoc/http-server.adoc, docs/asciidoc/tcp-client.adoc, docs/asciidoc/tcp-server.adoc, docs/asciidoc/udp-client.adoc, docs/asciidoc/udp-server.adoc, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/eventloop/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/eventloop/Application.java
Related to https://github.com/reactor/reactor-netty/issues/2943#issuecomment-1782880888
=> Update reference documentation for event loop group

reactor-netty-core/src/main/java/reactor/netty/channel/AbstractChannelMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
=> Ensure `HttpServer` `connections.total` metric is correct when connection close happens before connection open

reactor-netty-http/build.gradle, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientSpec.java, reactor-netty-http/src/main/java/reactor/netty/http/client/WebsocketClientSpecImpl.java, reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerSpec.java, reactor-netty-http/src/main/java/reactor/netty/http/server/WebsocketServerSpecImpl.java, reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
=> Add support for websocket `client_no_context_takeover` and `server_no_context_takeover` extension parameters

reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProviderMeters.java, reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/MicrometerPoolMetricsRecorder.java, reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java, reactor-netty-core/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2ConnectionProviderMeters.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java, reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerPoolMetricsRecorder.java, reactor-netty-http/src/test/java/reactor/netty/http/client/Http2PoolTest.java, reactor-netty-http/src/test/java/reactor/netty/resources/DefaultPooledConnectionProviderTest.java
=> Expose metrics for `pending acquire` operation latency

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpRedirectTest.java
This is a regression caused by PR #2994
Fixes #3035
=> Ensure cookies can be added by `BiConsumer` provided with `HttpClient#followRedirect`

docs/asciidoc/http-client-conn-provider.adoc
=> Add info for `HTTP/2` connection pool metrics

docs/asciidoc/eventloop.adoc, docs/asciidoc/http-client-conn-provider.adoc, docs/asciidoc/tcp-client-conn-provider.adoc
=> Add `How To` dispose `Event Loop Group`/`Connection Pool`

docs/modules/ROOT/pages/tcp-server.adoc
Users can use `expand`/`collapse foldable text`
=> Keep the `indent` 0

docs/antora.yml, docs/modules/ROOT/pages/http-client.adoc, docs/modules/ROOT/pages/http-server.adoc, docs/modules/ROOT/pages/tcp-client.adoc, docs/modules/ROOT/pages/tcp-server.adoc, docs/modules/ROOT/pages/udp-client.adoc, docs/modules/ROOT/pages/udp-server.adoc, docs/modules/ROOT/partials/eventloop.adoc, docs/modules/ROOT/partials/http-client-conn-provider.adoc, docs/modules/ROOT/partials/proxy.adoc, docs/modules/ROOT/partials/tcp-client-conn-provider.adoc, docs/modules/ROOT/partials/wire-logger.adoc
- Remove unnecessary attributes
- Add global attribute for the source type
=> Add links to the examples

build.gradle, reactor-netty-examples/build.gradle, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/tracing/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/tracing/custom/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/tracing/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/tracing/custom/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/tracing/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/tracing/custom/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/tracing/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/tracing/custom/Application.java
Bump `Zipkin` reporter version to `3.3.0`
=> Depend on `Brave` `v6.0.2`

build.gradle, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/tracing/custom/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/tracing/custom/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/tracing/custom/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/tracing/custom/Application.java, reactor-netty-http/build.gradle, reactor-netty-http/src/contextPropagationTest/java/reactor/netty/ContextPropagationTest.java
Depend on `Micrometer Tracing` `v1.3.0-SNAPSHOT`
Depend on `Micrometer Doc Generator` `v1.0.2`
Depend on `Context Propagation` `v1.1.0`
=> Depend on `Micrometer` `v1.13.0-SNAPSHOT`

reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
=> Add `compression` for `HTTP/3` server support

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/ConnectionInfo.java, reactor-netty-http/src/main/java/reactor/netty/http/server/Http2StreamBridgeServerHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java, reactor-netty-http/src/main/java/reactor/netty/http/server/Http3ServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/Http3StreamBridgeServerHandler.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpTrafficHandler.java
=> Add `metrics` for `HTTP/3` server support

build.gradle
Depend on `Micrometer Tracing` `v1.3.0`
=> Depend on `Micrometer` `v1.13.0`

reactor-netty-http/src/test/java/reactor/netty/http/client/WebsocketTest.java
=> Test `TooLongFrameException` is propagated and connection closed

reactor-netty-http/src/http3Test/java/reactor/netty/http/Http3Tests.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConnect.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientSecure.java, reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerBind.java
=> Add `HttpProtocol#HTTP3`

reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java, reactor-netty-http/src/main/java/reactor/netty/http/client/Http3Pool.java
=> Add `Http3Pool`

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClient.java, reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientConfig.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpCompressionClientServerTests.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
This change is based on PR #2848
=> Add `Brotli` support for `HttpClient`

reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java, reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java
=> Always `decode` in an event loop

.github/dependabot.yml, build.gradle
Depend on `Micrometer Tracing` 1.4.0-SNAPSHOT
=> Depend on `Micrometer` 1.14.0-SNAPSHOT

.github/workflows/check_netty_snapshots.yml, .github/workflows/check_reactor_core_3.6_snapshots.yml, .github/workflows/check_transport.yml, .github/workflows/publish.yml, build.gradle, docs/modules/ROOT/pages/http-client.adoc, docs/modules/ROOT/pages/http-server.adoc, docs/modules/ROOT/pages/tcp-client.adoc, docs/modules/ROOT/pages/tcp-server.adoc, gradle/toolchains.gradle, reactor-netty-core/build.gradle, reactor-netty-core/src/jarFileTest/java/reactor/netty/JarFileShadingTest.java, reactor-netty-core/src/main/java/reactor/netty/resources/DefaultPooledConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/resources/NewConnectionProvider.java, reactor-netty-core/src/main/java/reactor/netty/transport/AddressUtils.java, reactor-netty-core/src/main/java/reactor/netty/transport/DomainSocketAddressUtils.java, reactor-netty-core/src/main/java/reactor/netty/transport/ServerTransport.java, reactor-netty-core/src/main/java/reactor/netty/transport/TransportConnector.java, reactor-netty-core/src/main/java17/reactor/netty/resources/DefaultLoopNIO.java, reactor-netty-core/src/main/java17/reactor/netty/transport/DomainSocketAddressUtils.java, reactor-netty-core/src/test/java/reactor/netty/NativeConfigTest.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/client/uds/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/http/server/uds/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/client/uds/Application.java, reactor-netty-examples/src/main/java/reactor/netty/examples/documentation/tcp/server/uds/Application.java, reactor-netty-http/build.gradle, reactor-netty-http/src/main/java/reactor/netty/http/client/UriEndpoint.java, reactor-netty-http/src/test/java/reactor/netty/http/server/HttpServerTests.java
Add `multi-release` jar support
=> Add `Unix Domain Sockets` support on `NIO` transport

build.gradle
Depend on `Micrometer Tracing` `v1.4.0`
=> Depend on `Micrometer` `v1.14.0`

reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClient.java, reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClientConfig.java, reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicClientConnect.java, reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicOperations.java, reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicResources.java, reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicServer.java, reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicServerBind.java, reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicServerConfig.java, reactor-netty-incubator-quic/src/main/java/reactor/netty/incubator/quic/QuicTransportConfig.java, reactor-netty-incubator-quic/src/test/java/reactor/netty/incubator/quic/BaseQuicTests.java
=> Annotate with `Nullable`, fields that can become null

reactor-netty-http/src/main/java/reactor/netty/http/client/HttpClientOperations.java, reactor-netty-http/src/test/java/reactor/netty/http/HttpProtocolsTests.java
=> Ensure `POST` empty body sending `content-length 0`

reactor-netty-core/src/main/java/reactor/netty/tcp/SslProvider.java, reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java, reactor-netty-http/src/main/java/reactor/netty/http/Http2SettingsSpec.java, reactor-netty-http/src/main/java/reactor/netty/http/Http3SettingsSpec.java
=> Add `Nullable` annotation to `equals` method

build.gradle
Depend on Micrometer Tracing 1.5.0-M3
=> Depend on `Micrometer` `1.15.0-M3`

reactor-netty-core/src/main/java/reactor/netty/tcp/TcpResources.java
The max connection is set up 500 by default. It's hard to optimize it .
=> Enable set up `TcpResources` default max connection by setting

reactor-netty-http/src/main/java/reactor/netty/http/server/compression/DeflateOption.java, reactor-netty-http/src/main/java/reactor/netty/http/server/compression/GzipOption.java, reactor-netty-http/src/main/java/reactor/netty/http/server/compression/ZstdOption.java
=> Ensure the default compression configuration is taken from Netty

reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java
=> Remove extra write invocation when `Expect: 100-continue`

reactor-netty-core/src/test/java/reactor/netty/tcp/TcpClientTests.java, reactor-netty-core/src/test/java/reactor/netty/tcp/TcpServerTests.java, reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
There is a problem with Ubuntu runners, we need to disable some tests in order to perform the release.
=> Temporary disable test

build.gradle
Depend on `Micrometer Tracing` `1.5.0`
=> Depend on `Micrometer` `1.15.0`

reactor-netty-http/src/main/java/reactor/netty/http/server/DefaultHttpForwardedHeaderHandler.java
https://datatracker.ietf.org/doc/html/rfc3986#section-3.1
=> Improve protocol validation in `Forwarded`/`X-Forwarded-Proto` header parsing

docs/modules/ROOT/pages/getting-started.adoc
Removing old reference to support listing and adding new link to webpage.
=> Update support listing reference

build.gradle
Depend on `Micrometer Tracing` `1.6.0-M1`
=> Depend on `Micrometer` `1.16.0-M1`

reactor-netty-core/build.gradle, reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java, reactor-netty-core/src/test/java/reactor/netty/transport/ProxyProviderTest.java
=> Support `Proxy-Authorization` renewal

.github/workflows/check_graalvm.yml, .github/workflows/check_netty_snapshots.yml, .github/workflows/check_transport.yml, .github/workflows/codeql-analysis.yml, .github/workflows/publish.yml
`macos-13` runner is deprecated
https://github.com/actions/runner-images/issues/13046
=> Switch to `macOS-14` runner
